lib/rss.js
pages/rss.js

Related to https://github.com/stackernews/stacker.news/issues/16
A SSR solution for a RSS feed:
+ feed has latest items (live)
- each request impacts server (load)
It's also possible to use a SSG solution (ex: /public/rss.xml file):
+ static file, no load on the server (faster)
- xml file is only created on build time (delay)
Note, I was not able to properly test the query.

Implements rss feed

---

components/comment.js

Currently there's a space or "\" missing, e.g. https://stacker.news/items/5747 .
This PR also aligns this with https://github.com/stackernews/stacker.news/blob/master/components/item.js

Add "\" after boost in comments

---

pages/wallet.js

I noticed a typo the word 'Your' should say 'You':

Typo fix on wallet page

---

styles/globals.scss

I changed the overflow to `auto` so that it's not always showing the scroll when it's not needed.
@huumn we discussed the issue here: https://stacker.news/items/73723

change drop down scroll to auto

---

components/price.js

As discussed in https://stacker.news/items/83883.
I noticed that for ZAR, there is a space between the symbol and amount.
See https://en.wikipedia.org/wiki/South_African_rand (see "Denomination" at right side)
For EUR or USD, there is no such space:
https://en.wikipedia.org/wiki/Euro
https://en.wikipedia.org/wiki/United_States_dollar

Add ZAR currency

---

.env.sample
api/slashtags/index.js

This also makes `SLASHTAGS_SECRET` optional.
If none is set, random bytes will be generated. This is useful for local development.

Mention slashtags auth in README

---

components/reply.js

Closes #237 
https://user-images.githubusercontent.com/27162016/220821282-6e914a87-5fb6-4a30-bbc0-b6c5e488ee16.mp4
I wasn't entirely sure if with "comment textareas" every textarea is meant or only comment replies.
To not have autofocus for directly replying to posts, only `!replyOpen` needs to be added to the condition in `useEffect`.

Autofocus reply inputs

---

Dockerfile
worker/Dockerfile

Update docker container to latest stable Debian release ("bullseye") and latest version of Node.js 14, to fix this build error on MacOS:
```
error - unhandledRejection: Error: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /app/node_modules/sodium-native/prebuilds/linux-arm64/node.napi.node)
at Object.Module._extensions..node (internal/modules/cjs/loader.js:1127:18)
at Module.load (internal/modules/cjs/loader.js:933:32)
at Function.Module._load (internal/modules/cjs/loader.js:774:14)
at Module.require (internal/modules/cjs/loader.js:957:19)
at require (internal/modules/cjs/helpers.js:88:18)
at load (/app/node_modules/node-gyp-build/index.js:22:10)
at Object.<anonymous> (/app/node_modules/sodium-native/index.js:1:43)
at Module._compile …
```

upgrade debian version in docker containers

---

Dockerfile
docker-compose.yml
worker/Dockerfile
worker/wait-for-it.sh

Current:
Both the app and worker containers mount the host volume containing the source code. Currently, both run `npm install` which results in concurrently building the same code.
Proposed changes:
Run `npm install` in the `app` container only; the worker process waits for the install to complete before starting up.

Only run `npm install` once during `docker compose up`; worker process waits for this to complete

---

styles/globals.scss

This fixes the issue mentioned in https://stacker.news/items/172931.
The reason why the dropdown items were not visible on darkmode was that browsers which use WebKit/Blink (fork of WebKit) as the rendering engine seem to use the color of the selected item for the options, too.
Chrome and Brave use Blink since they include `WebKit/537.36` in their user agent header [0]. Firefox uses Gecko.
However, this also seems to be OS-dependent since you mentioned that Brave on iOS and Chrome on macOS works.
So I did a bit of research and found the following:
> Most of Chrome's source code comes from Google's free and open-source software project Chromium, but Chrome is licensed as proprietary freeware. WebKit was the original rendering engine, but Google eventually forked it to create the Blink …

Fix dropdown items not visible in darkmode on some browsers

---

pages/login.js
pages/signup.js

This should fix the open redirect mentioned in #264.
**However, I wasn't able to test this since I can't login/signup on my local machine at the moment.**
I just tested that `decodeURIComponent` and the regex work as I expected manually:
```
// open_redirect_test.js
const regex = /^https?:\/\/stacker.news\/?/
let callbackUrl = "https%3A%2F%2Fwww.google.com%2F"
let decoded = decodeURIComponent(callbackUrl)
let isExternal = !regex.test(decoded) 
console.log(isExternal) // should print true
callbackUrl = "https%3A%2F%2Fstacker.news%2F"
decoded = decodeURIComponent(callbackUrl)
isExternal = !regex.test(decoded)
console.log(isExternal) // should print false
```
```
$ node open_redirect_test.js
true
false
```
These changes should return 500 Internal Server Error if there exists a session …

Return 500 if callback URL is external

---

README.md

I think it would also be good to add similar text to the [FAQ](https://stacker.news/faq) since @orthzar mentioned he only looked there. Maybe others will only look there, too.
However, I think this must be done by updating the database entry for the item the FAQ points to.
I think below "Where Should I Submit Bug Reports?" would be best.
So like this:
> #### Where Should I Submit Bug Reports?
>Also the git repo https://github.com/stackernews/stacker.news/issues.
>
>#### I found a vulnerability. How to responsibly disclose it?
>
>Please contact us via [kk@stacker.news](mailto:kk@stacker.news) or t.me/k00bideh.
For reference: https://stacker.news/items/175117

Add contacts for responsible disclosure to README

---

Dockerfile
package-lock.json
package.json

When running `npm install` with node v14.17.0, the dependency `react-longpress@1.1.1` showed a warning that it needs `react@^16.4.0`:
```
$ node --version
v14.17.0
$ npm --version
6.14.13
$ npm install
npm WARN @lexical/yjs@0.7.5 requires a peer of yjs@>=13.5.22 but none is installed. You must install peer dependencies yourself.
npm WARN react-longpressable@1.1.1 requires a peer of react@^16.4.0 but none is installed. You must install peer dependencies yourself.
npm WARN use-dark-mode@2.3.1 requires a peer of react@^16.8.0 but none is installed. You must install peer dependencies yourself.
audited 1449 packages in 3.402s
278 packages are looking for funding
run `npm fund` for details
found 25 vulnerabilities (1 low, 9 moderate, 14 high, 1 critical)
run `npm audit fix` to fix them, or `npm …
```

Upgrade node to v16.16.0

---

components/link-form.js

There are two flows when clearing both inputs:
1. First clear title, then clear URL, then enter new URL
In this case, new data will be fetched when the URL is cleared since the title is empty. Due to the fetch with empty variables, the fetched data is essentially reset. Entering a new URL thus triggers a new fetch (since title is still empty) and the fetched data is shown since it is different compared to the previous render.
2. First clear URL, then clear title, then enter new URL
In this case, new data will not be fetched when the URL is cleared since the title is not empty. When entering a new URL, new data is fetched but will not be shown since the fetched data was never reset and thus did not change compared to the previous render.
This is fixed by always either a) resetting the …

Fix fetched data not shown if last action was title clear

---

.env.sample
components/footer.js
styles/globals.scss

You can use `git rev-parse --short HEAD` to get a short commit hash for the env var `NEXT_PUBLIC_COMMIT_HASH`
Close #275

Show version in footer

---

components/form.js

As mentioned in our call, I would love to use CTRL+K to insert Markdown link formatting [like in GH](https://docs.github.com/en/get-started/using-github/keyboard-shortcuts#source-code-editing).
In my opinion, this is ready to ship but something to notice is that [`document.execCommand()` is deprecated](https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand) but still works as mentioned in [this SO answer](https://stackoverflow.com/a/62266439) and is still supported by every browser according to the [section about browser compatibility](https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand#browser_compatibility).
Also, it is mentioned that when it is unsupported, it will just return `false`: 
> **Return value**
A boolean value that is false if the command is …

Add Markdown formatting hotkeys: CTRL+K, CTRL+I, CTRL+B

---

lib/rss.js

Since we are already using `<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">`, I looked up the RFC for and have noticed that it also has a tag for authors: `<atom:author>`
See https://datatracker.ietf.org/doc/html/rfc4287#section-4.2.1
Closes #139

Use <atom:author> in RSS feeds

---

components/footer.js

looks the same on desktop and mobile:

Add SimpleX group invite to footer

---

components/form.js

Closes #327
```diff
diff --git a/components/form.js b/components/form.js
index 4567897..8710322 100644
--- a/components/form.js
+++ b/components/form.js
@@ -457,6 +457,7 @@ export function Form ({
validateOnBlur={false}
onSubmit={async (values, ...args) =>
onSubmit && onSubmit(values, ...args).then(() => {
+          console.trace()
if (!storageKeyPrefix) return
Object.keys(values).forEach(v => {
localStorage.removeItem(storageKeyPrefix + '-' + v)
```
First trace:
```
form.js:460 console.trace
eval @ form.js:460
Promise.then (async)
_callee$ @ form.js:459
[...]
eval @ form.js:458
[...]
onKeyDown @ form.js:249
[...]
```
_form.js:249_:
```javascript
245 <BootstrapForm.Control
246   onKeyDown={(e) => {
247     const metaOrCtrl = e.metaKey || e.ctrlKey
248       if (metaOrCtrl) {
249 …
```

Fix double submit

---

components/form.js

Slipped into the code in #328 (it's not automatically removed by standardjs when formatting)

Remove unused var

---

components/form.module.css

Close #333 
Since I only changed the CSS rules for the `markdownInput` class, I don't expect this to have any other unexpected changes.
https://github.com/stackernews/stacker.news/assets/27162016/7deb12e8-a463-4bd3-8e9d-baa0c48a80f0

Fix different font between write and preview

---

README.md
api/resolvers/imgproxy/index.js
api/webPush/index.js

Make web push & imgproxy setup optional for local dev

---

components/serviceworker.js
package-lock.json
package.json
sw/index.js

Close #354 (hopefully)
I tested this code using this patch:
```diff
diff --git a/sw/index.js b/sw/index.js
index c8dbee1..38c41ed 100644
--- a/sw/index.js
+++ b/sw/index.js
@@ -86,10 +86,12 @@ async function handlePushSubscriptionChange (oldSubscription, newSubscription) {
newSubscription ??= await self.registration.pushManager.getSubscription()
if (!newSubscription) {
// no subscription exists at the moment
+    console.log('no active push subscription found')
return
}
if (oldSubscription?.endpoint === newSubscription.endpoint) {
// subscription did not change. no need to sync with server
+    console.log('push subscription did not change. no need for sync. skipping')
return
}
// convert keys from ArrayBuffer to string
@@ -107,6 +109,7 @@ async function handlePushSubscriptionChange …
```

Sync push subscriptions on every page load

---

components/comment.js
components/item-info.js

This PR updates the Comment and ItemInfo components to render comment/reply counts using the appropriate singular/plural label, based on the number of comments/replies.
Apparently this has bothered me enough to fix it :)

Comment, Reply count singular/plural labels

---

components/form.js
components/user-header.js

Support an optional debounce prop on Input component
If provided, the debounce is applied to the validation of the containing form, imperatively invoking form validation after debounce is finalized
This also required introducing the `validateOnChange` prop on `Form` which gets passed to `Formik`, and defaults to true, just as it does in `Formik`.
Imperatively invoking form validation seemed to be the only way to debounce the validation call through formik.
Closes #257

Debounce API requests on edit nym by 500ms

---

components/adv-post-form.js
components/form.js

Approach: on input, check for leading/trailing spaces and the leading @ symbol on the username (e.g. when pasting a username with extra characters) and strip them. This has the effect of also restricting the user from typing such characters too.
While working on this, I discovered the drop-down suggestions menu was too sticky; it covered the post button and virtually obliged the user to pick a name in the list (even if not necessary because it was pasted in, e.g.) so I added logic to hide the menu when the user clicks out or tabs away.
(issue #185)

Forward sats to user: text trimming and menu click-out UX improvements

---

api/resolvers/item.js
api/resolvers/rewards.js
api/resolvers/wallet.js
api/typeDefs/index.js
api/typeDefs/item.js
api/typeDefs/itemForward.js
components/adv-post-form.js
components/bounty-form.js
components/discussion-form.js
components/form.js
components/item-full.js
components/link-form.js
components/notifications.js
components/poll-form.js
components/upvote.js
fragments/items.js
lib/constants.js
lib/form.js
lib/validate.js
prisma/migrations/20230814233157_multiforward/migration.sql
prisma/schema.prisma
worker/earn.js

This PR is to address #399, namely allowing users to configure zaps/sats forwarding on posts to up to 5 users, not just 1 user.
Approach taken:
1. Introduce a "ItemForward" model that represents the forwarding of a specific percentage of sats from a particular post to a particular user. There can be up to 5 forward entries for each post
2. Remove the existing "fwdUserId" field on the Item model (migrate existing forwards to the new model as part of the DB migration script)
3. When items and polls are created and updated, ItemForward entries are created/updated accordingly.
4. When a zap occurs on a post with a forwarded item, the item_act function will distribute sats accordingly, based on the forward rules configured.
5. If not 100% of sats are forwarded to other users, the remaining …

multiple forwards on a post

---

components/footer.js

Add meta sub to rss popover in footer and move nostr sub up to top row for 3 and 3 instead of 2 and 4
I mirrored the order from the sub picker select component (home, bitcoin, nostr, tech, meta, jobs)

Add meta sub to rss popover in footer

---

lib/validate.js

If no forward variable is set, the API responds with
> Cannot read properties of undefined (reading 'map')
I have noticed this because [@hn](https://stacker.news/hn) stopped working
> error posting link: [{"message":"Cannot read properties of undefined (reading 'map')"}]
You can test this with the following payload:
_link.json_:
```
{
"operationName": "upsertLink",
"variables": {
"sub": "bitcoin",
"title": "Hacker News",
"url": "https://news.ycombinator.com/"
},
"query": "mutation upsertLink($sub: String, $id: ID, $title: String!, $url: String!, $boost: Int, $forward: [ItemForwardInput], $invoiceHash: String, $invoiceHmac: String) {\n  upsertLink(\n    sub: $sub\n    id: $id\n    title: $title\n    url: $url\n    boost: $boost\n    forward: $forward\n    invoiceHash: $invoiceHash\n …
```

Fix forward required in GraphQL mutations

---

api/resolvers/item.js

Without this, following error is thrown when notifying users about new replies:
> [webPush] error sending user notification:  TypeError: Cannot read properties of undefined (reading 'id')
app  |     at createItemUrl (webpack-internal:///(api)/./api/webPush/index.js:76:29)
app  |     at async sendUserNotification (webpack-internal:///(api)/./api/webPush/index.js:125:33)
app  |     at async Promise.allSettled (index 0)
Bug introduced in a847b16

Fix TypeError during push notifications

---

components/footer.js

1. Use an ActionTooltip to explain what the light/dark mode and lightning buttons are for
2. Open the current commit github link in a new tab

Minor tweaks to the page footer

---

api/resolvers/notifications.js

Update how we query for item-driven notifications to de-dupe them for:
1. mentions
2. replies
3. thread subscriptions
4. user subscriptions
users should recieve only 1 notification for any given item created by another user, following the above priority order
this is accomplished by querying for replies to current user, replies on subscribed threads, items from subscribed users, and mentions (if enabled for the current user), sorting those results by item id and priority order within item id based on notification type, then selecting the highest priority notification from each item id
these results are then union all'ed with all other notification types, unchanged.
Closes #453

De-dupe item-driven notifications

---

components/toast.js
components/toast.module.css

Closes #468 
Side note: I wanted to just do `.toast.bg-success { ... }`, `.toast.bg-danger { ... }` in the CSS module, but with how Next.JS loads CSS modules via className, that didn't seem to work how I'd like, so I went with this approach instead. I am open to different implementations if there's a cleaner option.

toast border color based on variant

---

pages/api/site.webmanifest.js

This overrides OS auto-rotate settings on Android. This means that the PWA does auto-rotate even if the OS setting to auto-rotate is not enabled.
This property is experimental and only supported by Chromium-based browsers anyway.
Also, you can still manually rotate if you want.
Fixes #482

Remove orientation from manifest

---

api/resolvers/item.js
api/resolvers/search.js
components/layout.js
components/search.js
components/search.module.css
components/top-header.js
lib/constants.js
pages/~/search.js

The approach is straightforward: put the search controls at the top of the results list, similarly to the illustrations in the mockups of issue #365. If the user scrolls, the search bar assumes a floating position at the top of the screen and the list of items scrolls underneath it (as also suggested in the mockups).
Representative screenshots non-scrolled and scrolled:
Notes on the CSS changes:
- the searchSection and searchPadding classes are sort of complementary (only one is display: block at a time)
- they both have an associated class "float" that toggles on and off depending on scroll position
- a media query was needed to fill in missing container padding on xs screens (not sure why it was missing). I would have preferred an @include directive not to hard-code the bootstrap xs …

move search bar to top of page

---

prisma/migrations/20230831144120_thread_sub_forward_user/migration.sql

Update create and update item sql functions to subscribe forward recipients to the post
When the post is updated, ensure that if a forward user has already unsubscribed, keep it that way. Also ensure that any forward users that are no longer forward users are removed from subscription
Closes #459

Automatically subscribe forward users to threads

---

components/bounty-form.js
components/discussion-form.js
components/form.js
components/job-form.js
components/link-form.js
components/poll-form.js
lib/form.js

Live counter update to help authors know how many more chars they have to use in their post titles, and also poll options
applies across all post types (discussion, link, poll, bounty, job)

Visual Character counter for post titles, poll options

---

api/resolvers/blockHeight.js
api/resolvers/index.js
api/ssrApollo.js
api/typeDefs/blockHeight.js
api/typeDefs/index.js
components/block-height.js
components/price.js
fragments/block-height.js
fragments/blockHeight.js
pages/_app.js

Source the current block height from [mempool.space API](https://mempool.space/docs/api/rest#get-block-tip-height)
The price carousel now shows (in order):
1. price per BTC in fiat
2. sats per fiat unit
3. 1sat=1sat
4. current block height (I am open to feedback on how to present this number in the carousel)
Closes #435

Add block height to price carousel

---

api/resolvers/item.js
components/bounty-form.js
components/discussion-form.js
components/link-form.js
components/poll-form.js
lib/validate.js

Implemented via dependency injecting `me` into post validation schemas (link, discussion, bounty, poll), then comparing `me?.name` to the specified name for the forward entry.
I validated this on client-side, and also server-side by hitting the API directly, since you can't send to the API through the UI with this invalid state. Same error came back in both cases.

Disallow forwarding sats to yourself

---

api/typeDefs/item.js

Quickfix for the following issue by changing the depth field to Int from Int! in the item.js typeDef
https://github.com/stackernews/stacker.news/issues/492

made Item.depth nullable

---

components/item-full.js
lib/format.js

Introduce `format` option on `numWithUnits` fn, consumed by bounty listing. Format option is disabled by default, and only applicable when `abbreviate` is `false`.
Uses [`Intl.NumberFormat`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat), so it should honor each user's browser locale settings automatically.
Inspired by [this](https://stacker.news/items/255020/r/WeAreAllSatoshi) thread.
Can be used elsewhere in the codebase, but this is the place of inspiration, so I only adopted it here.

Format bounty sats with separators

---

pages/~/search.js
pages/~/search.module.css

This is to address issue #274.
(The ~sub syntax didn't seem to work for me...note to self to check into it.)

Add search hints to initial search page

---

api/resolvers/wallet.js
api/typeDefs/wallet.js
components/form.js
components/notifications.js
fragments/notifications.js
fragments/wallet.js
lib/constants.js
lib/validate.js
pages/api/lnurlp/[username]/index.js
pages/api/lnurlp/[username]/pay.js
pages/satistics.js
pages/wallet.js
prisma/migrations/20230915234627_lnaddr_pay_comments/migration.sql
prisma/schema.prisma

Related to #230 
This PR enhances SN on the receiving end to support comments when someone sends to a user@stacker.news lightning address.
It also enhances the withdraw to lightning address flow _from_ SN to allow comments to be included, if the lightning address provider supports them.
Sample wallet history UI:

Implementing LUD-12 comments on payRequest in LNURLP Lightning Address flow (sending and receiving)

---

api/resolvers/wallet.js
contributors.txt

Not sure how to test, but looking at the `decodePaymentRequest` docs this looks correct.

Verify invoice amount in lightning address withdrawal

---

pages/rewards/index.js

Danger case was already handled by the common `Form` component, but success wasn't toasted. I like having feedback on actions like this one.
Now, the danger toast message is also specific to the donate action, and not just the underlying JS error that occurred (which is logged, instead).

Toast success and danger for donate action

---

api/resolvers/item.js
api/resolvers/rewards.js
api/typeDefs/rewards.js
pages/rewards/index.js

Now you can just-in-time fund your account to donate to SN's reward pool.
You can also donate without an account via the `anon` account, also using JIT invoices.

Support JIT invoicing on donations to rewards pool

---

components/notifications.js

`1 sat was deposited`, `2 sats were deposited`, etc.
I found this while testing LUD-12 with a 1-sat invoice :P

fix singular/plural for invoice deposit notification

---

api/typeDefs/user.js
components/image.js
components/text.js
fragments/users.js
pages/settings.js
prisma/migrations/20231003134505_rename_to_imgproxy_only/migration.sql
prisma/schema.prisma

- Removed comments about `srcSet` which no longer made sense
- Update comments in `<ImageOriginal>`
- Simplify condition when image is loaded in `<ImageOriginal>`
- Rename column from `clickToLoadImg` to `imgproxyOnly` since we no longer use clicking to bypass setting. We simply show the link for the user to click. (I also never liked the name of the setting)
- Add info about setting in /settings
- Fix misleading URL on imgproxy errors: I read [your comment here](https://github.com/stackernews/stacker.news/commit/62b53e1b3e5e57bcdce553bca7b4fb52075931a3#r129010564) and will make sure it supports markdown links, too

Image refactor refactor

---

api/resolvers/user.js
api/typeDefs/user.js
components/form.js
fragments/users.js
lib/cursor.js
package-lock.json
package.json

Closes #529 
Support mention auto-complete in markdown input fields. Closely follows the suggestions in #529, which are largely inspired by GitHub's experience.
* When `@` is typed, show a list of top stackers for the day to pick from (5)
* Use the text immediately following `@` to search for similarly named users to pick from
* Use up/down arrow to navigate between search options
* Use Tab/Enter to pick the current selection
* Use escape to close the dropdown
* Selected user is inserted into the textarea input, and your cursor position is set to the end of the mention
* Suggestions do not show up if there's non-whitespace characters immediately preceding `@` e.g. `x@`
* Suggestions are shown as you're deleting an existing mention, all the way back to `@`. Suggestions are based on the …

Mention auto-complete

---

components/reply.js
docs/useful-dev-commands.md

Approach borrowed from https://stackoverflow.com/a/72537632
I don't know how the licensing works for using content from stack overflow, but here's the applicable license: https://creativecommons.org/licenses/by-sa/4.0/ ¯\\\_(ツ)_/¯ 
Basically this makes a copy of the selection when the `touchend` event occurs, so we can use it for processing later (when the imperative `quoteReply` method is invoked). It also stores a reference to the containing node, so we can do the DOM tree lookup to confirm the selection is from the parent item.
This code listens to that event for each instance of the reply component, removing the event listener on unmount
I also threw in a minor tweak to the dev commands file that I noticed should be made.

Fix quote selection reply in iOS Safari

---

components/user-header.js

When you click on the button that has the lightning address on a user's profile, in addition to opening a modal with the LNURLP QR Code, it now also copies the lightning address to your clipboard. I've found that I want to pay via LN Addr this way all the time but it's not convenient.
https://github.com/stackernews/stacker.news/assets/128755788/cb4a126f-ddae-4cc8-881e-18937e839041

Copy lightning address on click

---

components/adv-post-form.js

Keeps crossposting checkbox from rendering on forms other than discussion since currently only discussion posts have crossposting support.

crosspost to nostr checkbox only appears on discussion forms

---

components/use-crossposter.js

Removes unnecessary 'a' tag from nostr crosspost event which is causing the note to look like it is replying to itself.
[Thread](https://nostr.band/note1af6utxp8mudg8ducspyxzwh34qqu0t9yavwdmzvpkjftjqgqeqmsspws0g)

Removing a tag, retested crossposts and edits

---

components/form.js
pages/wallet.js

adds auto-complete support for other stacker.news users when withdrawing to a lightning address
implemented via adding an optional `transformUser` prop to the `UserSuggest` and `InputUserSuggest` components, which allows you to transform fetched user results before displaying in the suggestion dropdown
this is used to transform a user nym to nym@stacker.news, the corresponding lightning address
by default, `transformUser` is an identity fn aka no transformation
this change also clears suggestions when the surrounding input field is blurred, which is a better UX IMO
https://github.com/stackernews/stacker.news/assets/128755788/656970be-d7df-4d59-99c1-58382c302f50

Add auto-complete support when withdrawing to ln addr

---

worker/earn.js

Fixes https://github.com/stackernews/stacker.news/pull/530#discussion_r1346794363
Changes
- instead of sending one push notification per type (which then replaces all previous push notifications with tag `EARN`), the data is aggregated and then a single push notification for all types is sent
- [replaced `async/await` usage with `forEach` to `for ... of`](https://gist.github.com/joeytwiddle/37d2085425c049629b80956d3c618971)
Tested this manually with some mock data:
```diff
diff --git a/worker/earn.js b/worker/earn.js
index b0f00fd..73c926c 100644
--- a/worker/earn.js
+++ b/worker/earn.js
@@ -13,6 +13,62 @@ export function earn ({ models }) {
return async function ({ name }) {
console.log('running', name)
+    const now = new Date(new Date().getTime())
+    const sum = 1e8
+    let total = …
```

Fix earn push notifications

---

api/resolvers/user.js

Don't include your own comments when determining if there are new thread subscription replies for user hasNewNotes. 
Basically, if you subscribed to a thread and then made a comment on it, your notification bell would suggest you have new notifications to read, but when you go to the notifications page, there weren't any. Fun!

hasNewNotes for your own comments in subscribed threads

---

api/resolvers/item.js
lib/time.js
lib/timedate-scraper.js

Attempt to get publication year when auto-titling links

---

api/resolvers/wallet.js
api/typeDefs/wallet.js
components/bolt11-info.js
components/form.js
components/invoice.js
fragments/wallet.js
pages/withdrawals/[id].js

Closes #503 
This PR introduces a new `Bolt11Info` component to show info extracted from a BOLT11 after decoding. This component is used for Invoices and Withdrawals. It shows:
1. payment hash
2. payment description (if exists)
3. preimage (for invoices only, not withdrawals)
The preimage is fetched from LND via lookup by hash.
Fields are displayed in `CopyInput`, so they're readonly and easily copyable, if that's useful. 
This PR also updates the `CopyInput` component to use our toast hook for success/failure instead of showing the Thumb icon, just to standardize the UX. We don't have to keep this, but I thought the consistency would be good.
Are there other bits of info we should include? I am not really sure what's worth exposing.

SN wallet transaction details

---

api/resolvers/item.js
lib/item.js
worker/ephemeralItems.js
worker/index.js

Closes #472 
Introduce support for ephemeral items, i.e. items that delete themselves after a specified amount of time.
Stackers can enable this by including text in their items that follows this pattern: 
`@delete in <number> <unit>`
e.g. `@delete in 1 minute`, `@delete in 5 days`, etc.
* `<number>` must be a positive integer
* `<unit>` must be one of: `second`, `minute`, `hour`, `day`, `week`, `month`, `year`, or the plurals of each
If there are multiple "delete commands" found in the text of an item, the last command found in the text is honored.
If an item is edited, the delete commands are re-evaluated. In other words, if there was a delete command originally and it was removed in the edit, the deletion will not occur. Likewise, if there was not a delete command originally but one is …

Ephemeral items

---

pages/satistics.js

Closes #583 
This PR updates the wallet history page's `Fact` component to include when each wallet fact occurred.
It makes use of the common `timeSince` function that we use in item-related components to show a relative time that a wallet history event occurred.
Users can also hover over the relative time in each table row to see the full ISO timestamp (via `title` attribute).
Sample screenshot:

Wallet history timestamps

---

components/serviceworker.js
sw/eventListener.js

Potential fix for #411 
> However, I have an idea for a possible workaround (without really fixing the underlying issue since we don't know what is causing this):
> 
> We could delete the push subscription in IndexedDB if the user manually unchecks the push subscription.
>
> In that case, we know that if the service worker has no push subscription but there is a push subscription in IndexedDB during `SYNC_SUBSCRIPTION`, this is probably the bug and we can register a new push subscription in the background and send that one to the server. Currently, we aren't able to distinguish between the bug and manually unsubscribing since in both cases, there would still be a push subscription in IndexedDB.
> 
> So this means that during `unsubscribeFromPushNotifications`, we would add code that also …

Resubscribe if service worker lost push subscription

---

next.config.js

Closes #601 , fix the typo in `next.config.js` to apply CORS and Cache-Control headers to the `.ttf` font file.

Fix next.config.js to apply CORS and cache response headers to ttf font file

---

api/webPush/index.js
components/header.js
lib/badge.js
pages/notifications.js
sw/eventListener.js

Closes #594 
This PR adds support for notification badges on the app's icon on the home screen.
I originally was going to mimic the behavior of the notification bell in the UI itself (no count, just an empty badge). However, as I worked on these changes, I changed approaches.
Since badges correspond to push notifications, I thought it made sense to show the badge based on receiving push notifications, instead of just doing some kind of polling on the notes API. This also gives the implicit benefit of only showing badges to users who have enabled push notifications, which is ideal.
The changes work as follows:
* Track the number of push notifications received. Increment the count by 1 for every notification received _that we show_. e.g. notifications that get merged with current …

Notification badges

---

components/fee-button.js
components/form.js

https://github.com/stackernews/stacker.news/assets/27162016/28d5353a-128c-4940-9d61-9993224ec83c
Using the new `FeeButtonContext` helped to avoid some copy paste code in _components/reply.js_ and _components/*-form.js_ since I initially wanted to just pass state to both child components (`<MarkdownInput>` and `<FeeButton>`) from the parent (`<Reply>`, `<DiscussionForm>`, ...) :tada:
Closes #608

Disable reply button while uploading

---

components/block-height.js
components/error-boundary.js
components/logger.js
components/me.js
components/price.js
components/serviceworker.js
components/toast.js
pages/_app.js

Closes #609 
This PR makes a few changes related to error boundaries:
1. Updates the `ErrorBoundary` component itself to display a button which will copy relevant error details to the clipboard, so users can share it in a bug report
2. Updates the `ErrorBoundary` component to log errors caught to our logging API service (if the current use has opted in to sharing diagnostic info)
3. Updates the `ErrorBoundary` component to not render a page footer, since the footer has dynamic content which can itself fail at render time
4. Update the application root component tree to wrap the main page component with an error boundary, within all of our context providers. This is so that the most likely source of errors (the page content itself) can be instrumented via logger and toaster for copying the …

Fix client-side error boundary

---

components/price.js

https://stacker.news/items/313119
Currently, the price of bitcoin briefly flashes before the user's selected ticker appears in the header. The fix could involve waiting until after the initial render to display the user's selection, and defaulting to the fiat price of bitcoin.

Dont display price component until after initial render

---

api/resolvers/item.js
api/typeDefs/item.js
components/bounty-form.js
components/comment-edit.js
components/discussion-form.js
components/job-form.js
components/link-form.js
components/poll-form.js
components/reply.js
components/toast.js
components/toast.module.css
fragments/comments.js
fragments/items.js
lib/form.js
lib/item.js
styles/globals.scss

Closes #614 
This PR toasts when an item is created or updated and successfully schedules a deletion job via the `@delete` bot.
It supports all post types and comments, both new and edited.
The toast displays the time at which the item will be deleted, localized to the user's current browser.
If the user mentioned the delete bot but the deletion wasn't scheduled, these changes also toast a warning toast indicating that they may have tried to schedule a deletion but it didn't work, and gives an example of the correct usage.
I also optimized the resolver to only query the DB to find scheduled deletion jobs for your own items, since it's only really necessary for yourself.

Toast on delete bot directive usage

---

lib/badge.js

I found that the permissions check was failing on iOS Safari PWA, which seems like why the badges weren't working for me.
Check both `navigator.permissions.query` and `Notification.permission` for permissions.
It seems these values are not kept in sync on iOS Safari, which may be the source of badges not working on iOS PWA. [Source](https://developer.apple.com/forums/thread/731412)
Side note: holiday weekends mean I have time for side projects :)

Fix notification badges

---

api/resolvers/serial.js

One possible (temporary?) solution for #691 would be to not respond with a error message which tells that creating this invoice would exceed a limit.
By just responding with a different error message, the attacker cannot distinguish between "too many invoices" or "invoice would exceed limit". This isn't ideal but still a lot better imo.
~~I haven't tested this or checked if this would break something but if our code is good, we're not relying on error messages so this change should be fine.~~
edit: Okay, I will test this, don't want to rely on @huumn superhuman skills to know exactly the impact of every line of code changed just by looking at it, lol
TODO:
---
Okay, pretty sure this doesn't break anything. I searched for all kind of substrings of the previous error message, and tested …

Mix error messages to hide user balance

---

components/image.js
package-lock.json
package.json

Fix #678 
Keeping this in draft until I confirmed this does indeed not strip orientation EXIF data - which I am going to do now.
I got the tag value 0x0112 from [here](https://www.media.mit.edu/pia/Research/deepview/exif.html).
---
Okay, 21a9c3e does not work because we are actually deleting all EXIF data _at once_. So the loop is not _iterating_ over EXIF "tags". It's searching for the start of the EXIF data and then deleting it all at once. At least that is my current understanding which I am writing down here to not forget that this is my current "baseline of progress".
I think I need to dive deeper into the [EXIF spec](https://www.media.mit.edu/pia/Research/deepview/exif.html) to be able to do what [some tools](https://github.com/nathanpeck/exiftool) [can do on the …

Do not remove orientation EXIF data

---

lib/push-notifications.js

Not tested yet. Also, I only updated the query in `notifyItemParents`. Need to make sure that only this query needs an update (but I think so).
Fix #662
---
Tested now and thus ready for review:
https://github.com/stackernews/stacker.news/assets/27162016/10c0183f-dbc1-4c0d-921d-4fb80a63aa6d

Consider mutes before sending push notifications

---

components/serviceworker.js

Request persistent storage

---

worker/earn.js

Fix #661 
Essentially, this shows the best rank a stacker achieved per earn type and sums the sats per earn type instead of showing the last info per earn type.
Tested this by putting 141k into donations:
```sql
INSERT INTO "Donation"(created_at, sats, "userId")
VALUES (CURRENT_TIMESTAMP - '1 day'::interval, 141000, 14913);
```
and then assigning 16 random items to two accounts and pretending they were created yesterday:
```sql
UPDATE "Item"
SET created_at = date_trunc('second', CURRENT_TIMESTAMP - '1 day'::interval), "userId" = 14913
WHERE id IN (SELECT id FROM "Item" ORDER BY RANDOM() LIMIT 16);
UPDATE "Item"
SET created_at = date_trunc('second', CURRENT_TIMESTAMP - '1 day'::interval), "userId" = 14912
WHERE id IN (SELECT id FROM "Item" ORDER BY RANDOM() LIMIT 16);
```
This resulted in …

Fix wrong rewards in push notification

---

components/header.js
components/snow.js
components/upvote.js
pages/_app.js
pages/rewards/index.js
styles/globals.scss
styles/snow.scss

This PR adds "christmas zaps": the lightning strike is replaced with snow.
The snowflakes are animated using CSS animations. The javascript codes only creates `<div>` elements with the appropriate CSS class (`snow`) set.
I used this as reference: https://codepen.io/alphardex/pen/dyPorwJ
https://github.com/stackernews/stacker.news/assets/27162016/970fffb9-5f57-47ab-9c7e-008718dc0922
Checked for browser support of [CSS keyframes](https://developer.mozilla.org/en-US/docs/Web/CSS/@keyframes#browser_compatibility):
Update: I just realized this isn't visible in light mode, lol. I'll check if a very thin black border around the snow flakes makes sense in light mode.

Christmas zaps

---

sw/eventListener.js

Related to #411 
|       | Chrome (Blink) | Firefox (Gecko) | Safari (WebKit) |
| ----------- | ----------- |----------- |----------- |
| Desktop      | :white_check_mark:  [video for Brave on desktop](https://files.ekzyis.com/public/sn/web_push_test.mp4)  |  :white_check_mark: Firefox on desktop: tested zaps, replies and mentions| 
| Mobile   |   :white_check_mark: Brave on Android: tested zaps, replies and mentions      | _did not test but pretty sure this will work, too._ |
For faster testing on desktop (not E2E), we can use the serviceworker tools provided by some browsers:
Payload for replies:
```
{"title": "@anon replied to you", "options": { "tag": "REPLY", "icon": "/icons/icon_x96.png" }}
```
Payload for zaps (_does not use new merge logic_):
```
{"title": "your post stacked 21 …
```

Fix silent push due to missing tag support in Safari on iOS

---

components/link-form.js

With this PR, I am suggesting to remove the existing guard against all caps titles for the following reasons:
- it's ineffective since it only makes the second letter lower case
- there are ways to not make it trigger and thus still be able to post links with all caps
- it's unexpected and thus confusing
- there are legitimate use cases for using all caps in the first few letters. example: acronyms
- it only applied to link posts (inconsistent UX)
related to https://github.com/stackernews/stacker.news/issues/584, #590

Remove ineffective guard against all caps

---

components/serviceworker.js
sw/eventListener.js

This adds more logging so we can trace better where the service worker on iOS shows unexpected behavior.
My educated guess is that `Notification.close()` does not work but [according to MDN](https://developer.mozilla.org/en-US/docs/Web/API/Notification/close#browser_compatibility), it should work.
But this wouldn't be the first but the second case where [MDN shows invalid data what a browser supports](https://github.com/mdn/browser-compat-data/issues/20305).
Related to #411

Add verbose logging in onPush listener

---

components/logger.js
components/serviceworker.js
sw/eventListener.js

Related to #411 
I didn't notice a difference testing locally but I am pretty sure this will revert back to the Android UX that we had before #719 since the only problem was that it was noticeable that notifications are closed instead of only replaced using `tag`.

Only close notifications manually on iOS

---

pages/wallet.js

Code works with `autocomplete` but it prints a warning in the console:
> Warning: Invalid DOM property `autocomplete`. Did you mean `autoComplete`?
Code also works with `autoComplete` as used in other parts in the code base.

Fix invalid DOM property

---

sw/eventListener.js

I think I only added `console.log` and `console.error` for debugging during development.
Since we have problems with push notifications on iOS where we will not see the browser console anyway (or only using  USB debugging), we can remove these lines.
Also, the payload options weren't useful in the logs. They only add noise.
Related to #411

Remove logging to browser

---

api/resolvers/serial.js

Fix TypeError on item creation if JIT invoicing is used

---

api/resolvers/item.js
api/resolvers/notifications.js
api/typeDefs/notifications.js
api/typeDefs/user.js
api/webPush/index.js
components/notifications.js
fragments/notifications.js
fragments/users.js
lib/push-notifications.js
pages/settings.js
prisma/migrations/20240110195551_territory_posts_notifications/migration.sql
prisma/schema.prisma
sw/eventListener.js

Close #681. This is based on #744 so #744 needs merging first.
TODO:
Territory post notifications look like this in /notifications:
Push notifications keep territories separate:

Territory post notifications

---

sw/eventListener.js

I could swear I fixed this exact same thing before. Couldn't find a similar commit during my shallow git history search though. Maybe I force pushed it over or bad rebase or something.
This is related to a deposit push notification bug that can be seen in our logs.
For some reason, I receive a "4 sats were deposited in your account" when someone sends me 1 sat on SN.
I also received "2400 sats were deposited in your account" when someone send me 400 sats a few days ago.
Not sure what is going on, wasn't able to reproduce locally yet and the logs didn't fully explain what is going on.

Fix logged title

---

components/form.js
components/invoice.js
components/item-act.js
components/modal.js

Commit description:
> This commit refactors `useInvoicable`. The hard-to-follow recursion was replaced by awaiting promises which resolve or reject when one step of our JIT invoice flow is done.
>
> Therefore, `onSubmit` is now fully agnostic of JIT invoices. The handler only returns when payment + action was successful or canceled - just like when a custodial zap was successful.
This was done while working on #749 since we will heavily rely on JIT invoices there and thus this was a good time to tackle this TODO:
> // TODO: refactor this so it can be easily understood
// there's lots of state cascading paired with logic
// independent of the state, and it's hard to follow
I think this is much better now. There is no recursion anymore.
Keeping in draft since I want to sleep over this and …

refactor: replace recursion with promise sequence in `useInvoiceable`

---

pages/wallet.js

adds support for scanning bip21 qrs on withdrawal.
I didn't really make an attempt to add any substantial bip21 support as we only use it for finding the lightning param.
Closes #734

Unified QR scanning

---

worker/wallet.js

On reconnects, we used a stale value for `confirmedIndex`. This means that we would confirm all invoices again since the worker was started.
Found this while debugging #763 but this fixes not #763.

Fix stale confirmedIndex used on reconnect

---

prisma/migrations/20240124000131_fix_user_stats_post/migration.sql

Bug was here:
```diff
- (sum(quantity) FILTER (WHERE type = 'POSTS'))::BIGINT as posts,
+ (sum(quantity) FILTER (WHERE type = 'POST'))::BIGINT as posts, 
```
Posts are nonzero now locally:

Fix typo in FILTER for posts in user stats

---

components/text.js

This formats links like https://stacker.news/items/395051 to [#395051](https://stacker.news/items/395051)

Format internal links as #<id>

---

api/s3/index.js
worker/deleteUnusedImages.js

The job failed if we tried to delete more than 1000 keys at once.
This was mentioned [here](https://docs.aws.amazon.com/cli/latest/reference/s3api/delete-objects.html):
> The request can contain a list of up to 1000 keys that you want to delete.

Fix image deletion batch size

---

api/resolvers/item.js
api/typeDefs/item.js
components/comment.js
components/comment.module.css
components/comments.js
components/item-info.js
components/item.module.css
components/items.js
components/territory-header.js
fragments/comments.js
prisma/migrations/20240130165240_existing_pins_null_sub/migration.sql

Closes #61 
TODO:
Current state (b88080c4):
https://github.com/stackernews/stacker.news/assets/27162016/18f21a8f-e531-4f55-b874-63bd9c481000

Allow territory founders to pin items

---

api/resolvers/wallet.js

For https://github.com/lnurl/luds/pull/234

Remove description hash check for lnurl

---

components/toast.js
components/toast.module.css
components/use-crossposter.js

I added tags to toasts in #749 for UX reasons. They work similar to how we merge push notifications in the service worker. So 2x `subscribed` becomes 1x `(2) subscribed`. This behavior is enabled by default since the body of a toast will be used as the tag by default and since I think this always makes sense to declutter the UI.
I figured that having this as a dedicated PR is easier to review. I will rebase #749 on this PR.
This also includes being able to attach an `onCancel` function to a toast. If a toast contains an `onCancel` function, it will not be closed on page navigation. This was also added in #749 to cancel async zaps (NWC) and can also be used to cancel custodial zaps in the near future, too.
Since toasts can have `onCancel` and the same tag (for example by simply having the …

Add tags and onCancel to toasts

---

api/resolvers/item.js
contributors.txt

Fixes https://github.com/stackernews/stacker.news/issues/642
This updates the `item#dupes` resolver to correctly extract the yewtube video ID and find similar links based on that ID. I only found one hostname for yewtube (no mobile site) and this should match across normal yewtube links (/watch?v=ID) and embed links (/embed/ID).

Fix yewtube links showing up as dupes of each other

---

api/resolvers/item.js
lib/url.js

Fixes https://github.com/stackernews/stacker.news/issues/768
Looks like there was a regression at some point that made all hacker news links and all bitcointalk links appear as dupes. 
Originally, we expected that these links would be caught by the `whitelist.includes(uri)` if-condition, but now `uri` is a regex string (like `(%.)?bitcointalk.org(:[0-9]+)?/index.php`) so we never matched correctly against the whitelist values.
This returns the original behavior of checking the whitelist against the URL's hostname + pathname. It also renames a variable and reassigns the previously mutated variables to new variables for clarity.

Fix hacker news and bitcointalk dupes

---

api/resolvers/item.js
components/item-info.js
components/item.js
components/items.js

This allows pins to be zapped and shown when they aren't pinned in the ranking for the page, eg in top, home, recent, or when visited directly.
This solves some of the issue presented in #773 and some the issues to be solved in #772 without introducing anything too new. It doesn't solve every corner of the issue but I think it might solve a goldilocks amount.
Merging immediately.

allow pins to be zapped but not from pin position

---

components/territory-form.js

On the territory form, clicking on the labels of the "post types" or "billing" options don't toggle the correct input:
https://github.com/stackernews/stacker.news/assets/158518982/991f675f-5dd8-4b5b-bbeb-02c521baa81d
All the labels within each group were being assigned the same html "id" since we were falling back to the "name" prop. We need to keep the "name" prop the same because that's how the form associates the value with the correct form field. Fix is to assign explicit "id" prop to each checkbox so that the label toggles the correct input.
https://github.com/stackernews/stacker.news/assets/158518982/9fa631b1-9c0c-4264-b865-a1f9286ae143

Fix territory form label clicks not toggling correct input

---

.gitignore
components/banners.js
components/form.js
components/invoice.js
components/item-act.js
components/lightning.js
components/qr.js
components/upvote.js
components/wallet-card.js
components/webln/index.js
components/webln/lnbits.js
components/webln/nwc.js
copilot/capture/manifest.yml
docs/attach-lnbits.md
lib/validate.js
package-lock.json
package.json
pages/_app.js
pages/settings/wallets/index.js
pages/settings/wallets/lnbits.js
pages/settings/wallets/nwc.js
styles/wallet.module.css

Supersedes #715 Closes #533 Closes #490 Closes #75
Based on #753, #752, #777, #778
TODO:

Expose WebLN interface via React Context

---

prisma/migrations/20240209001227_update_image_fees/migration.sql

Every stacker was below 50 MB per day (except one stacker at one day).[^1]
Since storage is cheap, we can allow 50 MB per day for free; especially since UX around image fees suck.
[^1]: Run this query: `SELECT "userId", date_trunc('day', created_at), SUM(size) / 1024 / 1024 AS size FROM "Upload" GROUP BY "userId", date_trunc('day', created_at) ORDER BY SUM(size) DESC LIMIT 21;`

Update image fees to 50 MB free per day

---

components/webln/index.js
components/webln/lnbits.js
components/webln/nwc.js
pages/settings/wallets/lnbits.js
pages/settings/wallets/nwc.js

fix #802
* fixed warning about component update while rendering another component
* individual providers no longer need to know if they are the default or not
* default setting is now handled by `WebLNContext` -- the same context that returns the provider. this makes a lot more sense and is a lot easier to read (imo)
* default payment checkbox is now also disabled if there is only one enabled provider or if it is the default provider
https://github.com/stackernews/stacker.news/assets/27162016/b1f6411a-0dfe-4db3-936d-dcc4763f20e0
_and I really hate `useEffect` and loading stuff from local storage now, lol_

Refactor default payment method setting

---

lib/validate.js

Enforcing wss:// for relay URLs we need a bit more work since we need to parse the URL before we can give it to Yup object. 
Working on it but this can already be merged. Wanted to validate secrets anyway (make sure they are 32 characters in hex).

Enforce HTTPS for LNbits

---

components/text.js

Links like https://stacker.news/items/123456/related were parsed as [#123456](https://stacker.news/items/123456/related). We want to show [#123456/related](https://stacker.news/items/123456/related).
This PR fixes that.
Related to #350, #765

Show item page in internal links

---

next.config.js

Prod builds assumed that we're running in an AWS environment and use a CDN. This commit changes that.
Now, if the AWS way to fetch the commit failed _and_ the normal git command fails and only if, we assume we're running the prod build locally and don't configure the CDN.

Fix local prod builds assuming CDN

---

middleware.js
pages/_document.js

close #770 
Some notes regarding the approach of using a middleware:
We could use meta tags in `<Head>` in app.js but [then we can't use `report-to`](https://cheatsheetseries.owasp.org/cheatsheets/Content_Security_Policy_Cheat_Sheet.html#3-content-security-policy-meta-tag).
We could add static CSP headers in next.config.js but then we can't enforce a strict CSP with dynamic nonces. We could use hashes but hashes are fragile.
So afaict, middleware is the only viable solution. Even though middlewares feel like third-class citizens in NextJS :/
TODO:
We could also uses hashes but this can break easily:
> Using hashes can be a risk approach approach. If you change anything inside the script tag (even whitespace) by, e.g., formatting your code, the hash will be different, and the script won't …

Add Content Security Policy headers

---

components/webln/lnbits.js
components/webln/nwc.js

Payment methods were not marked as initialized if the local storage item did not exist on page load.
This lead to missing updates to the list of enabled providers since only initialized providers are considered.
And with no update to the list of enabled providers, a new payment method is in that case not automatically marked as the default if it's the only one.

Fix missing setInitialized

---

api/resolvers/item.js

I believe this doesn't break any assumption in #788. This should really only affect the saloon since only comments in the saloon have no sub.
Hence, even if a user has `nsfwSetting` disabled[^1], they will still see saloon comments in anyone's profile since they are never excluded.
[^1]: this double negation gets hard to keep track off

Fix saloon comments hidden in profile due to nsfw filter

---

prisma/migrations/20240215144824_fix_sub_spent_calculation/migration.sql

Removes the filter for `ItemAct.act = 'TIP'` so that we can sum all non-tip ItemActs for the sub.

Fix territory spent calculation

---

api/resolvers/sub.js
api/typeDefs/sub.js
components/form.js
components/territory-form.js
components/territory-payment-due.js
fragments/subs.js
lib/constants.js
lib/territory.js
lib/time.js
prisma/migrations/20240216003921_territory_billing_trigger/migration.sql
prisma/schema.prisma

closes #786 
This does what it says. It prorates, ie credits stackers, for the already paid billing period. e.g. If they're 15 days into a monthly billing cycle, upgrading to a year costs 900k sats.
This also makes the territory billing jobs a little more robust by maintaining how much time is already paid for in the `Sub` table and generating billing jobs off that column in a trigger (application doesn't need to concern itself with inserting/updating those jobs).
TODOs

Make territory billing period changeable

---

components/form.js
components/invoice.js

If you had an wallet attached, wanted to pay an invoice with it ("payment pending") and then canceled it, the `onSubmit` handler didn't recognize this as the user aborting the action and toasted "submit error: invoice was canceled". This fixes this.
PS: We should probably put all (frontend) error messages into lib/constants.js to prevent such bugs. But wanted to keep this PR simple. And maybe there is a better way to match errors instead of matching by error message?

Fix onSubmit not ignoring payment cancels from WebLN payments

---

components/invoice.js
components/webln/index.js
worker/nostr.js
worker/wallet.js

For consistency reasons. JIT is a better name in the frontend since it describes the use case.

Rename HODL to JIT in frontend comments

---

components/webln/nwc.js

It worked with Mutiny because Mutiny only supports `pay_invoice` so the resulting array only contained a single element with value `pay_invoice`.
With wallets that supported multiple methods, the single element no longer matched `pay_invoice`.
https://github.com/stackernews/stacker.news/assets/27162016/1ad2e5a2-e48c-419d-a099-a643ccf524d5
I think that's what every stacker encountered with red indicators but no error message since there is indeed no toast if `pay_invoice` support was not detected.
So I believe this fixes #821. I think the errors in the console are unrelated to NWC and that they are just ["CSP WTF reports"](https://github.com/nico3333fr/CSP-useful/tree/master/csp-wtf).

Fix NWC support detection

---

.github/workflows/test.yml
components/text.js
lib/url.js
lib/url.spec.js
package-lock.json
package.json

Since we mentioned tests in #804 and I noticed internal linking is a good candidate to start adopting tests, I added the simplest way to include tests for it that I could imagine.
This only uses the node internal [`assert`](https://nodejs.org/api/assert.html) package. No test framework required.
I especially like how the tests document what behavior we want to see and prevent regressions.
Some drawbacks:
- we can't test code that includes JSX
- Using `node **/*.spec.js` works with multiple test files but on first error, the whole test suite is aborted.
Errors would look like this:
```
$ npm test
> stackernews@0.1.0 test
> node **/*.spec.js
node:internal/process/esm_loader:34
internalBinding('errors').triggerUncaughtException(
^
AssertionError [ERR_ASSERTION]: …
```

Add tests for internal linking

---

components/webln/nwc.js

Fixes: https://github.com/stackernews/stacker.news/pull/845#issuecomment-1951410455
The NIP defines separating by commas but seem alby guys did commas, this should handle both cases (according to chatgpt)

Handle space separated NWC info event

---

components/toast.js

I believe this makes the intention of this code more clear.
Stills works like before and it's easier to build on top.

Refactor removeToast

---

components/toast.js
components/webln/index.js

"Toast flows" are a group of toasts that should be shown after each other.
Before, such flows were implemented by manually removing previous toasts in the same flow.
Now `flowId` can be passed and `ToastProvider` will make sure that there always only exists one toast with the same flowId.
This is different to toast tags since tags don't replace toasts with the same tag, they only are shown "above" them.
Added a wrapper for such flows to reuse the logic for custodial zap cancellation.

Toast flows

---

components/upvote.js

Just a nice little touch to zapping. This PR fills the bolts with the color they would get when zapped.
https://github.com/stackernews/stacker.news/assets/27162016/2930e378-3ec1-4483-b9a5-f2043589ae80

Fill bolts on hover with next zap color

---

api/resolvers/item.js
api/typeDefs/item.js
components/form.js
components/poll-form.js
components/poll.js
fragments/items.js
lib/time.js
lib/validate.js
prisma/migrations/20240219144139_add_poll_expires_at/migration.sql
prisma/migrations/20240219195648_update_update_item_for_poll_expired_at_updates/migration.sql
prisma/schema.prisma

Closes https://github.com/stackernews/stacker.news/issues/671
- Adds `pollExpiresAt` column to `Item` table
- Backfills `pollExpiresAt` where `pollCost` is not null
- I'm assuming this is a proxy for items that are polls. I could also join with the poll options table.
- Adds datetime picker to the poll form in the "options" accordion. defaults to 25 hours in the future so user doesn't hit the validation error as long as they create the poll within an hour. Expiration is also clearable/nullable
- Updates the `update_item` postgres function to correctly set `pollExpiresAt` to NULL if the user edits their poll and removes the expiration. It surprised me that I had to do this...I'm not sure if there's a better way to handle in application code. I tried setting to `undefined` and `''` but they …

Make poll expiration configurable

---

api/typeDefs/user.js
components/dont-link-this.js
components/invoice.js
components/item-act.js
components/toast.js
components/toast.module.css
components/webln/index.js
fragments/users.js
pages/settings/index.js
prisma/migrations/20240219225338_zap_undos/migration.sql
prisma/schema.prisma

Based on #856 
This prepends a toast flow to the existing payment flow to allow zap cancellation: "zap undo's".
Zaps are not really undone but only get triggered after a few seconds. What undoing actually means is to abort the pending zap.
If a zap failed because of insufficient funds and a wallet for sending is attached, the flow continues with the attached wallet.
Current state (ef544d09):
https://github.com/stackernews/stacker.news/assets/27162016/5f2f180d-7020-4699-bc5d-c42cc1484cb9
TODO:

Allow zap undo's for short period of time

---

api/resolvers/sub.js
api/resolvers/user.js
api/typeDefs/sub.js
api/typeDefs/user.js
components/user-header.js
fragments/users.js
pages/[name]/territories.js

Closes https://github.com/stackernews/stacker.news/issues/847
- Shows "territories" tab on profile if user founded any active territories
- User territories page lists active territories founded by the user, ordered by stacked
<details>
<summary>Screenshots</summary>
</details>

Show founded territories on profile

---

components/toast.js

If a toast gets rendered again with the same animation-delay, the negative animation-delay seems to get added which means that the animation skips ahead.
This commit fixes that by ensuring that animation-delay is only set if the toast was not rendered before.
Before:
_notice how the progress bar for `subscribed` gets out of sync when `unsubscribed` gets rendered for the first time and how `unsubscribed`'s progress bar gets out of sync when it gets rendered again due to `subscribed` disappearing. progress bar for toasts that were hidden before are not out of sync._
https://github.com/stackernews/stacker.news/assets/27162016/73d5d41c-b394-4bb1-8b2f-e12d555b7481
Now:
_no progress bar desyncs anymore._
https://github.com/stackernews/stacker.news/assets/27162016/29963650-d167-4f44-b74d-be5b7b31 …

Fix toast progress bar desync

---

components/item-act.js
components/toast.js
pages/settings/index.js

More zap undo fixes

---

components/invoice.js
components/item-act.js
components/toast.js
components/toast.module.css
components/webln/index.js

The progress bar indicates when the invoice will expire.
This works by ~passing in~ returning a timeout ~to~ in the withToastFlow wrapper.
If timeout is set, progressBar option will be true for the toast and delay will be set to the timeout.
If progressBar is set, the progress bar will use the delay for its duration.

Use progress bar for pending payments

---

prisma/migrations/20240224215425_fix_duplicate_image_conflict/migration.sql

The `create_item` function was missing `ON CONFLICT DO NOTHING` for insertions into the `ItemUpload` table as in `update_item`.
This means that if the same image was used multiple times in the same item, creation failed. But it worked during editing.
Diff for `create_item`:
```diff
diff --git a/exclude/create_item b/exclude/create_item
index 075bf372..e5f891b2 100644
--- a/exclude/create_item
+++ b/exclude/create_item
@@ -120,7 +120,7 @@ BEGIN
-- record attachments
IF upload_ids IS NOT NULL THEN
INSERT INTO "ItemUpload" ("itemId", "uploadId")
-            SELECT item.id, * FROM UNNEST(upload_ids);
+            SELECT item.id, * FROM UNNEST(upload_ids) ON CONFLICT DO NOTHING;
END IF;
-- schedule imgproxy job
```
Side note:
Some automated job in the CI for schema or at least function diffs …

Fix conflict on duplicate image in post

---

prisma/migrations/20240224220605_remove_unused_create_item_function/migration.sql

We only use `create_item` at a single location:
https://github.com/stackernews/stacker.news/blob/a067a9fcf113954ca9a73ddc71db4220e9e801d6/api/resolvers/item.js#L1332-L1337
It uses the function signature with integer[] at the end.

Drop unused function signature of create_item

---

components/item-act.js
components/toast.js

Turbo zaps had different toast bodies so they weren't merged together. This gave stackers the option to undo these zaps out of order.
When zaps are undone out of order, the client cache can get in a bad state. Using the item id as a tag fixes that such that zaps for the same item will always get merged together.
This can be seen as a workaround for hacky zap undo code but I think it's also better UX so maybe we should do this anyway.

Fix out of order undos for turbo zaps

---

prisma/migrations/20240228031956_drop_note_territory_posts_column/migration.sql
prisma/schema.prisma

I've seen that I forgot to add the column back into the Prisma schema for backwards compatibility in https://github.com/stackernews/stacker.news/commit/cd4f24310611c936523bf317eab49b911b80483c but it should be safe to drop now.

Drop noteTerritoryPosts column

---

components/info.js

The info icon was not vertically centered (see video), this PR fixes that.
https://github.com/stackernews/stacker.news/assets/27162016/6dc171bf-27db-497f-8d22-c05c88011b7d

Fix alignment of info icon

---

api/resolvers/notifications.js
lib/cursor.js

This improves pagination performance of notifications by using the last page's eldest `sortTime` as a filter for the next page. Previously we were using an offset method of pagination.
Given that `sortTime` is not guaranteed to be unique, there is a small probability we'll miss things between pages. This will only occur if two notifications happen at exactly the same millisecond which is likely to be incredibly rare globally:
```
stackernews=# select count(DISTINCT created_at), count(*) from "Item";
count  | count  
--------+--------
438562 | 438562
```
And is likely to be even more rare for the notifications of a single stacker. And even more rare that such a notification exists at a page boundary. 
So, this is not ideal, but it is likely more than good enough in practice.

Use keyset pagination for notifications

---

components/form.js

If `baseCost` in the territory form was fetched from local storage, its type was string not number which broke GraphQL validation.
Unfortunately, I didn't find a way to additionally check that the input type was set to `number` via Formik's return value of [`useField`](https://formik.org/docs/api/useField). But I think this change shouldn't break anything. If somethings expects a string and it now receives a number, Javascript should do what it's infamous for: coercing values. So this might even fix other related bugs.
However, I additionally added a check such that this manual cast only happens if the current default value is also a number to be safe and meet developer expectations more closely.
https://github.com/stackernews/stacker.news/assets/27162016/a962c5e5-4aeb-478d-b36e-6a76f1459c …

Parse numeric strings as numbers

---

api/resolvers/image.js
api/resolvers/item.js

Mhh, interesting. Apparently, image fees were never properly applied if JIT invoices were used since I added image uploads in #576.
Image fees were still applied from the custodial wallet since the image fees are deducted inside the postgres functions `update_item` and `create_item`. We only calculate the image fees in the mutation manually so we can use it for `serializeInvoiceable` and `enforceFee`.
And this never broke since if `enforceFee` is undefined, we don't check if the fee was paid in full in `checkInvoice`, only that an invoice with any amount was paid. And if it's `NaN` which is the case if you add `undefined` (`imgFees`) to a number, the check inside `checkInvoice` also won't run since `NaN` is a falsy value.

Fix image fees undefined and not enforced if logged in

---

package-lock.json

My suspicion is this fixes #959 (assuming tsx is the only issue).
There's a bug in npm https://github.com/npm/cli/issues/4828 that only adds the platform `npm install` is run on to `package-lock.json` when `node_modules` is present. I can at least confirm this change resulted in all other platform dependencies being added to `package-lock.json`.

reinstall tsx without node_modules present

---

docker-compose.yml

This makes it possible to continue to use `lncli` without `--rpcserver` inside the docker container even if the GRPC port exposed on the host machine is different.
This is the case on my machine since I am running a mainnet LND node on my machine so port 10009 is already used.
I could change the port to 20009 via `LND_GRPC_PORT` and `STACKER_LND_GRPC_PORT` (they can even have the same port) but then `lncli` inside the container needs to be aware of that which means that the sndev script would need to parse .env.development (or some other "magic") to know the GRPC port inside the container.
However, I decided that using standard ports inside the container is better to keep the sndev script simple at the cost of having to think about host vs container ports since they are different now.
One …

Keep standard ports inside container

---

api/resolvers/notifications.js
api/resolvers/user.js
api/resolvers/wallet.js
api/typeDefs/notifications.js
api/typeDefs/user.js
components/notifications.js
fragments/notifications.js
fragments/users.js
lib/webPush.js
pages/settings/index.js
prisma/migrations/20240325114003_withdrawal_notifications/migration.sql
prisma/schema.prisma
sw/eventListener.js
worker/wallet.js

This PR adds notifications for successful withdrawals:
I think having notifications for failed (auto)withdrawals would also be useful but going to do this in a different PR.
_Wanted to add video to show off push notification merging but for some reason suddenly all my channels are inactive and I see this in the logs (maybe related, not sure if that was there before):_
> stacker_lnd   | 2024-03-26 01:38:53.004 [ERR] CMGR: Can't accept connection: unable to accept connection from 172.19.0.10:47790: chacha20poly1305: message authentication failed
_Will check tomorrow what's going on but keeping this PR ready for review since I tested the code before and it worked._

Withdrawal notifications

---

middleware.js

I noticed that in 9820055a, the CSP middleware was commented out. I assume that was accidentally checked into git.
I clicked around with CSP enabled a little bit on my local machine and the site works fine with CSP enabled.
So not sure why it was disabled? Is there something we should add to it conditionally to not interfere with local development?

Fix CSP commented out in middleware

---

api/resolvers/notifications.js

Fixes https://stacker.news/items/493271
In #958, we denormalized replies but don't store replies to self, see `p."userId" <> NEW."userId"` here:
https://github.com/stackernews/stacker.news/blob/15fb7f446b68611306e0dd0c5a0fa460834be991/prisma/migrations/20240323222903_replies/migration.sql#L70-L73
However, we missed that `ThreadSubscription` can still notify users about their own replies if the reply is in a thread to which they are subscribed.
This PR makes sure that we never notify 
Some discussion can be found here: https://github.com/stackernews/stacker.news/commit/a7b0272200c83a5d4c76b48460fc2aca084df3d7#r140575475
Push notifications were not affected since they actually still use old code with a `p."userId" <> $2` filter:
https://github.com/stackernews/stacker.news/blob/15fb7f446b6861 …

Never notify on replies from self

---

.env.sample
.github/pull_request_template.md
components/block-height.js
components/chain-fee.js
components/fee-button.js
components/footer-rewards.js
components/invoice.js
components/lightning-auth.js
components/me.js
components/price.js
components/sub-select.js
components/use-has-new-notes.js
lib/constants.js
pages/invoices/[id].js
pages/rewards/index.js
pages/wallet/index.js
pages/withdrawals/[id].js

Closes #1033
* Add env vars for 4 different common polling intervals, fast (1000), normal (30000), long (60000), extra long (300000):
* `NEXT_PUBLIC_FAST_POLL_INTERVAL=1000`
* `NEXT_PUBLIC_NORMAL_POLL_INTERVAL=30000`
* `NEXT_PUBLIC_LONG_POLL_INTERVAL=60000`
* `NEXT_PUBLIC_EXTRA_LONG_POLL_INTERVAL=300000`
* `NEXT_PUBLIC_` prefix is used since these are consumed in client-side code.
* Use env vars in all `pollInterval` params to `useQuery` in the codebase
* The original intent behind this PR is just to be able to reduce network noise in local dev, for easier debugging.
* Updated the PR template to ask if new env vars are being introduced
N/A
N/A

env vars for polling intervals

---

api/resolvers/user.js
api/typeDefs/user.js
components/mute.js
fragments/users.js
lib/apollo.js
pages/settings/index.js
pages/settings/mutes/index.js

Closes #943 
Add a muted users management tab to the settings page - a tab where you can view all the stackers whom you've muted, and you can manage your mutes for each individually. The approach is as follows:
1. Add a "muted users" tab to the settings page that links to new page at `/settings/mutes`
2. Create a new user graphql query which returns all users that you've muted
3. Displays a list of these users, in pages of 21
4. Each user in the list has an action overflow menu, where you can manage your subscription(s) and mutes, just like on the user profile page
5. When you unmute a stacker in the list, the list reloads to reflect that change, including removing said stacker from the list
New "muted users" tab on settings page nav bar:
The muted users listing:
Pagination available:
No …

Mute Management Settings Page

---

components/text.js
lib/url.js

ensures that internal links do not open in new tabs by default 
Closes #1036
Adds some logic to ensure that links are considered internal links only when they start with `https://stacker.news` in prod or when links start with `/` indicating it is a next internal route.  This prevents the site getting confused on links like `https://example.com/items/134500`.  I suppose this will not work on the sn onion site

Internal links are not target=_blank by default

---

lib/url.spec.js

- adds env variables to run the tests in `/lib/url.spec.js`
- adds a new test to prove non-valid origins fail

Fix the tests for parseInternalLinks

---

api/resolvers/item.js
api/resolvers/rewards.js
api/resolvers/serial.js
api/resolvers/sub.js
api/resolvers/wallet.js
pages/api/lnurlp/[username]/pay.js
pages/invites/[id].js
worker/auction.js
worker/earn.js
worker/territory.js
worker/wallet.js

#1040 contained a bug that broke item creation and updating and was thus reverted.
Turns out that was at least one reason why `results.flat(2)` was needed (see https://github.com/stackernews/stacker.news/pull/1040#discussion_r1555123391).
This PR contains the same changes + ffbbcad0f3e75ef86f2f517cc58cce1d31b72df5 which fixes item creation and updating without flattening results which was also something I wanted to get rid of.
I now searched for `serialize` and tested everything that depends on the return value of it + zaps.
Therefore, following functions were tested:
- `createItem`
- `updateItem`
- `act` via zaps and custom zaps
- `donateToRewards`
- `paySub`
- `createSub`
- `updateSub`
- `createInvoice`
- `cancelInvoice`
- `createWithdrawal`
Also tested invoice and withdrawal …

Merge serializeInvoiceable with serialize without bug

---

lib/validate.js

The missing `required` attribute does not make the certificate for LND autowithdrawals optional. It still verifies if the value is properly encoded. This PR fixes that.
Before:
After:

Fix cert required

---

components/form.js

from @ekzyis's comment
> I just noticed that the UI/UX is reversed for comments. When the comment is uncollapsed, we show the closed eye to collapse it. When it's collapsed, we show the open eye to uncollapse it.
> 
> So I think we should make it consistent here. A classic case of [this](https://dev.to/ben/should-a-button-communicate-the-current-state-the-intended-behavior-or-both-50na).

Flip the PasswordHider icons for consistent UX

---

pages/api/lnurlp/[username]/pay.js
pages/api/lnurlp/[username]/verify/[hash].js

This PR adds support for LNURL-verify.
closes #1102 
https://github.com/stackernews/stacker.news/assets/27162016/52a41f14-c08a-4ca2-9ad6-451d4743dece
LNURL-verify is not part of the LNURL spec, see https://github.com/lnurl/luds/issues/182.

Support LNURL-verify

---

docker-compose.yml

Arrays for `env_file` are only supported in Docker Compose >=v2.24 which is too new (from January 2024). Most distros distribute older packages.
Since `--env-` file as defined in the sndev script acts as an override for env_file anyway, we can safely remove it here.
See https://github.com/stackernews/stacker.news/pull/1082#issuecomment-2081230695 and https://github.com/stackernews/stacker.news/commit/dd6e921e2e00950f19da5bd6d76769c89268d1bb#r141433414

Remove .env.local from env_file

---

components/item.module.css
styles/globals.scss

Closes #1125 
adds an explicit word break to the main and other item components to handle the text of long titles. Firefox handles this break by default but it seems that chrome and safari do not
chrome linebreak (note the `break-all` behavior in the url where the rest of the title has `break-word`) 
firefox linebreak (no change from prod)
This bit of css seems to only be necessary for chrome or safari based browsers as firefox seems to already have some default line-breaks built for slash characters. however, since I cannot explicitly state to make a linebreak on a "/" I opted to add `word-break: break-word;` instead. as a result the word breaks on firefox <-> chrome look slightly different
Yaaasss
**Did you QA this? Could …

Add explicit word break for items

---

lib/apollo.js

closes #995
enables apollo cache to work for 'stacked' 'spent' in /statistics page.

bug | #995 | add TypePolicy to Fact 

---

components/logger.js
components/nav/common.js
components/nav/mobile/offcanvas.js
components/webln/index.js
components/webln/lnbits.js
components/webln/lnc.js
components/webln/nwc.js

Close #927
TODO:
Yes, stackers will still be able to access their current attached wallets without attaching them again. If a wallet wasn't found with the new key, we will fallback to the old key and migrate it to the new key.
Yes, but I couldn't test LNC since I don't know how to connect it. See https://github.com/stackernews/stacker.news/pull/1104#discussion_r1582239915.

Fix unintended sharing of wallets and logs

---

api/resolvers/item.js
components/bounty-form.js
components/fee-button.js
components/form.js
components/invoice.js
components/item-act.js
components/job-form.js
components/modal.js
components/pay-bounty.js
components/payment.js
components/poll.js
components/qr.js
components/reply.js
components/toast.js
components/upvote.js
components/webln/index.js
pages/_app.js
pages/invoices/[id].js

This PR is the first step of refactoring the layers of code for external payments.
Essentially, we have three layers: 
1. Optimistic UX via manual Apollo cache updates
2. Zap undo: delay zapping and show option to "undo" (which is technically a cancel)
3. Payment code (custodial vs attached)
These layers are currently a mess since code for them is all over the place + zap undo, external payments and toast flows for both are implemented by wrapping functions. We don't have _distinct_ layers that don't leak into each other.
This PR focuses on the payment layer. It replaces the function wrapper `useInvoiceable` with `usePayment` which hooks into the new context `PaymentContext`.[^1] This implements what I described in https://github.com/stackernews/stacker.news/pull/1041#issuecomment-20439594 …

Replace useInvoiceable with usePayment

---

pages/settings/wallets/cln.js
pages/settings/wallets/lightning-address.js

The detach button was missing for CLN and LN address. This fixes it by using the same code as for LND.
https://stacker.news/items/530554
yes
I did not test this actually fixes the issue but pretty sure it will from simply reading the code

Fix wallet detach unavailable

---

components/image.js
lib/url.js

Fix #1152
Images from our media domain (m.stacker.news) were not trusted so these images didn't load for stackers which had `imgproxyOnly` enabled until the worker processed the image and srcSet with imgproxy URLs was available.
I renamed `<ImageProxy>` to `<TrustedImage>` since it describes better why we're doing what we're doing.
yes
yes

Fix images from media domain not loaded if imgproxyOnly enabled

---

api/resolvers/chainFee.js
components/price.js

Fixes #1124 
This PR addresses an issue with the transaction fee rate shown in the header as it wasn't updating regularly.
- Uses Mempool for latest transaction fee (uses `hourFee` but can be changed to higher or lower priority if requested)
- Tidies up onClick handler to reduce repetitive code
**Note:** the existing implementation deletes the local storage entry on every complete cycle of clicking the price component. However, with these changes nothing is deleted as it doesn't appear necessary. Please let me know if I've overlooked something.
Tested locally on desktop using a minimal compose profiles setup. Might benefit from some extra eyes on this as it's my first PR.

[1124] - Use Mempool For Fee Rate

---

components/qr.js
components/webln/lnbits.js
components/webln/lnc.js
components/webln/nwc.js

This fixes the hack in the QR component to prevent infinite renders if `provider.sendPayment` is called by wrapping the context value with `useMemo`.
yes
Tested with LNbits and NWC

Fix QR rerender on WebLN payment

---

components/webln/index.js

The default setting to pick which provider to use if multiple are enabled didn't work. It restored the persisted order before it was saved. It was supposed to only restore the persisted order on first render.
The providers also weren't able to tell if they were the default since `WebLNContext` didn't expose the name property. Now it does.
This will create a conflict with #1181 but I'll resolve it. Feel free to merge #1181 or this first.
yes
yes

Fix provider default setting

---

lib/validate.js

I accidentally inverted the env check in a585ba7f, see https://github.com/stackernews/stacker.news/commit/a585ba7f0aa0eb8050142661f23da2253c8a3607#r142166222

Fix inverted lnbitsSchema env check

---

components/modal.js

This fixes concurrent `showModal` calls with stale values which lead to modals getting replaced instead of stacked.
fixes https://github.com/stackernews/stacker.news/pull/1194#issuecomment-2135756183
Yes
Searched for `showModal` calls and thus tested modals for QR codes, custom zaps, zoomable images, avatar upload, delete, anon info, "you will lose your work"-modal. There are more but looks good to me

Use refs for modals

---

api/resolvers/item.js
api/typeDefs/item.js
components/item-info.js
fragments/comments.js
fragments/items.js
prisma/migrations/20240529074650_item_bot_badge/migration.sql
prisma/schema.prisma

This adds a `bot` badge to any item that was created with an API key.
See https://github.com/stackernews/stacker.news/pull/1205#issuecomment-2138546513
Yes, I only added a column with a default and `apiKey` is nullable in the GraphQL typedef.
Yes
Yes
No

Add bot badge to items created with API key

---

pages/settings/index.js

This removes the trash icon to delete API keys. We now reuse the button to generate API keys for deletion.
See https://github.com/stackernews/stacker.news/pull/1205#issuecomment-2138546513
Yes
Yes
Yes
No

Use same button to generate and delete API keys

---

components/accordian-item.js
components/item-full.js
components/reply.js

Fixes #837 
This PR ensures that the Related Posts section is closed once a comment is made.
This issue took me a while to find but eventually found the problem within Accordion component.
- Made use of `activeKey` and `onSelect` props
- Implemented `onSelect` handler to update `activeKey` value
- Set `activeKey` value on load
- Use `null` instead of `undefined` (Accordion doesn't seem to behave when using `undefined`)
https://github.com/stackernews/stacker.news/assets/7639854/cf6cb2a3-29fc-4428-848b-1889ceead087
Please QA this if possible as I may have overlooked something.

Close related section

---

sndev

Adds a `fund_user` command to `./sndev` that allows you to fund a user without having to use a LN invoice, so you can easily fund users without running the payments containers.
N/A
As discussed [here](https://chat.sndev.team/#/room/!dhqketVrbDjhGqdqtp:sndev.team/$0MBiw_ZFjKP697TWGfvV3Rn4Sp9cV4e5eXkuutzJjlI?via=sndev.team)
Yes
Yes
N/A
No

add `fund_user` sndev command

---

components/text.js
lib/url.js

Fixes #1213 
This PR ensures a popover is seen for internal links that include a text part.
These links were tested and are working as expected:
| Link    | Comment |
| -------- | ------- |
|`http://localhost:3000/items/459356`|shows popover and renders internal link|
|`[link](http://localhost:3000/items/458213`|shows popover and renders internal link|
|`[link](https://stacker.news)`|opens in new tab (this is external relative to localhost)|
|`https://stacker.news`|opens in new tab (this is external relative to localhost)|
|`[link](http://localhost:3000/settings)`|renders internal link (no popover)|
|`[link](/settings)`|renders internal link (no popover)|
**Preview**
**Popover visible on second link**

Fix issue with popover on full sn links

---

api/resolvers/item.js
api/resolvers/notifications.js
api/resolvers/user.js
api/typeDefs/notifications.js
api/typeDefs/user.js
components/notifications.js
components/text.js
fragments/notifications.js
fragments/users.js
lib/remark-ref2link.js
lib/webPush.js
pages/settings/index.js
prisma/migrations/20240529105359_item_mentions/migration.sql
prisma/schema.prisma
sw/eventListener.js

This adds notifications if one of your posts or comments were mentioned.
I also added parsing of references as `#<itemId>` to links so internal references are now linked both ways. This means that `#1234` will now be parsed as a link to https://stacker.news/items/1234 (see d449d8bf).
Related to https://github.com/stackernews/stacker.news/issues/667 but doesn't close it since this PR is only about notifications
I initially wanted to include the type of item that was referred in the title. So if someone referred to a post of yours, it would show `one of your posts was mentioned` instead of `one of your comments was mentioned`. However, that made the code more complicated (see d9740250).
I now use `items` to mean both but I think that's not a good name since it might be confusing for …

Item mention notifications

---

api/resolvers/item.js
components/text.js
lib/url.js
lib/url.spec.js

The code for item mentions in the backend didn't parse internal links properly. Links like `https://stacker.news/items/560297?commentId=561109` didn't use the comment id but the item id.
Item mentions should always use the id the frontend would show for the link when parsed. 
Going to test the code for item mentions more since [there might be more wrong](https://stacker.news/items/560297?commentId=561120)
Yes

Fix missing commentId parsing for item mentions

---

components/item-act.js
components/pay-bounty.js
components/poll.js

Related to #1218 
Manual optimistic updates break cache updates for comments (probably updates for all following mutations). This PR comments out the code that breaks them for now.
TODO:
Yes
Yes, tested zaps and custom zap with commenting afterwards, bounty payments, polls

Avoid manual optimistic updates for now

---

lib/url.js

This is a small and simple change to embed YT shorts.
I actually wanted to embed YT clips like [this](https://stacker.news/items/486787) but I haven't found a simple way. The embed URL requires the video id which is not available if given only the clip URL. I found this working embed URL in the document head:
```
<meta property="og:video:url" content="https://www.youtube.com/embed/2LKwnQJXngU?clip=Ugkx1bqCjGlspRX3VC5hWobnDQDIPdbPYu6b&amp;clipt=EM2f-AEYpcf6AQ">
```
Interestingly, YT does not seem to expose this embed URL when clicking on Share > Embed but uses [this](https://www.youtube.com/embed/2LKwnQJXngU?si=BOfZ4bgen7SPEMTN&amp;start=4069) as the iframe src.
Fetching the document in the browser does not work ~due to CORS policy~ 403 errors.
**Are your changes backwards compatible? …

Embed youtube shorts

---

components/item-act.js

There was some [discussion about zap responsiveness on SN](https://stacker.news/items/560966?commentId=562741). This PR changes the lightning strike to appear with the optimistic response. Before, the strike happened only after the mutation was successful. 
Yes
Yes

Remove strike delay

---

components/upvote.js

Fixed two issues with the pulse animation for zap undos. See c2a526284f8cb9eba1092be39f93dd1e3d1dd680 and 173852a35bd58a4b6354be42aa7da73293f837ce.
I think the bug that 173852a3 fixes is what nout experienced [here](https://stacker.news/items/563298) with delayed zaps not showing anything. It didn't show anything if you didn't zap before since the animation used the previous color for the pulse which is the same as no color in that case.
This PR is part three of a series of PRs related to fixing stuff around zap undos (#872, #962) but since this PR is really small, I am still confident that the new code for zap undos is a lot better than what we had before. I just missed these two bugs before for some reason but they made immediately sense.
_The size of this PR might even be a …

More zap undo fixes III

---

pages/settings/index.js

The info for zap undos was still using the old text even though we use a pulse animation instead of toasts now.
Yes
Yes
Yes
No

Update zap undos info

---

components/banners.js
pages/settings/index.js

Use <Alert> for auth banner in /settings

---

api/resolvers/item.js

I noticed that I received no item mention notification for this: https://stacker.news/items/582653
Turns out that ~the cast to a number~ the check `isItemPath` in `parseInternalLinks` failed because the parentheses in the raw markdown were included in the match.
This PR fixes it by only matching characters that make part sense as part of the URL. Only matching `/items/\d+` is not enough since we also need to match any potential `commentId` query parameter.

Fix item mention ref pattern

---

components/text.js

User popovers showed "user not found" if users were mentioned within a markdown link.
I noticed this while writing [this comment](https://stacker.news/items/582556). I initially wrote this:
```
[@Natalia be like](https://stacker.news/items/549152):
```
but then I realized that it shows "user not found" because `name` was set to `@Natalia be like`.
This PR fixes that.

Fix user popover if mention inside link

---

docker-compose.yml
docker/litd/Dockerfile

The `litd` container was always shown as unhealthy because `curl` wasn't installed.

Fix litd healthcheck

---

pages/satistics/index.js

Invoices that were cancelled but did not expire yet showed `unknown failure` in /satistics.

Add missing CANCELLED status

---

api/paidAction/itemCreate.js
api/paidAction/itemUpdate.js
api/paidAction/zap.js
lib/webPush.js

I noticed that we can't fully eliminate duplicates if we delete existing mentions. For example, if I mention someone, then edit my comment to remove the mention and then edit again mentioning them again, they will receive another notification.
I think we didn't delete them before.

Fix push notifications

---

api/paidAction/lib/item.js

Similar to user mentions, we shouldn't receive a push notification if we mention our own items.

Fix item mention of own items

---

api/paidAction/README.md
api/paidAction/index.js
api/paidAction/itemCreate.js
api/paidAction/zap.js
api/resolvers/item.js
api/resolvers/paidAction.js
api/resolvers/rewards.js
api/resolvers/sub.js
api/resolvers/wallet.js
api/typeDefs/item.js
api/typeDefs/paidAction.js
api/typeDefs/rewards.js
api/typeDefs/sub.js
api/typeDefs/wallet.js
components/invoice.js
components/item-act.js
components/payment.js
components/use-paid-mutation.js
docker-compose.yml
fragments/paidAction.js
fragments/wallet.js
pages/rewards/index.js
prisma/migrations/20240703144051_action_args_err/migration.sql
prisma/schema.prisma
worker/paidAction.js
worker/territory.js

This solves this: https://stacker.news/items/594374/r/k00b?commentId=594860
This makes it so paid actions no longer need the client to keep the tab/site open to have pessimistic actions complete.
We do this by creating 3 new columns on `Invoice`:
1. when the mutation is called, we store the args in `actionArgs` on the invoice
- these are used to run `perform` when invoice transitions to `HELD`
2. if `perform` succeeds, it stores the result in `actionResult` on the invoice
3. if `perform` fails, it stores the error in `actionError` on the invoice
To get the result of the pessimistic action, I created another graphql query `paidAction` which returns `actionResult`. We call this once we see the invoice is paid on the client.
To get the error of the pessimistic action, we check for …

improve pessimistic paid actions by letting the server perform actions and settle invoice on `HELD` 

---

api/resolvers/rewards.js
api/ssrApollo.js
middleware.js
pages/api/auth/[...nextauth].js
prisma/migrations/20240706000412_one_day_referrals/migration.sql
prisma/schema.prisma

So far this captures the relevant referral data in `middleware.js`, storing it in cookies (for a future login), and passing it in the request headers (for logged in stackers) for storage in the db.
- referrals can be earned the following ways:
- explicit referrals by sharing links with `/r/<referrer name>` at the end or invite links
- implicit referrals:
- every item link attributes a referral to the OP
- every item link with a `commentId` attributes a referral to the comment's OP
- every profile page link attributes a referral to the stacker on the profile
- every territory link attributes a referral to the territory founder
- for logged out stackers, we store referrals in their cookies to be used on signup:
-  `sn_referrer` is set by either explicit or implicit referrals for 24 hours
- …

new referral scheme

---

api/paidAction/zap.js

A stacker reported to me that even though [this stacker](https://stacker.news/vostrnad) stacked 20k+ sats on [their post](https://stacker.news/items/600187), `stacked` in their profile still showed 0 sats.
I noticed that the new zap code introduced in #1195 is missing the update to the `users.stackedMsats` column:
https://github.com/stackernews/stacker.news/blob/371084016740fc29751e5964e17c687420c6ea57/api/paidAction/zap.js#L86-L88
After I fixed that, I noticed that 99 sats were added to `stackedMsats` instead of the expected 90 sats for a 100 sat zap.
Then I also noticed that the sybil fee is calculated wrong. It divides by 100 which is equal to 1% instead of dividing by 10 for 10% since `x * 0.1 = x * 1/10`.
yes
**Did you …

Fix missing stackedMsats update + wrong sybil fee

---

lib/currency.js

Closes #1226 
Added Naira currency.
Yes, by deleting the line that adds the Naira Currency
Yes
N/A
N/A

feat: added NGN currency

---

api/resolvers/user.js

Small bug I have found while looking into #1268. If you're subscribed to a thread and then reply in it, you would get a notification indicator with no notification.
yes
yes

Fix notification indicator shown for own replies

---

pages/settings/wallets/[wallet].js
wallets/README.md
wallets/index.js
wallets/webln/index.js

> attach/detach/enable UX is a bit inconsistent but it's not super clear how it should be.
-- https://github.com/stackernews/stacker.news/pull/1274#issuecomment-2245949873
Yeah, I agree. For the enable UX, I actually wanted to use validation and show a error message but it didn't show up and for some reason, instead of looking into it and fixing it, I went with a different approach.
But I fixed it now and think validation is better instead of disabling the checkbox if no WebLN provider was found. You can always disable WebLN but you can only enable it if a WebLN provider was found.

Use validation for WebLN wallet

---

lib/wallet.js

This removes the duplicate `Wallet` in the app logs:
```
injected GraphQL resolvers:
upsertWalletWalletLND
upsertWalletWalletCLN
upsertWalletWalletLightningAddress
injected GraphQL type defs:
upsertWalletWalletLND(id: ID, socket: String!, macaroon: String!, cert: String, settings: AutowithdrawSettings!): Boolean
upsertWalletWalletCLN(id: ID, socket: String!, rune: String!, cert: String, settings: AutowithdrawSettings!): Boolean
upsertWalletWalletLightningAddress(id: ID, address: String!, settings: AutowithdrawSettings!): Boolean
```
It's just aesthetics, it has no other effects.

Fix duplicate 'Wallet' in resolver name

---

components/item-act.js
components/upvote.js
pages/settings/index.js

This fixes following things:
- top margin for zap undo input was missing
- zap undo input hint was outdated
- pulse color did not use zap amount, it always used the zap defalut
_Fixing stuff around zap undos is becoming a meme_

More zap undo fixes IV

---

lib/validate.js
pages/settings/index.js

My tip default was 1 and I didn't enable `tipRandom` so `tipRandomMax` was set to 1, too.
However, that meant I couldn't save my settings and I received no feedback why. I saw the validation errors below the input for `tipRandomMax` (`must be more than minimum`) only after I enabled `tipRandom`.
This is bad UX. This PR fixes that by only validating `tipRandomMin` and `tipRandomMax` if `tipRandom` is set.
* changed label from `Enable random zap values` to `random zaps` since it's more consistent with how other zap settings are named
Yes
Yes, `tipRandomMin` and `tipRandomMax` are only saved if `tipRandom` is set
**For frontend changes: Tested …

Only validate tipRandom if enabled

---

api/ssrApollo.js

If you're getting redirected to the signup page because you're logged out, the callback is to a NextJS data URL.
For example, if you go to /territory and get redirected to /signup, the callback is `/_next/data/development/territory.json`.
yes
yes

Fix callback set to NextJS data URL

---

api/paidAction/itemCreate.js
api/resolvers/item.js
api/typeDefs/user.js
components/comment.js
fragments/users.js
lib/validate.js
pages/settings/index.js
prisma/migrations/20240808234214_investment_filter/migration.sql
prisma/migrations/20240808234214_sats_filter/migration.sql
prisma/schema.prisma

closes #690
This basically turns greeter mode from `yes, see freebies` or `no, don't see freebies` -to-> only see *posts* with at least X sats "invested." For comments, if `investmentFilter` > 0, freebies are collapsed unless they've been upvoted.
This is also compatible with wild west mode.
By default `investmentFilter = 10` and also applies to lurkers, giving them better spam filtering. We can increase this default for lurkers and new stackers as needed.

replace greeter mode with investment filter

---

components/use-local-state.js
pages/settings/wallets/[wallet].js
wallets/index.js

In #1278, I changed the logic in `useConfig` such that `wallet.config` is set to `clientConfig` (see [this line](https://github.com/stackernews/stacker.news/pull/1278/files#diff-fe57f778594fcebe6b8d96b7e6e0355bec7f8ca042a8397dc6a7fb508674344fR169)) which is null if no entry exists for WebLN in local storage.
This meant that the WebLN check became unclickable because `wallet.isConfigured` is false if `wallet.config` was null.
* reverted ddb32e0b because it was treating a symptom but this PR fixes the underlying issue
* I considered also adding this in this PR since `wallet.config` should now never be `null` but an empty object if no config exists (even during SSR for all wallets):
```diff
diff --git a/wallets/index.js b/wallets/index.js
index ba249678..cddd0a0e 100644
--- …
```

Fix WebLN checkbox unclickable

---

wallets/lnd/server.js
wallets/server.js

This was a pending TODO from #1243. `createInvoice` in wallets/server.js shouldn't need to parse LND errors. `createInvoice` in wallets/lnd/server.js should do that.
Yes
Yes

Remove TODO about errors in createInvoice

---

components/log-message.js
components/wallet-logger.js

Showing the wallet name if logs for only a single wallet are shown is redundant. This PR hides the wallet name in that case.
Before
After
Yes
Yes

Hide wallet name in logs for only a single wallet

---

wallets/index.js

Every wallet returned by the `useWallet` hook has `sendPayment` set even if it doesn't support payments since `wallet.sendPayment` is wrapped with a `useCallback` hook. This lead to every wallet getting deleted on logout.
This PR fixes that by exposing `canSend` in `useWallet` which is then used to check if this wallet should get deleted.
Looked into this because of https://stacker.news/items/651050
Yes
Yes

Fix all wallets deleted on logout

---

api/paidAction/index.js
lib/format.js
wallets/cln/server.js
wallets/lightning-address/server.js
wallets/lnbits/server.js
wallets/lnd/server.js
wallets/server.js
wallets/wrap.js
worker/autowithdraw.js

fixes #1303
Mostly this floors any msats passed to lnaddr's `createInvoice`. This change also required modify `wrapInvoice` to take the served invoice's msats as a parameter (as it can't be induced anymore). For p2p zaps, the excess msats effectively get paid to SN.

Msats to sats floor

---

api/resolvers/wallet.js
api/typeDefs/wallet.js
fragments/wallet.js
lib/wallet.js

This PR makes it easier to add server wallets by generating more boilerplate plumbing code:
* generate `type WalletLND { ... }` etc.
* generate `union WalletDetails = WalletLND | ...`
* I could unfortunately not see a way to generate `__resolveType` with its fourth argument as mentioned [here](https://github.com/stackernews/stacker.news/pull/1278/files#r1707709821) so I left a comment there
<details>
<summary>info object</summary>
```
GraphQLUnionType {
name: 'WalletDetails',
description: undefined,
resolveType: [Function: __resolveType],
extensions: [Object: null prototype] {},
astNode: {
kind: 'UnionTypeDefinition',
description: undefined,
name: { kind: 'Name', value: 'WalletDetails' },
directives: [],
types: [ [Object], [Object], [Object], [Object] ]
},
extensionASTNodes: [],
_types: [ …
```

Generate more server wallet code

---

middleware.js

Add wasm-unsafe-eval to CSP for LNC

---

api/resolvers/wallet.js
api/typeDefs/wallet.js
lib/wallet.js

506bb364 fixed the query for LN addresses but it broke it for LND since now `__resolveType` returned `WalletLnd` but it should have been `WalletLND`.
With this PR, `__resolveType` will always return the same as `generateTypeDefName`.
Yes
Yes, all wallets resolve now

Fix inconsistency between walletTypeToResolveType and generateTypeDefName

---

api/paidAction/itemCreate.js
api/resolvers/user.js
api/typeDefs/user.js
components/fee-button.js
fragments/users.js
lib/validate.js
pages/settings/index.js
prisma/migrations/20240819233308_disable_freebies/migration.sql
prisma/schema.prisma
wallets/index.js

Introduces a setting for disabling freebies. By default, this is null. When the first sending wallet is attached, `disableFreebies` is set to true IFF `disableFreebies` is null, otherwise the setting is completely controlled by the stacker.

disable freebies setting

---

api/paidAction/index.js
lib/constants.js
wallets/server.js
worker/paidAction.js

closes #1314 
This limits pending *incoming* paid actions per *stacker* to 100.
This limits pending *outgoing* paid actions/autowithdraws per *wallet* to 25.
If you lower the limits to 0, or close to 0, they behave as expected:
- new paid actions are rejected
- `createInvoice` throws
I also tested that prisma does not count `null` in `notIn` queries.

paid action limits

---

api/typeDefs/item.js
components/item-info.js
components/item.module.css
fragments/items.js

This PR fixes the accessibility issue that `item.meSats`, `item.upvotes` or the exact timestamp is only visible on hover which isn't available on mobile. It introduces `details` as a new entry in the item context menu. On click, it opens this modal:
I also added `item.cost` for everyone to see even though it was only visible to the author before since I don't consider it sensitive. 
Mobile:
Yes, I only additionally resolve `item.cost` in item queries now which isn't a breaking change
Yes, tested logged in and logged out.
Yes, see screenshot …

Show item details via context menu

---

api/resolvers/user.js

On every wallet save if `disableFreebies <> NULL`, this would show up in the logs:
```
Invalid `prisma.user.update()` invocation:
An operation failed because it depends on one or more records that were required but not found. Record to update not found.
at _n.handleRequestError (/app/node_modules/@prisma/client/runtime/library.js:121:7749)
at _n.handleAndLogRequestError (/app/node_modules/@prisma/client/runtime/library.js:121:7057)
at _n.request (/app/node_modules/@prisma/client/runtime/library.js:121:6741)
at async l (/app/node_modules/@prisma/client/runtime/library.js:130:9355)
at async Object.disableFreebies (webpack-internal:///(api)/./api/resolvers/user.js:612:17) {
code: 'P2025',
clientVersion: '5.17.0',
meta: { modelName: 'User', cause: 'Record to update not found.' }
}
```

Ignore no rows found in disableFreebies

---

wallets/index.js

When a wallet that supports send+recv, the full config was saved on the client on priority change. It didn't cause any issues but wasn't intended. It was fixed in 8e3f4ae4.
However, 8e3f4ae4 revealed a bug where we actually save an empty WebLN config because if we use a function for validation, the function has to return an object in the format Formik expects errors. So in case of no errors, it returns an empty object. So this means that all this time, only the `wallet.enablePayments()` call actually saved `enabled: true` for WebLN. This was fixed in 503d4de9 by not overwriting the config with the return value of `walletValidate` but merging it.
For consistency, the config is now always merged with return values in 27bcef9d. …

Fix full config saved on client on priority change

---

fragments/wallet.js
lib/validate.js
prisma/migrations/20240821014115_phoenixd/migration.sql
prisma/schema.prisma
scripts/genwallet.sh
wallets/client.js
wallets/phoenixd/client.js
wallets/phoenixd/index.js
wallets/phoenixd/server.js
wallets/server.js

Close #1315
TODO:
I will probably test the API calls on mainnet since `phoenixd` doesn't support signet yet (https://github.com/ACINQ/phoenixd/issues/49)
* included a `genwallet` script that generates some boilerplate code. It also marks the lines of code that require updates with TODOs that are easily searchable.
* cherry-picked the commits that rename the wallet interface from #1310 
* `phoenixd` only supports `mainnet` and `testnet`:
```
$ phoenixd --help
Usage: phoenixd [<options>]
Liquidity Options:
--auto-liquidity=(off|2m|5m|10m)  Amount automatically requested when inbound liquidity is needed (default: 2m)
--max-mining-fee=<int>            Max mining fee for on-chain operations, in satoshis (default: 1% of auto-liquidity amount)
--max-fee-credit=(off|50k|100k)   Max fee credit, if …
```

Phoenixd send+recv

---

api/paidAction/itemCreate.js
api/resolvers/item.js
api/typeDefs/sub.js
components/fee-button.js
components/post.js
components/territory-form.js
fragments/paidAction.js
fragments/subs.js
pages/settings/index.js

- removes freebie posts (and removed from territory form)
- ranks unfreed freebie and deleted comments at bottom regardless of sort (e.g. recent)
I left the `allowFreebies` territory setting for backwards compat.
Should be.
`6`: I didn't test unarchiving territories or anon posts/comments.
n/a
no

Improve freebies

---

wallets/README.md
wallets/blink/client.js
wallets/index.js
wallets/lnbits/client.js
wallets/lnc/client.js
wallets/nwc/client.js
wallets/phoenixd/client.js

NWC wallet logs contained `preimage=undefined` because `sendPayment` returned it as a string while the caller expected an `{ preimage }` object.
I've noticed that this expectation lead to undefined preimages in two more cases: Blink returned `{ preImage }` (note the wrong case) and phoenixd returned it as a string like NWC.
I have therefore decided to change the interface to return preimage as plain strings now. An object was only originally chosen to match the [WebLN interface of `sendPayment`](https://www.webln.guide/building-lightning-apps/webln-reference/webln.sendpayment).
yes
tACK 86b18bb0 8. I didn't …

Fix preimage undefined in wallet logs

---

lib/cln.js
lib/proxy.js
wallets/lnbits/server.js

Close #1166 
This adds the agent that is used to withdraw to a CLN node on Tor to LNbits.
This will only work for receive because our Tor proxy is only available on the server.
yes
tACK 662b18ed 8. I tested attaching CLN and LNbits for receiving and made sure that the correct agent is selected depending on the given socket/URL. Both attach successfully if given `stacker_cln:3010` or `lnbits:5000`.
no

Support Tor for LNbits recv

---

components/banners.js
pages/settings/wallets/[wallet].js

I have noticed  that the wallet security banner is missing for wallets that can spend and receive.
This PR adds it back if a wallet can spend and updates the text.
The banner takes up a lot of space on mobile. Maybe it should be dismissable?
yes
tACK 695620fb 10. Tested all wallets.
yes, see screenshot
no

Update wallet security banner

---

middleware.js

Possible fix for #1332 
I don't know why this only happens on Firefox. Safari and Chrome load these resources that are added dynamically to the DOM from `a.stacker.news` fine:
_route-loader.js:83_
```js
function prefetchViaDom(href, as, link) {
return new Promise((resolve, reject)=>{
const selector = '\n      link[rel="prefetch"][href^="' + href + '"],\n      link[rel="preload"][href^="' + href + '"],\n      script[src^="' + href + '"]';
if (document.querySelector(selector)) {
return resolve();
}
link = document.createElement("link");
// The order of property assignment here is intentional:
if (as) link.as = as;
link.rel = "prefetch";
link.crossOrigin = process.env.__NEXT_CROSS_ORIGIN;
link.onload = resolve;
link.onerror = ()=>reject(markAssetError(new Error("Failed to prefetch: " + …
```

Add a.stacker.news to script-src

---

components/modal.js

If you open a modal where `onHide` is set to `null` (like when you click on "pending" for a comment) and then press ESC, this error is thrown and not caught: `TypeError: onHide is not a function`
yes
tACK 1c1f8df1 10

Fix onHide is not a function

---

prisma/migrations/20240902125646_undelete_bios/migration.sql

In #1295, I only fixed that the bio marker was missing for old bio items.
However, I didn't fix that some bio items were already deleted (since the marker was missing). This PR fixes that.
https://stacker.news/items/668143
yes
tACK 348610f0 10. Ran the migration locally and a deleted bio item was no longer deleted and thus editable.

Undelete bio items

---

middleware.js

This should fix CSP errors in Firefox because scripts fetched via `<link rel="prefetch">` don't use `script-src`.
Potential fix for #1332 
yes
not QA'd since CSP errors only happen in prod build

Use default-src 'self' a.stacker.news

---

components/autowithdraw-shared.js
components/form.js
components/use-client.js
pages/settings/wallets/[wallet].js
pages/settings/wallets/index.js

If only recv was configured for a wallet and we reloaded the page while we were on the configuration page, `enabled` was not set since it's initially set to undefined while the query is loading. Using [`enableReinitialize`](https://formik.org/docs/api/formik#enablereinitialize-boolean) reinitializes the form if the initial values change.
Additional changes:
* fix `readOnly` hydration error
* refactor repetitive logic to check if component is mounted with `useIsClient` hook from [here](https://usehooks-ts.com/react-hook/use-is-client#hook)
This has been an issue at many places and I solved it in the past using `ClientInput` which manually sets the value if the `initialValue` prop changes using this combination of `useField` and `useEffect`:
```js
function Client (Component) {
return ({ …
```

Reinitialize wallet form if initial values change + fix readOnly hydration error

---

components/image.js
components/text.module.css

This is pretty straightfoward. Basically when we are determining if a link might be an image before falling back to an link, we do the same for video.
This is the first step toward supporting video uploads and gif to video conversions.
7. I tested both posts and comments with this link https://video.nostr.build/e5607f8cee909defe6276ab14cf2fe0c53630664f7630ef3e6986fca4f1f5881.mp4
P.S. This image code could use a refactor.

recognize video links

---

api/typeDefs/user.js
components/image.js
fragments/users.js
pages/settings/index.js
prisma/migrations/20240903235340_hide_images/migration.sql
prisma/schema.prisma

closes #610 
This introduces a new setting to render images/video as links instead of images/video. They open like a link when clicked - in a new tab.
By default and for anon, images and videos are shown.
`6` Tested image and video links anon/logged in with all combos of imgproxy only and show images and videos.
I did not test proxied images.

Optout of display of images and video (show them as links)

---

components/accordian-item.js
components/invoice.js
pages/satistics/index.js

* fix missing `margin-left` when there is an invoice comment
before:
after:
* fix `margin-bottom` not applied to accordian body
before:
after:
yes
`7.5`
yes
no

Random CSS fixes

---

components/media-or-link.js

This PR fixes various things around the new embeds.
For example, it fixes this issue with the nostr embed caused by https://github.com/vercel/next.js/issues/39451:
<details>
<summary>video</summary>
https://github.com/user-attachments/assets/7ae44b3e-9a4c-4b6e-92ec-b3996629ac48
</details>
* The wavlake embed allows zaps using WebLN. Would be cool if we could get the bolt11 somehow and use the attached wallets instead.
* there is a warning that mentions that `allow-scripts` + `allow-same-origin` allows iframe to escape the sandbox during runtime but this only applies to embeds loaded by the same origin as the parent:
> Note, however, that you need to be very careful when dealing with framed content that comes from the same origin as the parent. If a page on https://example.com/ frames …

Fix embeds

---

components/adv-post-form.js
components/job-form.js
components/territory-form.js
pages/settings/index.js

I removed `fw-bold` from info text where it didn't highlight anything and was thus overused.
Related to https://github.com/stackernews/stacker.news/pull/1368#discussion_r1748677129
yes
`9` I used search & replace (`ul className='fw-bold'` -> `ol` and `ul className='fw-bold'` -> `ul`) and verified that the syntax is correct.
no

Remove overused fw-bold from infos

---

lib/time.js
wallets/server.js

Fix #1378 
yes
`9` I tested using two accounts. One has NWC send and other has LNbits recv attached. Since a timeout of 10 seconds succeeds locally (receiver sees a p2p zap in notifications), I used a timeout of 1 millisecond for testing and it correctly times out and falls back to a zap into the custodial wallet.

Fix missing user invoice timeout

---

prisma/migrations/20240910000406_auto_weekly_posts/migration.sql
worker/index.js
worker/thisDay.js
worker/weeklyPosts.js

Does what title says. 
- It also makes them all have a `bot` tag and does the same for `thisDay` posts
- `thisDay` doesn't "skip" paying anymore either. It pays like anyone else.
`7`. Ran all jobs manually and they worked. Didn't test paying a bounty a real top comment thread, but it worked with some test comments.

automate meme monday, fact friday, what work wednesday

---

components/lightning-auth.js
jsconfig.json
pages/_app.js
wallets/index.js
wallets/webln/index.js

Close #945 
This listens for `webln:enabled` and enables the attached wallet responsible for WebLN. This means that stackers only need to enable WebLN once by logging in with lightning which will optimistically call the `window.webln` stuff or by clicking on the QR code during payments. After that, following payments will first try to use the WebLN wallet using our wallet code like any other wallet before showing any QR code.
I think only running WebLN optimistically during login and not also during payments is a good compromise since the user will be asked to enable WebLN during login. If they do, the WebLN wallet is also enabled which will then call the `window.webln` stuff optimistically because we use our attached wallets optimistically.
WebLN is optimistically called during Login …

Enable WebLN wallet on 'webln:enabled'

---

api/resolvers/apiKey.js
api/resolvers/invite.js
api/resolvers/item.js
api/resolvers/lnurl.js
api/resolvers/message.js
api/resolvers/notifications.js
api/resolvers/ofac.js
api/resolvers/referrals.js
api/resolvers/rewards.js
api/resolvers/serial.js
api/resolvers/sub.js
api/resolvers/upload.js
api/resolvers/user.js
api/resolvers/wallet.js
lib/error.js

_cherry-pick of commit c27eafdcdb28d5af77847d5fb19befb35400a655 from #644_
All these changes were included in #644 but are easier reviewed independently.
There is actually not much to review, I simply replaced all usage of `GraphQLError` with a custom instance for less repetition / more consistency. I did this because I wanted to be sure that there are no typos for the error code since I use it [here](https://github.com/stackernews/stacker.news/pull/644/files#diff-740636f0d82955f9b0b7681e3c7920fbc93821a10c25722b7eb04061ea43daa2R157-R159) in #644.
When this is merged, I will rebase #644 which will make the change set smaller.
**On a scale of 1-10 how well and how have you QA'd this change and any features it might affect? …

Throw errors which extend GraphQLError

---

pages/settings/index.js

I noticed this while reviewing #1373 that if the banner is shown and we switch tabs, there's an ugly layout shift.

Fix layout shift between setting tabs

---

api/paidAction/itemCreate.js
lib/webPush.js

If someone with reply notifications enabled is subscribed to a user and that user replies to them, they will receive two push notifications for the same item; once as a reply and once as a subscription. However, only one notification will show up in /notifications.
This PR fixes that by only sending a push notification for a user subscription if that user wasn't already notified of the item as a reply; making the experience consistent with what they will see on /notifications.
I noticed that push notifications are not fully consistent with /notifications since even if the setting `someone replies to someone who replied to me` is disabled, we still receive notifications if someone replies directly to us but no push notification. Essentially, that setting encompasses all replies for push …

Fix duplicate push notification as reply and subscription

---

wallets/index.js

This removes the inconsistent exclusivity of assigning only `isConfigured`, `enablePayments` and `disablePayments` to the wallet object in `useWallet`
Why I even started doing this in the first place: https://github.com/stackernews/stacker.news/pull/1278#discussion_r1703313506
yes
`7`. I've tested that attaching wallets and paying from them still works.
n/a
no

useWallet hook cleanup

---

components/wallet-logger.js
wallets/index.js

I noticed that I lost my phoenixd wallet because it can send so it got completely deleted on logout. It should only delete the send config. I probably forgot to update this code after we started to support wallets which can send and receive at the same time.
Also added that logic to wallet logs deletion.
yes
`7`.
* tested that a wallet that has send+recv configured only loses send on logout
* tested that only send logs are deleted on logout
* tested that deleting logs while on a wallet config page only deletes logs of that wallet
* tested that deleting logs on the page that has all wallet logs deletes logs …

Fix recv wallet deleted on logout

---

api/resolvers/upload.js
components/file-upload.js

Upload errors were toasted but still bubbled up. This PR fixes that by stopping errors from bubbling up.
Also renamed more stuff that assumed we're only dealing with images.
yes
`7`. Tested by setting upload limit to 1MB and uploaded a file >1MB.
n/a
no

Catch s3 upload errors

---

api/resolvers/item.js
components/item-info.js
components/use-item-submit.js

The combination of #1393 + #644 made it possible that the author of an item could change from anon to a user and vice versa.
This PR makes sure that during item updates, the author is never changed. 
yes
`8`
* switched accounts and edited item with different author and made sure author doesn't change (using e04f64e8 before edit option disappears on switch)
* made sure hash+hmac edit only shows for anonymous items if anonymous
n/a
no

Never update author of item on edit

---

.platform/nginx/conf.d/elasticbeanstalk/00_application.conf
pages/api/auth/[...nextauth].js
pages/api/graphql.js
pages/api/signout.js

I have noticed that `Secure` isn't set for the multi auth cookies in prod as they should here for connections that use TLS:
https://github.com/stackernews/stacker.news/blob/c8975038bdee5ce4cd4c5655724ac0baada9b21a/pages/api/auth/%5B...nextauth%5D.js#L121-L127
This means that these checks that use `request.secure` are most likely not working as intended:
https://github.com/stackernews/stacker.news/blob/c8975038bdee5ce4cd4c5655724ac0baada9b21a/pages/api/graphql.js#L91-L98
https://github.com/stackernews/stacker.news/blob/c8975038bdee5ce4cd4c5655724ac0baada9b21a/pages/api/signout.js#L14-L22
This explains why switching doesn't work because the multi auth middleware never looks up the correct session cookie and think there is nothing to do for it.
This is most likely caused by TLS termination …

Use X-Forwarded-Proto to detect scheme

---

.platform/nginx/conf.d/elasticbeanstalk/00_application.conf
pages/api/auth/[...nextauth].js
pages/api/graphql.js
pages/api/signout.js

#1403 didn't fix #644 in prod. This PR simply always sets  `Secure` for the multi auth cookies in prod using `NODE_ENV` instead of relying on a `X-Forwarded-Proto` header.
yes
not tested
n/a
no

Always set Secure for multi auth cookies in prod

---

components/table-of-contents.js
components/text.js

I've noticed that the slugs generated in the FAQ are not always consistent with the slugs that are used in the Table of Contents. This means that if you click on an entry in the ToC, you might not get scrolled anywhere. This seems to happen if you move from a post to the FAQ. I assume that's the case since that case triggers a lot of changes in the `<Text>` component; calling `GithubSlugger.slug` a lot of times with the same inputs which always generates unique slugs.
At first I thought this is caused by strict mode but strict mode isn't enabled in production afaik and it also still happens if it's disabled locally.
To reproduce:
1. Go to https://stacker.news/items/683598
2. Click link to FAQ in the footer
3. Notice how site loads slow because a lot of renders are triggered
4. Click on a …

Fix different slugs in ToC vs text

---

components/hat.js
styles/globals.scss

The contrast for the hat in the profile is bad in dark mode:
It's okay in light mode:
This is caused by the hat assuming it's put against the background but in the profile, it's inside a badge that always uses `bg='grey-medium'`.
This can be fixed by always using the color that light mode uses. This is `#212529`.
yes
`9`. `fill-dark` is only used when the icon is inside a badge with `bg-medium`.
n/a
no

Fix hat contrast in profile

---

pages/settings/settings.module.css

The tabs in /settings were overflowing and `margin-left` caused the next row to appear unexpectedly indented. I fixed this using `gap`, see screenshots.
This changes this:
to this + if row overflows, there is no indentation:
I used `gap: 0 0.5rem` instead of  `gap: 0 1rem` to keep the original margin because I found the original margin to be too much.
yes
`9`. settings.module.css is only used in /settings and /satistics and both look fine/better with the change.
yes …

Fix margin on row overflow

---

lib/nostr.js

I have noticed that `this.error` in the `onerror` websocket callback assigns the error to the websocket object, not the `Relay` instance. So it was available at `this.ws.error`.
This PR fixes it by using arrow functions which don't rebind `this`.
I digged into this because of the discussion about NWC and Coinos [here](https://stacker.news/items/691917) but this isn't going to fix whatever is the issue, only fix that we might show `null` as the error.
Strangely, I noticed that I get HTTP 403 Forbidden errors from the Coinos relay when trying to connect to it for NWC receives but I don't when I connect to it for NWC sends. The only difference is client vs server who initiates the connection.
But since this also happens locally, I am confused what the difference is for the relay. Maybe …

Fix nwc error message

---

components/upvote.js
lib/rainbow.js

Fix [this](https://stacker.news/items/692150?commentId=692635) and [this](https://stacker.news/items/692150?commentId=692268).
The changes in 5f0494de30f4730445a9b12361050c83deb40b65 in components/upvote.js made the `fill` style on hover or pending not show up if the item wasn't zapped before.
This PR fixes this. Instead of reverting to using `meSats` as a condition for when to show the style, I actually updated the `getColor` function since I believe it should actually return the default color if the item was clearly not zapped yet instead of always at least the first upvote color.
yes
`8`. Tested that …

Fix upvote hover style not showing for first zap

---

components/item-act.js

This didn't cause any bugs because `useWallet` returns everything we need on first render on `master`.
This caused a bug with the changes in #1373 though since there the wallet is loaded async.
This meant that during payment, the wallet config was undefined.
yes
`10`. This fixes the bug I encountered in #1373 when testing wallets.
n/a
no

Fix missing effect dependency for useZap

---

api/resolvers/upload.js

It's annoying when downloading pictures from m.stacker.news that the extension is not included in the URL.
yes
`7`. Tested locally with one image.
n/a
no

Include extension in S3 key

---

components/item-act.js
lib/apollo.js
pages/api/graphql.js

This uses a conditional batching apollo link if successive zaps are made so they can be serially/batch executed so updating the client cache doesn't race.
This batching link is only used if there's a wallet attached or using custodial sats so that QR popup isn't delayed by the debounce.
fixes #1389 
QA: `7`

batch zap requests

---

components/nav/mobile/offcanvas.js
components/nav/mobile/offcanvas.module.css
components/toast.module.css

This adds a slide-in animation for toasts and the offcanvas.
https://github.com/user-attachments/assets/780da5b5-4445-4356-a264-0ef6feedf855
yes
`8`. Tested as seen in the viode.
Yes, see video.
No

CSS animation for toasts and offcanvas

---

api/paidAction/index.js
api/resolvers/paidAction.js
components/comment.js
components/form.js
components/invoice.js
components/item-act.js
components/item-info.js
components/item.js
components/notifications.js
components/use-paid-mutation.js
styles/globals.scss
worker/index.js

Currently this fixes #1381 ... "fixes" because it just gives better errors messages and aims to prevent the cause: unintentional double-clicks of the retry button.
The retry button is now disabled and pulsed when pressed.
This also fixes #1361 by not waiting for settlement on pessimistic acts (if p2p zap and receiver uses a zap locker, it'll never settle). This has no impact on optimistic acts.
Bonus: adds a `settling` message on pessimistic QR-paid actions.

UX latency enhancements for paid actions

---

api/lnd/index.js
api/paidAction/index.js
api/resolvers/blockHeight.js
api/resolvers/chainFee.js
api/resolvers/price.js
api/resolvers/wallet.js
components/payment.js
components/use-paid-mutation.js
components/wallet-logger.js
fragments/wallet.js
lib/fetch.js
pages/api/lnurlp/[username]/pay.js
pages/api/lnurlp/[username]/verify/[hash].js
prisma/migrations/20241002145114_create_invoice_update/migration.sql
wallets/wrap.js
worker/imgproxy.js
worker/nostr.js
worker/paidAction.js
worker/wallet.js

Currently, we beat the crap out of lnd with super frequent, redundant, or unnecessary grpc calls.
So far:
- replace use of `decodePaymentRequest` with `parsePaymentRequest`
- cache blockheight
- cache our node's pubkey
- cache node info
- bonus: reuse cache abstraction for price fetching and fee rate fetching
Planned:
- this was worse than I thought - it's was two calls per state machine transition when we could've gotten away with 0 using the subscription event object
Test todo:

Be kind to lnd

---

README.md
api/paidAction/README.md
api/paidAction/boost.js
api/paidAction/index.js
api/paidAction/itemCreate.js
api/paidAction/itemUpdate.js
api/paidAction/zap.js
worker/paidAction.js

fixes #1461
These were failing in prod regularly because some of them were done in the paid action's interactive tx, but because they were async the tx was already closed when they ran.
This moves these noncritical side effects outside of the tx.
QA: `8`. I've tested that the modified paid actions still run (fee credits, optimistic, pessimistic), and that noncriticalSideEffects don't error. I tested that all modified paid actions send notifications, but I didn't test all possible notifications they can send.

run noncritical side effects outside critical path of paid action

---

fragments/users.js
pages/settings/index.js

These are no longer used and considering we fetch `me` a lot, probably best to remove.
QA: `5`. I searched around for all uses of `\b(user|me)\??\.(optional|privates)\??\.` and looked for any unexpected/unnecessary `me` usage.

remove unused fields from me fragment

---

worker/wallet.js

I noticed that in `subscribeForever`, `sub` could still be a promise when we reach the finally block since we never assign the event emitter to it when `subscribe` returned a promise.
I am not sure if this lead to any leaks but if so, they should be fixed now.
You can reproduce the error by giving the worker bad LND credentials.
yes
`5`. Looked at logs w/o change -> found `sub?.removeAllListeners is not a function` in worker logs. Looked at logs with change -> no more such error
n/a
**Did you introduce any new environment variables? If so, …

Fix sub?.removeAllListeners is not a function

---

components/wallet-logger.js

This fixes an infinite loop of reloading wallet logs.
Also moved `more` button from this
to center like this:
I think this is more consistent with the logs layout and how other buttons for more look.
yes
`6`. Made sure logs for every wallet still load correctly.
yes, see screenshots
no

Fix infinite loop of loading wallet logs + center more button

---

components/wallet-logger.js

This fixes the first page getting loaded again when clicking on `more` for wallet logs.
This also matches the behavior of `loadLogs`. It also loads the first page and then calls `setPage(1)`.
yes
`5`. Clicked on button once to check that second page is now loaded
yes
no

Fix first page of wallet logs loaded twice

---

lib/validate.js

The wallets which weren't the original receive wallets didn't validate autowithdraw settings (NWC, LNbits, phoenixd).
yes
`5`. I saved NWC, others should work too then
n/a
no

Fix missing autowithdraw settings validation

---

api/resolvers/wallet.js
worker/wallet.js

fixes #1485 
It looks like prisma's interpretation of intervals in templates changed at some point. I didn't find anywhere else where we use intervals this way.
QA: `6`. made invoices, reproduced bug, then made some more invoices, ran job - no deletions, made one of the invoices artificially old, ran job - only old one deleted.

premature invoice deletion: fix interval in sql template

---

api/resolvers/sub.js

Fix https://stacker.news/items/731783?commentId=731806
The validation on the server to unarchive territories included the sub name which meant it was in "edit mode" an dthus failed for achived territories.
yes
`5`. I reproduced the bug and noticed the divergence of validation on client vs server. Fixing it also fixed the bug.
n/a
no

Fix territory unarchive schema validation

---

pages/invites/index.js

fix #1518
yes
`8`. Reproduced bug and verified that after fix invites can be created again. Looking at the code and code history, it's a trivial fix.
n/a
no

Fix missing fragmentName

---

api/paidAction/index.js
wallets/wrap.js

fix https://stacker.news/items/738313
Invoices from attached wallets already respected the privacy setting of the recipient.
However, the description of wrapped invoices was determined by the setting of the recipient.
This PR fixes that. Wrapped invoices now respect the sender's privacy setting.
QA: `8`. I tested all combinations of sender+receiver privacy settings. This respects them in all cases.

Fix description of wrapped invoices don't respect privacy setting

---

components/comment.js
components/item-info.js

This often happens to me: I am editing something and then the timer runs out. Now I am stuck with a comment in edit mode that I can't exit 
This PR fixes that by showing `cancel 00:00` when the timer runs out so one can still exit edit mode.
an edgy amount of props drilling was required here
yes
`6`. I edited a comment and waited until the timer runs out. It still showed the option to cancel.
yes, no changes
no

Don't hide cancel if edit timer runs out

---

fragments/paidAction.js

The `upsertComment` mutation currently returns the list of child comments whenever a comment is edited. This behavior causes the Apollo cache to update, resulting in any new comments appearing upon the re-render triggered by the edit form. This PR modifies the `UPDATE_COMMENT` fragment to exclude the list of child comments, preventing unintended cache updates. #1509
yes
9. Comments are updated as expected at different levels of depth, as expected editing doesn't cause the child comments to refresh anymore. …

Prevent UPDATE_COMMENT from invalidating the cache of child comments (Fix #1509 )

---

components/error-boundary.js
lib/stacktrace.js
package-lock.json
package.json

This pull request addresses [issue #1524](https://github.com/stackernews/stacker.news/issues/1524). It adds a helper function that fetches and utilizes the source .map files to decode the stack trace and implements it when a user clicks on "Copy Error Information."
yes
9 - This implementation looks for a specific stack trace pattern, but I am unsure if it may vary. However, it does return the original stack trace intact, so any failure in pattern matching will not lead to losing information in the report.

decode minified stacktrace

---

pages/settings/wallets/index.js

On current `master` (d6caee5b), if you want to move a wallet one to the right, you have to drag it two wallets. Dragging a wallet only one to the right does nothing which looks like a bug:
https://github.com/user-attachments/assets/d5db5e69-8699-4fab-9a12-2221efd597cc
It's also inconsistent with moving wallets to the left where you only need to drag it one slot:
https://github.com/user-attachments/assets/d6967fae-129c-419a-8a98-ac5e3e7a6e35
This PR makes dragging wallets left or right consistent with each other:
https://github.com/user-attachments/assets/8454c8ca-e15f-473a-b365-ed2deacd7bad
yes
`6`. Tested …

Fix wallet priority reorder inconsistency

---

components/wallet-logger.js

If we're on /wallet/logs, we want to show logs from all wallets. For that, we pass no wallet to `useWalletLogs` but the underlying function to fetch logs assumed there is always one set and only fetched local logs in the case of no wallet.
I've seen that I basically reverted the line change in https://github.com/stackernews/stacker.news/commit/2bdbb433df8c36d848d00a6a423a5c5d2df4eb8f so I made sure that WebLN still saves. I think the previous line was correct and changing it was just an oversight.
yes
`5`. I made sure that NWC logs and LNbits are fetched fine individually (locally + from server) and …

Fix global wallet logs never fetch logs from server

---

components/vault/use-vault-configurator.js

fix #1543 
This problem was caused by only one `useVaultConfigurator` receiving the new key when a device is connected. I had been assuming the `useEffect` would capture this update on connect - but it doesn't because `me.privates.vaultKeyHash` changes before the device is connected.
This adds apollo's `reactiveVar` to create a global var holding the vault key now so that if one instance changes it, all instances change.
I made it so that if the local key hash doesn't match, we unsync any local wallets to local storage.

fix vault key changes not seen by all instances of useVault

---

wallets/index.js

Add a `storage` even listener to pickup wallet updates in other tabs. fix #1550
QA: `8`. Opened two tabs to nwc wallet, modified config and watched it change. Detached one, watched the other go blank. Reattached one and was able to zap in the other without reload.

listen for local storage wallet changes

---

components/form.js
lib/validate.js

Our passphrase scanning was broken because we were using the wrong destructured freld from formik's `useField`.
This fixes that. It also adds some text to the qr scanner modal ("Where'd you learn to square dance?") and truncates the validation text.
QA: `8`. Enable -> show qr -> take picture of qr with my phone -> refresh page -> disconnect -> scan picture of qr -> enable

fix passphrase scanning

---

components/invoice.js

This problem is caused by a mis-ordered `if` statement which should be pretty easy to see from the old `if` statement - a confirmed invoice that were at one point `isHeld` were being displayed as `settling`.
QA: `5`. I couldn't easily reproduce the bug, but I'm pretty sure this ordering is correct thinking through all possible situations.

fix invoice status display

---

pages/api/auth/[...nextauth].js

Fix #1560 
- Prisma Client API documentation for [`updateMany`](https://www.prisma.io/docs/orm/reference/prisma-client-reference#updatemany)
yes
`10`. Confirmed no push notification is sent when I do the same I did in https://github.com/stackernews/stacker.news/issues/1560#issuecomment-2466410003
n/a
no

Only send push notification if referrer was updated

---

components/nav/common.js

Fix this:
https://github.com/user-attachments/assets/640a4330-3790-4b10-a575-6ed6e4bd9b9f
yes
`10`. I clicked on `logout` and offcanvas closed.
yes
no

Fix offcanvas not closed before showing logout prompt

---

api/resolvers/item.js

I noticed during SNL yesterday that inactive territories have `hot` sorts that look more like `top` ... it turns out they were `top`.
This happened sometime ago when I changed the equation for sorting to have a boost term in the numerator. What I missed is that this effectively made the equation `numerator + boost / decay` rather than `(numerator + boost) / decay`. Lame.

fix precedence of op for not full hot sort

---

.env.development
README.md
docker-compose.yml
docker/tor/services.conf
docker/tor/tor.sh
sndev
wallets/cln/ATTACH.md
wallets/lnbits/ATTACH.md
wallets/lnd/ATTACH.md
wallets/webln/ATTACH.md

closes #1533
You'll have to delete and restart containers after this is merged. It renames `stacker_(lnd|cln)` to `(lnd|cln)` and relies on docker compose labels to provide access to service clis/onions/certs now.
This replaces:
- `sndev fund_user` -> `sndev set_balance`
- `sndev (stacker|sn)_(lndcli|clncli|litcli)` -> `sndev cli (lnd|sn_lnd|cln|litd)`
- `sndev (stacker_(lnd|cln)|lnbits) get_onion` -> `sndev onion (lnd|cln|lnbits)`
- `sndev stacker_lnd get_cert` -> `sndev cert lnd`
- `sndev (fund|withdraw)_cln` -> `sndev (fund|withdraw) --cln`
This adds:
- `sndev test` command (which just runs our one jest test)

sndev cleanup

---

api/resolvers/item.js
components/item-info.js

If you delete an item while it's still editable, it still looks like it's editable.
I also refactored some code because I realized the state was only needed for anon edits (see individual commits).
The bug:
https://github.com/user-attachments/assets/188cd971-e25f-4db6-86b7-2f81dbf253ca
Proof of fix and no new regression:
https://github.com/user-attachments/assets/b7015756-4417-4e83-a5f5-daf61199ce7c
I considered renaming `canEdit` to `showEditCountdown` but that variable was too long and I think it's clear from the context it's only about the edit countdown and that the actual edit authorization happens on the server.
yes
**On a scale of 1-10 how well and how have you QA'd this change and any features it might affect? Please …

Fix edit countdown on deleted items

---

api/resolvers/item.js

Not tested but I believe this is what was missing.
We probably only need the outlaw clauses since the other clauses shouldn't be relevant for the front page but I think they don't hurt (except the extra user query maybe).
But we also use `filterClause` for the mostly empty subs so I guess we should apply the same filtering here.
yes
`1`. It does not crash the server.
n/a
no

Fix outlawed can show up on front page

---

worker/paidAction.js
worker/wallet.js

I am pretty sure that fixes https://stacker.news/items/760734?commentId=760753 but couldn't test without fees.
I personally would be interested in seeing how much SN had to pay for the forwarding but I can see how that can conflict with UX. It probably isn't interesting to most and would just cause confusion and lead to questions, even if I rename `fee` to `sn_fee`. However, what do you think?
```diff
diff --git a/worker/paidAction.js b/worker/paidAction.js
index 60aac122..5d505963 100644
--- a/worker/paidAction.js
+++ b/worker/paidAction.js
@@ -289,10 +289,10 @@ export async function paidActionForwarded ({ data: { invoiceId, withdrawal, ...a
`↙ payment received: ${formatSats(msatsToSats(received))}`,
{
bolt11,
-          preimage: payment.secret
+          preimage: payment.secret,
// we …
```

Fix fee added to received amount

---

wallets/index.js

When you clear local storage, the event has no key.

Fix TypeError if local storage is cleared

---

components/form.js

Images and other file uploads update the draft reply, fixes #1522
Unfortunately it's difficult to show the difference using screenshots, maybe I can try with a screen recording later?
Nothing to report.
**Are your changes backwards compatible? Please answer below:** Yes
**On a scale of 1-10 how well and how have you QA'd this change and any features it might affect? Please answer below:** 8. Throughly tested manually on dummy posts, no automatic tests.
**For frontend changes: Tested on mobile? Please answer below:** Yes, they work.
**Did you introduce any new environment variables? If so, call them out explicitly here:** No

fix: reply storage is updated with the new content on file upload

---

components/layout.js
components/pull-to-refresh.js
components/pull-to-refresh.module.css

Pull-to-refresh for iOS, completing #1258.
As `router.reload()` is not graceful and `router.replace(...)` adds "/~" to the path breaking functionality across the app, I've decided to use `router.push()` instead, reloading the same page.
This updates the browser's history but since we're talking about a PWA there's no history to be accessed from the user.
This component wraps `<Layout />` and is present in every page that make use of it.
https://github.com/user-attachments/assets/46209199-ae9d-433b-8c5f-92ae9f073c6c
At the moment it's enabled also for Android, disabling its native pull-to-refresh. If we want to enable it back we can pass `android=false`
Not being a master of creativity and CSS I want to know if you'd like to see something else instead of _refreshing..._, even though I …

feat: PWA pull to refresh

---

components/dark-mode.js

`useDarkMode` wasn't listening to the DOM updates by the icon in the footer. This caused any component that uses `useDarkMode` to not get updates about the current theme. Example bug:
https://github.com/user-attachments/assets/3ba07c47-d5b1-4e9c-bb10-81dcfd034636
The footer icon does change on click correctly because it updates local state but not the state of any other component that uses `useDarkMode`.
yes
`8`. tested as seen in the video
yes, this literally fixes light and dark mode updates …

Fix missing useDarkMode update

---

components/pull-to-refresh.js

Our custom PTR is better integrated into our UI than the native PTR on Android.
This PR removes the checks to disable the custom PTR on Android so it will always be used.
I don't get a prompt on Android to install SN as a PWA. I tried Brave and Chrome and HTTPS via ngrok. :thinking: 
yes
`7`. I wasn't able to test this on Android as a PWA since for some reason, I didn't get a prompt to install. I only found "add to home screen" but that's not a PWA.
But when I set `isPWA` to `true` manually, it worked and the native PTR wasn't shown so I think this should work in the Android PWA.
**For frontend changes: …

Always use custom PTR on Android

---

api/paidAction/index.js
api/paidAction/receive.js
worker/paidAction.js

In #1570, `sybilFeePercent` was removed from the context. This broke zaps with fee credits because `sybilFeePercent` was now undefined.
`sybilFeePercent` is now always included in any action context. 
yes
`6`. I tested zaps with fee credits and pessimistic zaps via anon.
n/a
no

Fix 'Cannot mix BigInt and other types' on zaps

---

components/use-indexeddb.js
pages/settings/wallets/[wallet].js
prisma/migrations/20241119210957_optional_recv/migration.sql
prisma/schema.prisma

fixes #1611 
fixes #1612 
This also makes the wallets have the right colored images based on light/dark mode.

Wallet fixes

---

api/paidAction/lib/item.js
worker/paidAction.js

If we're running an item creation pessimistically, the worker didn't include `models` in the context when calling `performPessimisticAction`. If the text included a mention, the query to fetch the mentioned users would then fail.
https://github.com/user-attachments/assets/480ae087-8868-4c2f-b74b-b77e3ed852d6
yes
`5`. Anon can now mention stackers.
n/a
no

Fix mentions for pessimistic actions

---

pages/api/auth/[...nextauth].js
pages/api/graphql.js

Fix #1613 
If we switched to anon and used credentials for an account that was already added to the `muti_auth` cookies during `login`, we didn't switch to it since we returned before we would do that after the duplicate check. This is fixed by changing the order between the user switch and duplicate check.
If we did the same but with new credentials, `getToken()` wasn't aware that we switched to anon. This is fixed by calling the middleware that updates the session cookie according to our multi_auth cookies.
Existing credentials:
https://github.com/user-attachments/assets/db1711ac-147d-42da-ac78-19488c00c749
New credentials:
https://github.com/user-attachments/assets/be2c37ae-132c-42c7-be4f-a6c382784dd8
yes
**On a scale of …

Fix account switching anon login

---

components/file-upload.js

Fixes #1616 
Safari seems to need a 'bump' to load the uploaded element when it's a video
Added `element.load()` in `components/file-upload.js`
https://github.com/user-attachments/assets/e9b3efa1-b389-46bf-a71d-e11aa14b61bc
I don't think there's much to it, this only reminds Safari to load the element
**Are your changes backwards compatible? Please answer below:** It shouldn't compromise usual behavior
7, I don't have an Android but I tested it on Firefox and Safari
**For frontend changes: Tested on mobile, light and dark mode? Please answer below:** Yes, tested mainly in Safari …

fix can't upload mp4 on safari

---

wallets/server.js

If the wallet failed to create an invoice, we couldn't pass any `bolt11` to `logger.error` so `context.status` wasn't set. This meant this log message is ignored by the status indicators.
This PR fixes that by passing  `{ status: true }` manually to the call.
The idea behind `context.status` to control which log message should affect status is to prevent simply saving your wallet to make your wallet become green again. Only errors during sending and receiving should affect the status.
kind of
`7`. Didn't test but change is trivial so I am confident this is good to ship.
**For frontend changes: Tested on …

Fix wallet status ignoring failed requests to create invoices

---

api/paidAction/index.js
api/paidAction/receive.js
pages/api/lnurlp/[username]/pay.js

The nip57 job relies on the dbInvoice desc field to get the metadata it needs to publish the zap receipts
```js
const desc = JSON.parse(inv.desc)
const ptag = desc.tags.filter(t => t?.length >= 2 && t[0] === 'p')[0]
const etag = desc.tags.filter(t => t?.length >= 2 && t[0] === 'e')[0]
const atag = desc.tags.filter(t => t?.length >= 2 && t[0] === 'a')[0]
const relays = desc.tags.find(t => t?.length >= 2 && t[0] === 'relays').slice(1)
```
however at some point there must have been a regression that caused this link to be broken, since this field is not being used anymore.
This PR adds an optional `internalDescription` context field that when passes is used to set the dbInvoice.desc field (that could be different than the servedInvoice.description field due to privacy settings).
This is an …

HOTFIX: restore missing link between lnurlp and nip57

---

api/typeDefs/wallet.js
components/countdown.js
components/invoice.js
components/payment.js
fragments/wallet.js
prisma/migrations/20241122041724_invoice_cancelled_at/migration.sql
prisma/schema.prisma
worker/paidAction.js
worker/wallet.js

If an invoice expires, LND emits a new invoice update event with `is_canceled` set. We use that event in `checkInvoice` to mark the invoice as cancelled in our database.
However, this means that we can't really tell if an invoice was canceled because it expired or because it was actually canceled by the user. For LND, this makes no difference, but imo, this makes a difference in our UI because QR codes change their state from "expired" to "cancelled".
I think this state change is bad UX. If the user didn't cancel the invoice themselves (by closing the modal), the status should stay at expired and the modal should not close.
I fixed this by adding a new column `Invoice.cancelledAt` so we can now check `invoice.expiresAt < invoice.cancelledAt`. If this is true, we know the invoice was …

Use invoice.cancelledAt to determine if invoice expired or was canceled by user

---

wallets/wrap.js

Unless there is a reason to hide this info, imo it helps with debugging p2p failures a little bit.

log how high are estimated fees when too high

---

wallets/lnc/ATTACH.md
wallets/lnc/client.js

It seems the import broke at some point. This PR makes the LNC attachment  """"work"""" again.
Also, the doc needed a refresh after the sndev refactoring.

fix LNC attachment and docs

---

components/wallet-card.js
components/wallet-image.js
pages/settings/wallets/[wallet].js
wallets/index.js

`useWallets` is a more appropriate location to check which image we should use.
yes
`8`. The correct image is still used in light and dark mode.

refactor: Check darkmode in useWallets

---

components/wallet-card.js
components/wallet-status.js
components/wallet-support.js
wallets/common.js
wallets/index.js

I noticed this
> It's also going to be tempting to start making useWallets a monolith again, but that's part of what made the code so buggy. Meaning, it's going to be convenient to push all code into useWallets for anything that uses useWallets but it's going to be inconvenient to maintain.
-- https://github.com/stackernews/stacker.news/pull/1643#discussion_r1855255109
also applies to what I did in #1559. This PR removes that code from `useWallets` and moves it into their own wallet hooks.
Based on #1638, #1640
`useWalletSupport` is a bit of a ridiculous "hook" but I think it's indeed better to have it separated so we can use it only where we need it (which is only inside the `WalletCard` component).
yes
**On a scale of 1-10 …

More wallet hooks: useWalletStatus & useWalletSupport

---

api/paidAction/index.js

I have noticed that when we retry an invoice, the new invoice does not include the same `actionArgs` as the old invoice but the full old invoice. See invoice with id 294087 for example.
We currently don't use these `actionArgs` of the new invoice during a retry since we only allow retrying optimistic actions so this didn't trigger any bug.
However, in #1642, pessimistic actions also should be retriable and that's where this triggers a bug like `billingType` being undefined when I pay the new invoice to create a territory.
With the changes in this PR, retries of pessimistic actions start to work in #1642.
this doesn't fix it for old invoices but they aren't used anymore anyway
**On a scale of 1-10 how well and how have you …

Fix actionArgs of new invoice during retry

---

components/invoice.js
components/payment.js
components/qr.js
pages/invoices/[id].js

We no longer ever try to pay QR codes with attached wallets. We only show QR codes if attached wallets are unavailable or all failed.
That's why we always pass `useWallet={false}` to every `Invoice` component so we can completely remove it now.
yes
`3`. Only tested with single failed zap from LNbits and the QR code showed up. From reading the code, I am pretty sure that this doesn't break anything and simply removes dead code.
n/a
no

Remove unused useWallet from QR code component

---

api/resolvers/item.js

Adds `activeOrMine` to the 'top' sorting items query, effectively filtering boosts that are not created by the user and/or unpaid.
Fixes #1645 
Before:
After:
Boost owner context:
Nothing else!
**Are your changes backwards compatible? Please answer below:** I don't think so, it mimics 'recent' in filtering boosts as suggested by the issue ^^
8. Tested as the creator pov, the stacker pov and anon pov
**For frontend changes: Tested on mobile, light and dark mode? Please answer below:** n/a
**Did you introduce any new environment variables? If so, call them out explicitly here:** No

fix: top boosts shows others' unpaid boosts

---

components/file-upload.js
lib/constants.js

Allows H264 `video/quicktime` uploads.
This is a follow-up to the #1617 PR that fixed #1568 core problem (not being able to upload from iOS/Safari).
MOV files being containers for MPEG-4 should be supported on the majority of devices, and iOS recordings are encoded in H264 or HEVC.
**But Firefox doesn't support HEVC.[^1]**
When a video is exported in Safari or PWA, it gets transcoded into H264 automatically by iOS eliminating (at the moment) the need for dedicated transcoding. 
Since there's no way to detect a video codec without an external library and Firefox before uploading throws an error if it doesn't support the video[^2] we could assume that if an error is generated and the file is video/quicktime then it's a codec error, throwing a custom toaster error that says:
> codec might …

fix can't upload from iOS camera/mov files

---

components/wallet-logger.js

Deleting logs of a single wallet wasn't working because `wallet.sendPayment` was not defined.
yes
`8`. Deleting wallet logs of only one wallet works now.
n/a
no

Fix wallet logs delete for single wallet

---

api/paidAction/itemCreate.js

Completes #1505 
Shows an error that informs the users that their uploads have been expired (24 hours)
before:
after:
All is good! 
maybe we should disclose to users that their uploads will last 24 hours if not used.
**Are your changes backwards compatible? Please answer below:** Yes
9. Multiple file uploads, some of them deleted and some not, error is consistently correct about affected IDs.
**For frontend changes: Tested on mobile, light and dark mode? Please answer below:** n/a
**Did you introduce any new environment variables? If so, call them out explicitly here:** No

enhance: show an error when uploads are expired

---

pages/api/lnurlp/[username]/pay.js

Fixes https://github.com/stackernews/stacker.news/issues/1689
`validateSchema` and `lud18PayerDataSchema` were imported from `@/lib/format` instead of  `@/lib/validate`

Fix lud-18 validation imports

---

.env.development
docker-compose.yml

This renames `LND` to `SN_LND` and `STACKER_LND` to `LND` to match `sn_lnd` and `lnd` as the respective container names.
This already annoyed me during #1679 since "lnd" can mean the SN node or the stacker node depending on context.
I also considered to keep the `STACKER_LND` for the env vars so it's clear which node we're referring to if we ever add more nodes but then we'll have to also change the container name anyway, so I decided it's better to keep env vars simply consistent with how our containers are currently named.  
basically
`7`. Tested by making sure nodes can still pay each other's invoices: …

Use same naming scheme between ln containers and env vars

---

components/wallet-logger.js

`loadNew` always thought it is loading the first page for the first time because `latestTimestamp` was not updated by `loadMore`. This meant it always called `setHasMore` with `true`, causing the bug that can be seen in the video.
This is fixed by calling `setLogs` in `loadMore` instead of directly setting the logs state via `_setLogs`.
https://github.com/user-attachments/assets/6fb1521a-f4e7-4950-8ea7-c41d0d3bd547
yes
`6`. `loadNew` now only calls `setHasMore` during the first poll.
n/a …

Fix latest timestamp not updated

---

wallets/server.js

This changes the condition for failed forwards on the server such that client and server share the same view. 
Related to https://github.com/stackernews/stacker.news/pull/1688#issuecomment-2532805496
yes
`8`. I tested failed forwards with this change and without this change and receiver fallbacks still work.
n/a
no

Use same view about failed forwards on server and client

---

components/item-act.js
components/use-invoice.js

Fix #1707 
This excludes pending forwards from ever being considered for something by the client.
I think this is a change that should really only affect the bug regarding failed forwards and doesn't cause any regression during other payments.
Maybe the server should set a `pending` field in the invoice which the client can use to know that it shouldn't use this state to determine something about the invoice? I don't like how the client becomes more aware of individual transitions because it _might_ see them just so it can ignore them. 
yes
`7`.  Tested with failed forwards, successful forwards and no …

Fix pending forwards considered paid by client

---

components/notifications.js
worker/paidAction.js

Fix #1704 
yes
`8`. Tested successful forwards and autowithdrawals. Expected amounts are shown in notifications and wallet logs. 
n/a
no

Don't expose p2p zap receivers to routing fees

---

api/resolvers/item.js
components/use-can-edit.js
lib/constants.js
lib/item.js

Regular items were considered jobs which meant that regular items could be edited forever.
TODO:
This was reported multiple times by 0xbitcoiner already (last report [here](https://stacker.news/items/804740)) but I must have always forgotten to look into it.
yes
`9`. Regular items are no longer editable forever because no condition to bypass the edit check is true anymore.
n/a
no

Fix forever edits

---

lib/fetch.js
lib/time.js

I am a bit ambivalent about using `AbortSignal.timeout` because it looks like an unnecessary change with some risk since [MDN](https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal/timeout_static) can be wrong about browser support but wanted to propose it anyway to see what you think since it's not letting me go.
As mentioned, according to [MDN]([MDN](https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal/timeout_static)), `AbortSignal.timeout` seems to have been supported pretty well for some time. Only which error is thrown (`AbortError` vs `TimeoutError`) was changed this year which isn't something we depend on.
I also added a change that makes sure that timeout errors use "timeout after X seconds" as an error message. The default is "The operation was aborted due to …

Use AbortSignal.timeout + custom timeout error message

---

components/toast.js

For big toasts, there was padding on the left missing.
before:
after:
yes
`10`. See screenshots.
yes
no

Fix missing toast padding

---

wallets/payment.js

As mentioned in the chat, I noticed the usage of `withTimeout` to check for receiver fallbacks depends on how fast the server responds.
If the server is too slow, we will timeout before we get an invoice update which would tell us about receiver errors.
yes
`8`. Tested with the patch from #1688.
n/a
no

Fix receiver fallbacks depend on fast polls

---

api/resolvers/wallet.js
wallets/config.js
wallets/nwc/client.js
wallets/nwc/index.js
wallets/nwc/server.js

We were passing `models` and `me` into the wallet test functions. I think they were used in the past for logging but we no longer need them. 
I also removed `logger` from the NWC functions since they don't use it.
Maybe I am overdoing it with small PRs but it's nice to get small changes out of the way so I can focus on the relevant stuff in #1558.
yes
`5`. I looked at all `testSendPayment` and `testCreateInvoice` function signatures and saw none of them use these arguments.
Regarding removal of `logger`: removing an unused argument doesn't break any function calls in JS since you can always call a function …

Remove unused wallet context args

---

wallets/blink/client.js
wallets/blink/common.js
wallets/blink/server.js

For #1722, I need to pass `signal` as a context to the Blink wallet functions. To make this easier and consistent with how other wallets are implemented, I changed the function signatures to match the common `[bolt11, ] config, context` signature. 
yes
`8`. Tested by attaching Blink send+recv:
https://github.com/user-attachments/assets/57e6f7dd-838b-43ab-a998-2a212e1146fd
I also attempted a zap and got the expected error (insufficient balance).
n/a …

Refactor Blink function signatures

---

components/wallet-logger.js

The lightning address wallet has `shortName` set so we need to use `walletTag` to filter the wallet out of logs since that we use `walletTag` inside logs.
yes
`8`. Simple change
n/a
no

Fix lightning address logs deletion

---

lib/nostr.js
wallets/nwc/client.js
wallets/nwc/index.js
wallets/nwc/server.js

In an attempt to fix relay issues, we're opening and closing relay connections after each nwc call. This is the same behavior as before we switched to NDK in #1590.
As @riccardobl mentioned in the chat, it probably makes sense to keep the relay connections open on the server which this code doesn't do (yet). However, the previous code also didn't do that.
yes
tbd, will test more tomorrow
n/a
no

Close relay connections after each NWC call

---

components/nostr-auth.js
components/use-crossposter.js
lib/nostr.js
wallets/nwc/index.js
worker/nostr.js

This PR 
-  fixes nostr logins and crossposts: Closes #1741 
- and refines  #1739 by:
- moving the close method inside the nostr class
- adding static method to return the ndk singleton
- disconnecting from the relay after crosspost on the client

Refine #1739 and fix regression causing nostr crossposts and login to not work

---

api/resolvers/wallet.js

_Using NWC as the example wallet here._
If you have a NWC send-only config for a wallet and then enable device sync, the mutation in `syncLocalWallets` only creates a row in `Wallet` and `VaultEntry` but not in `WalletNWC`.
If you then try to save again, the backend will see that there is a row for the wallet in `Wallet` and will try to update `WalletNWC`. This fails because there was no such row created during sync to server. 
This PR fixes this by always creating a row in `WalletNWC` if `Wallet` was created.
---
update: Okay, this breaks WebLN though as the comment `// client only wallets has no walletData` indicated why there was this check for existing wallet data. Added as TODO.
Maybe the fix is to also pass an empty receive config during local sync since that's what we also do on …

Fix send-only wallet save after device sync enabled

---

docker-compose.yml

As suggested in  https://github.com/stackernews/stacker.news/issues/1733, I have separated the wallets crons from the payments crons using the custom label ofelia.group and two lists of depends_on. This successfully separates the crons; however, it doesn't seem to fully resolve the issue. CLN still does not automatically reconnect to the peer when it restarts unless forced to do so. To address this, I modified row 561 to make it reconnect in the cron job.
Closes https://github.com/stackernews/stacker.news/issues/1733

add ofelia cron for wallets and force cln to reconnect

---

components/boost-button.js
components/upvote.module.css

I tried to find the changes that broke this to have full context and see if I am missing something but I can't tell.
Using `git blame` on components/upvote.module.css (because that's where I fixed it) shows 5f0494de3 but I don't think this was broken since we shipped #1408.
Using `git log -G "deletedAt"` I find following commits but from looking into them, I also can't tell which one broke it:
```
$ git log --oneline --no-decorate -G "deletedAt" -10
6d9db696 Fix upvote button shown for deleted items
b8061a63 don't double factor trust
6d4dfdda improve rewards (#1731)
01d51770 Fix edit timer stuck at 00:00 (#1673)
8a2bd84f fix: upvote widget not rendered when comment is collapsed (#1583)
fdd34b2e Fix edit countdown on deleted items (#1571)
9f06fd65 UX latency enhancements for paid actions …
```

Fix upvote button shown for deleted items

---

components/territory-form.js
lib/constants.js
prisma/migrations/20241223204948_territory_refund/migration.sql

This reduces monthly and yearly territory prices by half. It also refunds active territory owners for what they "overpaid" for what remains of their billing period.
QA: `8`. I ran the CTE in prod to verify it produces the right values. Locally, I created a new territory with monthly billing, upgraded to yearly, and manually made it enter into grace period - verifying new prices are used. I also manually made the territory 6 months into a yearly billing cycle with a `billingCost = 1m` then ran the migration, verifying I received a refund of ~250k sats.

reduce territory price with prorated refund for actives

---

components/item-act.js

I'm running out of less severe changes to fix this bug. I describe the problem in #1695 some, but the gist is:
1. a thread is cached on the client
2. someone replies to us in that thread and we get a notification 
3. we zap the item in notifications and the optimistic response updates all of an item's ancestors in the cache
4. on navigation, we use `writeQuery` to merge SSR data with the cache
5. `writeQuery` does not support merging into optimistic caches, so until the real response returns, the stale optimistic cache (which does not yet have the item in the thread) is shown 
(I should note this happens in more places than just notifications, so doing a hack checking the pathname is especially not worth it.)
This fixes the problem by avoiding a need to merge the ancestors in the thread. …

fix 1695 by not updating ancestors on zap

---

components/bookmark.js
components/comment-edit.js
components/delete.js
components/dont-link-this.js
components/item-act.js
components/pay-bounty.js
components/poll.js
components/reply.js
components/subscribe.js
components/use-item-submit.js

My theory as to why #1655 and #1669 occur is that an earlier and conflicting optimistic mutation fails while another optimistic mutation is in progress. When the optimistic mutation fails, it rolls back the cache to its initial state which causes the in-progress optimistic mutation to have its cache updates overwritten.
In the case of #1655, I believe that this occurs when an earlier zap (in a succession of zaps) fails. In the case of #1669, I believe this occurs when a poll is zapped, then voted on.
I've made the relevant cache updates write to each other. It's very hard to reproduce so I'm not sure I got all the relevant `cache.modify` calls, but I'll continue looking for any cache updates on the optimistic response path in the few places we do it (zaps/boosts/polls) ... it's unclear if …

make possibly conflicting optimistic cache updates write to each other

---

api/paidAction/inviteGift.js
api/typeDefs/invite.js
lib/validate.js
pages/invites/index.js

The frontend says `invite limit` is optional but if you don't enter anything and submit, we throw 
> Variable "$limit" got invalid value ""; Int cannot represent non-integer value: ""
I believe this has been an issue even before #1649 since the validation schema was not changed in #1649 and I had to update it to use `.nullable()`.
Additionally, our code checked if `invite.limit` was defined everywhere except in the most critical part where it gets redeemed, lol.
yes
`6`. Testing creating and redeeming limited and unlimited invite links.
**For frontend changes: Tested on mobile, light and dark mode? Please …

Require invite limit

---

api/paidAction/itemCreate.js
prisma/migrations/20241220000308_fix_duplicate_comments/migration.sql

Fix #1693 
Instead of a unique index, I used an exclusion constraint so we can specifically target duplicates within 10 minutes.
Some things I noticed during implementation:
1. A naive unique index doesn't work because the `text` column is too large for the index row so I am using `digest("text", 'sha256')`:
```sql
CREATE UNIQUE INDEX IF NOT EXISTS "Item_unique_time_constraint_idx"
ON "Item"("userId", "parentId", "title", "text", "subName");
ERROR:  index row requires 8432 bytes, maximum size is 8191
```
2. We need to make sure that NULL is considered equal via [`NULLS NOT DISTINCT`](https://www.postgresql.org/docs/16/indexes-unique.html):
```sql
CREATE UNIQUE INDEX IF NOT EXISTS "Item_unique_time_constraint_idx"
ON "Item"("userId", "parentId", "title", digest("text", 'sha256'), …
```

Add exclusion constraint to prevent duplicate items within 10m

---

api/resolvers/user.js

Noticed [here](https://stacker.news/bitcoin_wallets) that if the first item wasn't paid, we still show it next to `stacking since`.
This changes the query for `user.since` to use the same filter we use elsewhere to filter out unpaid items.
yes
`3`. Tested with unpaid first item.
n/a
no

Fix user since if first item wasn't paid

---

sndev

Since a Next.js update, the dev environment has started logging HTTP requests, which has caused the logs to become cluttered with logs of POST /api/graphql requests. This is an actual issue of  Next.js, see the related discussion here: https://github.com/vercel/next.js/discussions/65992.
This PR adds a workaround to filter out these logs by using grep in the sndev logs command.
before / after

filter out POST /api/graphql spam from sndev logs

---

pages/settings/index.js

The modal that is opened when one wants to link a nostr key always showed `Unlink`
yes
`10`
n/a
no

Fix NostrAuth link text

---

components/comment.js

This fixes #1706 by populating a new context for query params with the full comment so we can use `comment.path` to uncollapse all parents.
https://github.com/user-attachments/assets/1097e4e9-729d-4d3b-8abf-0031aa2d1e89
I named this new context `QueryParamsContext` since I struggled with a better name and we might want to use this for other stuff at some point even though I currently lack the imagination for what. Open for better naming ideas.
yes
`5`. See video. Also made sure in 91645e1e that if one navigates back and then forward again, the thread is still uncollapsed by storing the state in local …

Fix muted parents not uncollapsed

---

pages/api/auth/[...nextauth].js

As @riccardobl mentioned in #1781, #1779 is caused by the cookie pointer update in `pubkeyAuth` getting overridden back to the initial cookie pointer in the JWT callback.
As I mentioned in https://github.com/stackernews/stacker.news/issues/1779#issuecomment-2565585659, I thought I fixed  this in #1618 but it appears that I didn't really test all cases, but only the case when we switched to anon and then try to add a new account. Then we automatically get switched because the JWT callback will run with the token set to the new user since we return the new user token (the variable that is called `user`) in `pubkeyAuth`, not the old user token (the variable that is called `token`).
However, as noticed in #1779, this does not work if you're logged in as some account and then add an account …

Always return new user token for JWT callback to use

---

components/use-qr-payment.js

If an invoice cancel fails, we currently only log the error and return `undefined` and then throw in the constructor of `InvoiceCanceledError` because `invoice` is undefined. This results in an uncaught `Unhandled Runtime Error`.
This change doesn't change that cancel errors result in an unhandled runtime error, but it will at least show the proper error.
[According to NextJS docs](https://nextjs.org/docs/pages/building-your-application/configuring/error-handling#handling-errors-in-development), these unhandled runtime errors don't show up in prod. I assume they just get logged to console but don't crash the app? Not sure though.
But anyway, so far we never had an invoice cancel fail and this is just about throwing the actual error.
**Are your changes backwards compatible? Please answer …

Fix ignored cancel error

---

components/comment.js

Collapses the comment if it has `deletedAt` and no child comments, closes #363 
n/a
**Are your changes backwards compatible? Please answer below:** 
Yes, it's an addition to default collapse conditions
8, found correct behavior: if no childs, collapse.
**For frontend changes: Tested on mobile, light and dark mode? Please answer below:** n/a
**Did you introduce any new environment variables? If so, call them out explicitly here:** No

collapse childless deleted comments

---

api/resolvers/wallet.js
api/typeDefs/wallet.js
components/use-invoice.js
fragments/wallet.js

Required for #1776.
Since we only return hmacs when the invoice is created, stackers need to be able to cancel their invoices even if they don't contain an hmac anymore for #1776.
TODO:
https://github.com/user-attachments/assets/7377757f-634b-4eed-99c1-d7ac190362c7
yes
`8`. Tested anon cancels via hmac and stacker cancel without hmac, see video.
n/a
no

Allow cancel of own invoices without hmac

---

api/resolvers/wallet.js
api/typeDefs/wallet.js
components/use-invoice.js
components/use-qr-payment.js
fragments/wallet.js
prisma/migrations/20241231223214_invoice_user_cancel/migration.sql
prisma/schema.prisma

Requirement for #1776 
This adds a boolean column `Invoice.userCancel`. It is set if the invoice was cancelled by the user, i.e. the invoice was shown to the user via a QR code and they closed it. In any other case, it is not set.
I also added a constraint so cancelled invoices cannot be in a weird state where it's not clear if it has been cancelled and how.
https://github.com/user-attachments/assets/37de1f5b-db26-4dd0-9225-f281f9ad2932
I decided to use a trigger to set `userCancel` to false by default if it was not specified in the same call as `cancelled` and `cancelledAt` are set.
Yes, old rows are migrated by setting `userCancel` to false. I also checked that there are no existing rows that would fail the new constraint: …

Distinguish invoices cancelled by user

---

api/paidAction/boost.js
api/paidAction/index.js
api/paidAction/itemCreate.js
api/paidAction/itemUpdate.js
api/paidAction/lib/item.js
prisma/migrations/20250103011357_fix_expireboost_keepuntil/migration.sql

We've been using `expirein` for reminder, delete and boost jobs far into the future. We thought `expirein > startafter` would make sure they don't disappear before they get run. However, `expirein` is for how long a job can stay in the **active state**:
> **Expiration options**
>
> - expireInSeconds, number
>  How many seconds a job may be in active state before it is failed because of expiration. Must be >=1
-- https://timgit.github.io/pg-boss/#/./api/jobs
The docs aren't clear, but I assume `keepuntil` is called "Retention options" in the docs and they state this:
> **Retention options**
>
> - retentionSeconds, number
>  How many seconds a job may be in created or retry state before it's archived. Must be >=1
So we want to use `keepuntil` instead of `expirein` for reminder, delete and …

Fix expirein used instead of keepuntil

---

prisma/migrations/20250103150109_fix_invite_cuid_insecure/migration.sql
prisma/schema.prisma

`cuid` has been deprecated due to security, see [README](https://github.com/paralleldrive/cuid).
`cuid2` is now recommended but when I tried to use `cuid(2)` as the default in our Prisma schema as mentioned in the [Prisma docs](https://www.prisma.io/docs/orm/reference/prisma-schema-reference#cuid), it didn't work.
```
Error: Prisma schema validation - (validate wasm)
Error code: P1012
error: Error parsing attribute "@default": The `cuid` function does not take any argument. Consider changing this default to `cuid()`.
-->  prisma/schema.prisma:470
|
469 | model Invite {
470 |   id          String   @id @default(cuid(2))
|
Validation Error Count: 1
[Context: validate]
Prisma CLI Version : 5.20.0
```
Since Prisma is pretty weird anyway and I have more trust in `pgcrypto`, I decided to use …

Fix insecure default id for invites

---

components/modal.js

This fixes this:
https://github.com/user-attachments/assets/c49513c1-6091-4708-87d4-de778d076353
I identified that the issue is that the text input does not lose focus by opening a modal, at least on Safari iOS.
https://github.com/user-attachments/assets/50ec907a-8966-41ec-b9b5-68ba987c7ab6
yes
`8`. See video.
n/a
no

Fix scroll after modal close

---

components/serviceworker.js
sw/eventListener.js

Partial fix of #756, 2: (notification counts and sums)
This PR provides immediate relief for iOS users, specifically fixes iOS check to enable ek's fix (`initialValue = 1`) giving proper counting and sums on all notifications
`os` value is not updated between events, this fix reliably saves and gets the OS value to/from `ServiceWorkerStorage`
AMOUNT counts
SUM_SATS sums
This is part of a series of fixes tracked on #1794 
Yes
9, didn't test `FOLLOW` but it follows (heh) the same counting method as others, tested also with withdraw/deposit sums
**For frontend changes: Tested on mobile, light and dark mode? …

fix: iOS notification counts and sums are wacky

---

components/pay-bounty.js

https://github.com/stackernews/stacker.news/issues/1803 for bounties

add hasSendWallet to pay bounty

---

api/resolvers/item.js

Fix #1807 
Issue was that we destructured `subName` from `item` so `item.subName` was undefined.
Decided to simply pass `old` as the item to `isJob`.
yes
`6`. Made sure `isJob` now returns `true` for job edits.
n/a
no

Fix job edits

---

components/item-info.js
components/item.module.css

I think this:
looks better than this:
On mobile:

Use sats / ccs format in item details

---

api/paidAction/zap.js

Fixes #1809
Checks if there are new ItemActs before triggering notifyZapped, avoiding duplicate notifications
n/a
Yes
7, sent a lot of zaps really really fast!
n/a
No

fix: zapping too fast causes duplicate notifications

---

components/info/cc.js
components/info/index.js
components/info/reward-sats.js
components/notifications.js
pages/credits.js

These will just show up in `/credits` and zap notifications as in `Info` icon.
In another PR, I'll add a denormalized column in `users` that determines if a stacker has a wallet attached, and we can display a more prominent message with their CC zap notifications.

cowboy credit modal explainers wherever they are referenced

---

components/info/cc.js
prisma/migrations/20250113233026_weekly_posts_update/migration.sql
prisma/migrations/20250113235235_daily_rewards_refill_job/migration.sql
worker/earn.js
worker/index.js
worker/weeklyPosts.js

Each commit is pretty much its own change. Figure it was easier to review/merge as a package.
Changes:
- typo fix
- bot bounty changes
- explicitly state CCs
- reduce to 5k
- move meme bounty to ~memes (and support `weeklyPosts` jobs being in other territories)
- automate daily rewards
- add new job trigger every day 10 minutes after midnight to deduct and donate CCs from `@sn` 
QA: 7. I triggered all the weekly posts to confirm the changes worked and reviewed `pgboss.schedule`. For the daily rewards refill, I manually trigger it and it worked.

bounty updates and auto-rewards refill

---

wallets/wrap.js

Node runners with a private channel to SN can not receive 1 sat payments because the forward limit is set to 900 msats but we deduct 30% instead of 10% from each zap since a while.
it should probably say "incoming payment: 700 msats" instead of rounding to 0 sats for amounts < 1 sat.
yes
`0`. Did not test but change looks good to me
n/a
no

Update forward limits

---

scripts/welcome.js

This is what I will use for my next post to welcome new stackers.
It uses the API to fetch the recent bios and print out the markdown table + row count.
I noticed that `when` is not supported if you sort by recent. If it were, this would make the filter step obsolete.

Script for welcome series

---

wallets/server.js

This warning has been confusing for many stackers. I think we should remove it since there's nothing one can do and it's not very relevant.
It's nice to make them aware that they are missing out on some msats for each zap, but I think the logs aren't the place for it. Maybe in some other form in the future.

Remove msats warning

---

lib/webPush.js

Fixes #1819 
Adds a condition to the `notifyUserSubscribers`' query, ensuring that a push notification is not sent if the subscribed user has posted in a territory the recipient is subscribed to, avoiding duplicate notifications.
before:
after:
n/a
Yes
9, tested with userA and userB, the latter creating an Item in a territory user A is subscribed to
n/a
No

fix: duplicate push notification on subscribed user and territory

---

api/paidAction/territoryUnarchive.js

Fixes #1790 
Simple transaction to subscribe the user to the territory they unarchived.
n/a
n/a
Yes, just adds a transaction
7, unarchived a territory and got subscribed to it
n/a
No

Subscribe unarchiver to unarchived territory

---

components/item-info.js

Fixes #1692
Removes `!item.position` from downzap condition allowing downzapping on pinned posts
Downzappable
After downzapping
n/a
Yes
7, tested on pinned posts without sub and with sub
n/a
No

fix: allow downzapping of pinned posts

---

api/paidAction/itemCreate.js
lib/webPush.js

I subscribed to a post and I expected to receive push notifications but I didn't because we don't send any.
Turns out we likely never had push notifications for thread subscriptions afaict. At least I couldn't find a commit where we had them using `git log -S "ThreadSubscription"`.
This PR adds push notifications for these. It sends the same push notification as if you subscribed to the user that replied to the post you subscribed to because that's the same notification format I was going for.
It also makes sure that you only receive push notifications for stuff you would also find in your notifications by considering `users."noteAllDescendants"`:
push notifications:
```sql
-- send notifications for all levels?
AND CASE WHEN users."noteAllDescendants" THEN TRUE ELSE r.level = 1 END
``` …

Fix missing push notifications for thread subscriptions

---

wallets/cln/index.js

Fix #1846 
the line break for the v24.11+ command looks bad
yes
`7`. Tested both commands myself.
no

Add createrune info for v24.11

---

components/header.module.css
components/price.js
styles/globals.scss

Accessibility changes to price button to ensure that the `button` role is being used and the `aria-describedby` announces the correct hint for when the user activates the button.
No changes to visual UI
This is my first commit. I plan on doing more accessibility work for stacker.news in the future but wanted to start small to ensure I am in sync with your contribution process. 
This PR simply changes a few lines on prices.js to ensure the price element is announced as a `button` to screen reader users with the proper `aria-describedby` which describes the next action the button will perform and that it is focusable and actionable by the keyboard. 
I believe so. These are very small changes that should not impact backwards …

Update price button accessibility in header

---

components/comment.js

To outline a comment again, we add the class `outline-it`. However, if the comment was already outlined before, this doesn't work.
This PR fixes it by removing the class after the animation ended so we can add it again.
https://github.com/user-attachments/assets/e5932cc7-8237-4077-84e0-fc639835f45d
There is another bug that a comment with its id already in the query param can't be outlined again since the corresponding `useEffect` is not triggered. Will fix in another PR.
yes
`7`. Simple change + [`once`](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#browser_compatibility) …

Fix comment not outlined again

---

lib/rehype-sn.js

Fix #1898
Currently, SN will render this:
```
asdf@foobar
[](url)
```
like this:
```
asdf
```
This is fixed by preventing any parsing inside code blocks.
If you run `console.log(tree)` before `visit` is called, you still get the processed tree printed to console. I think that's because the tree is processed inline and the console will show the latest state of an object.
Therefore, I used `console.log(JSON.stringify(tree, null, 2))` to see the unprocessed tree in the console.
If you mean there's no regression, I think so, yes.
~`3`. Only tested the code block in the description but not processing anything …

Don't parse content in code blocks

---

lib/rehype-sn.js
lib/url.js
lib/url.spec.js

Fix/address issue https://github.com/stackernews/stacker.news/issues/323
Currently, `isMisleadingLink` in `lib/rehype-sn.js` checks whether links are misleading by comparing the link text to the href. If the link text is URL-like (contains letters, numbers, underscores, and dots), the function adds `http://` to the link-text and then checks whether the URL's origin has the same origin as href.
The issue is that if the link text contains other characters, like `:` or `/`, which are common in URLs, `isMisleadingLink` will return false (doesn't identify the link as misleading). This PR fixes the issue by checking if the link text is any valid URL. If it is, it compares the origin of the link text to that of the href, and if the two are different, `isMisleadingLink` will return true (is …

Fix the check for misleading links

---

api/paidAction/index.js
wallets/server.js
worker/autowithdraw.js

Our loop over receiver wallets is setup in a way that if anything fails after we created the invoice, we will not try the next wallet since we already exited the loop.
This affects p2p zaps, direct payments and autowithdrawals.
This PR fixes this by making the caller aware of the loop via an [async generator function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/AsyncGenerator). This means the caller can continue the loop on any errors.
This is the first time we use generators in our codebase, but I think this is a very good use case for generators.
bug + fix for p2p zaps:
https://github.com/user-attachments/assets/bbe40c6e-6032-4fbb-b95b-300fdeb6f9e9
bug + fix for direct payments:
https://github.com/user-attachments/assets/2aa644f7-cce3-4c2d-87d9-5b8e11 …

Fix receiver fallback on caller error

---

components/text.js

Fixes #1242 
Dynamically imports React Syntax Highlighter and uses the correct theme for the highlight.js based highlighter
This moves a fair bit of `react-syntax-highlighter` stuff that was present inside the `_app` bundle and by dynamically importing the highlight.js based highlighter we can highlight stuff again while preventing over 0.7~1.5 MB of base bundle growth.[^1]
To avoid disrupting the already established Markdown parser, `Code` dynamically imports libraries when called instead of dynamically importing `Code` itself
Noting that #1606 seems to have an alternative package that is much smaller than `r-s-h` that imports 1.5 MB of highlight.js
Yes
**On a scale of 1-10 how well and how have you QA'd this change and any …

fix: Dynamically import React Syntax Highlighter

---

components/text.js

Addresses #1832 
Dynamically imports MathJax whenever is needed. Checks for `$$some math$$` inside the text to be processed and loads MathJax when positive.
It created two chunks containing MathJax-full and MathJax's LaTeX font, configuring a 1.5MB download client-side when is needed.
I noticed that on Math blocks we load Code. I added a condition for React Syntax Highlighter that catches 'math' language and avoids loading the library since MathJax should handle math.
Yes
7, loads MathJax only on "$$math$$" and displays correctly, conditional rendering is also correct. RSH avoidance works correctly.
**For …

Dynamically import MathJax

---

pages/email.js

Emails are stored in lower-case and the verification is case-sensitive.
This PR converts the email address saved in session storage to lower case at the time of callbackUrl building, preventing unexpected login errors.
Code-entering page displays the email inserted by the user as-is to maintain the email as expected by the user, this fix operates behind the scenes
Yes
7, inserted all types of emails, as long as the email is correct whether UPPERCASE or lowercase it can't give an error.
n/a …

hotfix: Email addresses should be case insensitive

---

components/form.js
components/text.js
pages/withdraw.js

Addresses #1832
Dynamically loads React QR Scanner, React Datepicker with a loading placeholder.
It uses Next.js handling of dynamic loading instead of a state-based solution like we saw with syntax highlighting and MathJax
QR Scanner + loading:
React Datepicker + loading:
<video width="300" src="https://github.com/user-attachments/assets/ee16aa33-6c1a-4085-b080-60db9714f676">
Also React Syntax Highlighter + loading:
<video src="https://github.com/user-attachments/assets/603226e9-7838-4408-99de-19b11104ea57">
MathJax is not being considered for a loading placeholder for the fact that it's a plugin and not a component
Yes
**On a scale of 1-10 how well and how have you QA'd this change and any features it might affect? Please …

Dynamic loading optimizations

---

lib/url.js

Added a leading slash to the regular expression matching for nostr links, so the prefixes only match if preceded by a slash.
Tested that the changes fixes the issue.
Tested that nostr links still match.
I don't know all other sites that use nostr prefixes in their URLs, though.

Fix issue #1924, require nostr prefixes start with slash

---

.github/workflows/extend-awards.yml
extend-awards.py

Implements #1849
Adds a github action that is triggered on PR merge events, running a script that finds the relevant PR and associated issue.
It calculates the awards due to the PR and issue authors based on the issue tags and difficulty/priority rules. If needed, it adds lines to awards.csv and opens a PR for this change.
The action uses [Create Pull Request](https://github.com/marketplace/actions/create-pull-request) to create PRs, which requires access rights to the repository configured under Settings / Actions / General / Workflow permissions:

Add a github action that extends awards.csv on PR merges

---

.github/workflows/extend-awards.yml
docs/dev/extend-awards.md
extend-awards.py

Implements #1849
Pass ${{ github }} through env var GITHUB_CONTEXT to the script instead of passing it on the command line.
Tested with various PR body texts (backticks, single quotes, double quote, new lines, unicode, etc.) and multiple PR merge methods (squash, merge, etc.).

Extend awards action

---

components/text.js

If you click on a footnote in a long post before you click `show full text`, the button disappears but the text is still contained:
https://github.com/user-attachments/assets/9df6a5ce-f842-4836-a8fb-3b65ae899b9a
However, this also happens if you clicked `show full text`. In that case, the text is contained again.
**Steps to reproduce**
1. Go to https://stacker.news/items/400430
2. Click on first footnote
The fix is to remove code that was added in cc4bbf99e47862a4924510a5806c7f314ddd8854 and explicitly checks for the `#itemfn-` prefix. This looks like the code was added to fix something. But I couldn't tell what that would be. Why wouldn't we want to show the full text if we're navigating to a footnote? Wouldn't we want to handle it like clicking on a chapter? :thinking: 
**Are your …

Fix footnotes and overflow

---

pages/api/auth/[...nextauth].js

While reviewing #1904, I noticed checking `req && res` to detect if it's a login is weird. Not sure why I did that since `next-auth` already gives us a way to detect logins:
> The arguments _user_, _account_, _profile_ and _isNewUser_ are only passed the first time this callback is called on a new session, after the user signs in. In subsequent calls, only `token` will be available.
-- https://next-auth.js.org/configuration/callbacks#jwt-callback
So I moved the code into the existing `if (user)` block and tested that we can still:
1. login
2. add a new account
3. logout (until full logout)
Authentication is critical piece of code so to keep the `if (req && res)` check might make sense but `req` is definitely set (we also access it above) so I only added `if (res)`. `res` should also …

Also check for `user` before setting multi auth cookies

---

docs/dev/semantic-search.md

Resolves https://github.com/stackernews/stacker.news/issues/1951
Adds additional notes for configuring semantic search for the first time in a dev environment.
yes
9... the instructions work on my machine, anyway.
n/a
no

Update semantic search documentation

---

api/resolvers/admin.js

I thought @huumn forgot to enable the SNL banner but I just had to refresh my page.
I think this is still a good idea.
QA: `9`. Tested that non-admins cannot toggle and tested that admins can with this patch and inserting a row into the `Snl` table:
```diff
diff --git a/lib/constants.js b/lib/constants.js
index a2feb4df..d904b291 100644
--- a/lib/constants.js
+++ b/lib/constants.js
@@ -62,9 +62,10 @@ export const USER_ID = {
anon: 27,
ad: 9,
delete: 106,
-  saloon: 17226
+  saloon: 17226,
+  test01: 21858
}
-export const SN_ADMIN_IDS = [USER_ID.k00b, USER_ID.ek, USER_ID.sn]
+export const SN_ADMIN_IDS = [USER_ID.k00b, USER_ID.ek, USER_ID.sn, USER_ID.test01]
export const SN_NO_REWARDS_IDS = [USER_ID.anon, USER_ID.sn, USER_ID.saloon]
export const MAX_POLL_NUM_CHOICES = 10
export const …
```

Allow any admin to toggle SNL banner

---

pages/api/auth/[...nextauth].js
pages/api/graphql.js

It confused me why I wrapped `req` and `res` with `NodeNextRequest` and `NodeNextResponse` even though it wasn't needed.
It's only needed when one wants to access parsed cookies via `request.cookies` else they are just available as a string under `request.headers.cookie`.
yes
`7`. Tested email login, adding a nostr account and switching between users and anon.
n/a
no

Remove unnecessary wrapping with NodeNext(Request|Response)

---

scripts/welcome.js

https://stacker.news/items/904090
I originally wanted to use `limit: 9999` but then our API returns 400 Bad Request for some reason:
```gql
query UserItems {
items(sort: "user", name: "bxu", type: "all", limit: 9999) {
items {
id
createdAt
sats
credits
}
}
}
```
```json
{
"errors": [
{
"message": "code=maximum",
"locations": [
{
"line": 2,
"column": 56
}
],
"extensions": {
"code": "GRAPHQL_VALIDATION_FAILED"
}
}
]
}
```

Fix fetching of user items in welcome script

---

api/paidAction/itemCreate.js
fragments/items.js

Fix https://stacker.news/items/909192?commentId=909224
As @huumn guessed, the issue was that Prisma can't join on `CITEXT` in a case-insensitive way, see https://github.com/prisma/prisma/issues/14935.
To fix that, I fetch the territory in a separate query now.
https://github.com/user-attachments/assets/cf44c2ed-9585-41c1-af45-3811510a666e
Apparently, [we could also just use the preview feature `relationJoins`](https://www.prisma.io/docs/orm/prisma-client/queries/relation-queries#relation-load-strategies-preview), but I don't think we want to trust Prisma with preview features.
yes
`7`. See video.
**For …

Fix item cost in details

---

components/account.js
pages/api/next-account.js

Using /api/signout just because we use it during signout was a terrible naming choice imo. 'next-account' describes way better what this route does.

Rename to /api/next-account

---

api/paidAction/itemCreate.js

The query will return `{ replyCost: null }` if no sub was found because of the left join.
Instead of changing the query to use a inner join for the `Sub` table, I decided to check `sub?.replyCost` instead. Using a different join to keep `if (!sub)` felt wrong but not really sure why.
yes
`8`. Tested replies to items with no sub (like the saloon would be in prod) and with subs.
n/a
no

Fix saloon replies

---

prisma/migrations/20250312223725_check_reply_cost_positive/migration.sql

It made me uneasy when I saw that we don't have this check on the database. I manually updated a sub with a negative reply cost and I was able to print cowboy credits via replies.
I didn't add `NO VALID` since we don't have so many territories that we can't check them all at once.
yes
`5`. Tested replies but pretty confident this is good.
n/a
no

Add check for Sub.replyCost > 0

---

wallets/index.js

Fixes error messages in the browser console:
> failed to fetch invoices to retry: ApolloError: you must be logged in
yes
`7`. Tested by switching between anon and user.
n/a
no

Don't poll failed invoices if anon

---

lib/time.js

Our `@remindme` bot did apparently never support the `week` notation.
https://github.com/user-attachments/assets/ad0450d7-5e20-4c81-97df-86572049c9ff
`3`. Only tested `@remindme in 2 weeks` as a comment but pretty sure this is at least not a regression.
n/a
n/a

Fix @remindme does not support weeks

---

wallets/lnbits/server.js

Fix #1959
Strip trailing slashes from url, since path always starts with a slash. Similar to how client.js already does.

Support / at the end of LNbits URL

---

components/login.js

When visiting /login, the following warning was logged to the console:
```
Warning: Each child in a list should have a unique "key" prop.
```
yes
`9`. Warning is gone.
n/a
no

Fix warning about missing key for children

---

components/pull-to-refresh.js

Fixes #1985 
Shows pull-to-refresh message only when we're actually pulling
It's based on conditional styling via pullDistance
Yes
6, it doesn't show a message in odd resolutions when not pulling; vice versa it shows a message only if we're pulling
n/a
n/a

Hide pull-to-refresh when not pulling

---

pages/settings/passphrase/index.js

fix #1950
I think that we use `<textarea>` instead of `<input>` is related, see video.
I tried yesterday to get my password manager autofill to work with `<textarea>`, which is what we currently use for the device sync password input, but I am not sure it's possible even though it has `autocomplete="current-password"` and `type="password"` set. So I think we need to switch to `<input>`.
https://github.com/user-attachments/assets/c291b846-7b1d-4eaf-aed1-d5a270d215d1
Password manager autofill is also related to us wanting to switch to a dedicated input component for bip39 with separate inputs for each word: I guess with separate inputs you can't use password manager autofill 🤔
edit: or maybe it could work by using autofill on the first word input and then our code puts each word into its …

Fix no pw manager autofill for device sync password

---

components/sub-select.js
next.config.js

Closes https://github.com/stackernews/stacker.news/issues/1254
Selecting a territory while on `/top/cowboys` now sends you to `/~:sub/top/posts/day` (or stay in `top/cowboys` if home is selected). 
Redirects `/~:sub/top/cowboys` to `/top/cowboys`.
yes
9
n/a
no

Top cowboys territory selector fix

---

components/login.js
pages/api/auth/[...nextauth].js
pages/login.js
pages/signup.js

Fixes #1239 and #841 
Applies a cookie to remember the user’s choice between logging in or signing up.
NextAuth picks up this cookie for the general purpose `createUser` function used by Email and Providers (social media) authentication methods, as well as for `pubkeyAuth`, which is used by Lightning and Nostr Credentials Providers.
I first tried by passing `signup` to the signIn method, this works but not for OAuth since there are a lot of steps before landing back to the callback and every additional option is lost.
Cookies are a reliable method of persistence in this case.
Email and OAuth throws `Callback` and CredentialsProvider throws `CredentialsSignIn`, as Next Auth doesn't support custom error messages, a not invasive way to handle this is to show a vague generic message that …

Prevent new account creation on login

---

components/account.js
components/banners.js
lib/auth.js
pages/api/auth/[...nextauth].js
pages/api/graphql.js

fix #1821 based on #1956 #1974 supersedes #1904
I found out that we have a race condition on logout that exists without any account switching code: if a request starts before we receive the signout response (that deletes `next-auth.session-token`) and finishes after it, we're logged back in because it includes `next-auth.session-token` in the request headers and therefore also in the response headers thanks to the implicit token refresh on all requests.
However, I have also seen in the timings of the network tab that it's possible that a request still includes the cookie _after_ it was deleted AND _after_ we reloaded the page. This is somehow related to slow requests since this is reliably reproducible if we poll for `me` every second but sleep for 5 seconds on the server before replying. …

Reset multi_auth cookies on error

---

pages/api/auth/[...nextauth].js
pages/email.js

Updates #1976 
If we're in `signin` mode (cookie) and can't find a user with the inserted email, we resolve earlier and don't send a verification email. This works by passing `req` to `sendVerificationRequest`, this way we're able to access cookies and check for `signin`
n/a
I added some _mystery_ to the email.js message, in line with major websites behavior
Yes, we're just passing req to check the `signin` cookie
7, I can receive an email if I'm registered and I don't receive an email if I'm not registered.
n/a
**Did you …

don't send a verification email during sign in if no match

---

components/account.js

I did exactly what one shouldn't do with `onCompleted`: to use it for state syncing, see [this blog post](https://tkdodo.eu/blog/breaking-react-querys-api-on-purpose#state-syncing).
Apparently so many people were misusing `onCompleted` that it will be deprecated in the next release, see https://github.com/apollographql/apollo-client/issues/12352
There are more cases like this that one can find by searching for `onCompleted:`. Examples:
https://github.com/stackernews/stacker.news/blob/a83783f008702db5d8220e9883260511a64c2d7b/components/wallet-logger.js#L139-L141
https://github.com/stackernews/stacker.news/blob/a83783f008702db5d8220e9883260511a64c2d7b/components/form.js#L625-L633
yes
**On a scale of 1-10 how well and how have …

Fix useQuery lifecycle anti-pattern

---

lib/auth.js

None of these functions are used anywhere else anymore. Only `setMultiAuthCookies` (for login) and `multiAuthMiddleware` (to switch the `next-auth.session-token` cookies on each request) needs to be exported.

Remove unnecessary exports

---

api/ssrApollo.js
components/account.js
lib/auth.js
pages/api/next-account.js
pages/login.js

Based on #1997 #2005 #2006
I realized that in prod, the next-auth cookies use the `__Secure-` prefix, see [_Cookie prefixes_](https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/Cookies#cookie_prefixes) on MDN. We should use this prefix also for our `multi_auth` cookies.
TODO:
~**Account switching will be unavailable for everyone when we deploy** until they logged back in.~ _This is fixed in #2007._
No, but #2007 makes it backwards compatible
`8`. Tested account switching functionality with https://sn.ekzy.is/.
n/a …

Use __Secure- cookie prefix

---

api/resolvers/wallet.js
components/wallet-logger.js
prisma/migrations/20250118192921_normalized_wallet_logs/migration.sql
prisma/schema.prisma
wallets/server.js
worker/paidAction.js
worker/payingAction.js

We want to normalize the wallet logs. They currently don't link to invoices or withdrawals via foreign keys but store all the data in the JSON `context` column.
~However, afaict, we can't get rid of `context` entirely since either a) the data we want to show is unrelated to an invoice or b) the invoice was not created yet.~
~**update:** Decided to drop the `context` column anyway to keep it simple. If we really need some information, we can add it back or save it in a relational way.~
**update:** Realized we would lose `created invoice for X sats` log messages. We log them when we just fetched a user invoice before they get wrapped. Since wrapping can fail, this would mean we would show an error without having shown that we created an invoice.
There are and will most likely be more cases …

normalized wallet logs

---

components/login.js

I think it's better to remove the cookie when we left the login page instead of when we visit /signup.
However, if we navigate away by entering a URL, the `useEffect` cleanup will not run.
We could fix this with a global `useEffect` that listens for path changes and sets/unsets the cookie if we're on /login or not.
TODO:
https://github.com/user-attachments/assets/349d8f22-1569-4464-b7b1-b5c7bdc00fef
yes, especially because #1976 was not deployed yet
`5`. Tested that the cookie is removed when I leave /login.
n/a
**Did you …

Refactor login cookie with cookieOptions function

---

api/resolvers/search.js

Closes https://github.com/stackernews/stacker.news/issues/2004
The problem was that if a search query contained only `@nym` and `~territory` terms, the `termQueries` object would be empty. This causes the resulting search query passed to OpenSearch to contain only a `filter` clause and an empty `should` clause. However, `filter` does not apply a numerical score to the items returned by OpenSearch.  Since all of our search modes work by applying a multiplicative modifier to the item's score, not having a score means not being able to sort.
The solution is to include the nym and territory filters also in the `should` clause. This ensures that the `should` clause is not empty so all items can have a numerical score which can be modified by the sorts. 
(This may not be the most efficient way …

allow sort for search queries with only filters

---

components/account.js
components/banners.js

Based on #2010
Since we will remove this error checking code in #2007 anyway, I want to already remove it in this separate PR to get it out of the way of refactoring the client code for account switching for #2007.
yes
`8`. This only removes future dead code. I searched for `multiAuthError` to make sure I didn't miss any reference to it.
n/a
no

Remove multi auth error checking

---

lib/auth.js

This can handle more potential issues.
yes
`7` . Cookies are reset if pointer is not a number or if we fail to decode the JWT.
n/a
no

Reset if pointer is not a number or JWT cannot be decoded

---

components/account.js
components/nav/common.js
components/use-cookie.js
pages/_app.js

Based on ~#2018~ _(merged)_
I was able to remove almost all React state and only rely on a new `useCookie` hook to tell us what the current state of account switching is (which accounts are available + which account is selected). This looks much simpler now.
Unfortunately, I had to use polling to keep track of cookie changes because the [`CookieStore` API](https://developer.mozilla.org/en-US/docs/Web/API/CookieStore/change_event) is not supported in all browsers (Safari :eyes:).
yes
`8`. Tested switching between anon and user, user and user, logout until fully logged out.
**For frontend changes: Tested on …

Refactor multi auth client-side code with new useCookie hook

---

docker-compose.yml

Removed OpenSearch API Password on Line 176
Removed hardcoded OpenSearch admin password from docker-compose.yml and replaced it with an environment variable reference. 
The change specifically:
- Replaces `OPENSEARCH_INITIAL_ADMIN_PASSWORD=password` with `OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_PASSWORD}`
- Utilizes the existing `OPENSEARCH_PASSWORD` variable from .env.development
- Maintains functionality while improving security practices
N/A - Configuration change only
The change was straightforward as the environment variable was already defined in .env.development. This suggests there might be other instances of hardcoded credentials in the codebase that could benefit from similar treatment.
Yes, fully backwards …

Removed OpenSearch API Password

---

lib/auth.js

Based on ~#1998~ ~#2018~ ~#2019~
Instead of just removing all `multi_auth` cookies on error, we now reset to the initial state.
yes
`7`. Tested by removing each `multi_auth` cookie and seeing it getting set again.
https://github.com/user-attachments/assets/c65f7a53-ef14-4940-8bf5-006a32299021
n/a
no

Reset multi_auth to initial state on error

---

lib/webPush.js
sw/eventListener.js

This merges `THREAD` push notifications with `REPLY` push notifications but still respects the user setting for `THREAD` push notifications.
https://github.com/user-attachments/assets/0ab80a13-8cc5-4113-b64b-9b82d895cbea
yes
`8`. See video.
n/a
no

Merge follow-up replies with normal replies

---

api/paidAction/itemUpdate.js
lib/webPush.js

Every time I get a push notification that I was mentioned, my first question is who mentioned me.
So instead of `you were mentioned`, it now shows `@user mentioned you`.
yes
`8`. Tested push notifications if mentioned on `ITEM_CREATE` or `ITEM_UPDATE`.
n/a
no

Include name in mention push notification

---

components/post.js
components/territory-header.js

Almost always when I want to post something and I am looking for the right territory, I find some that I would like to visit.
This is currently annoying because there is no link to the territory anywhere while posting.
This PR includes the link in the territory info, but only while posting. In all other places, there is already a link available on the same page ([top territories](https://stacker.news/top/territories/day)) or we're already looking at the territory.
This is mostly just a PR to mention this problem with the laziest solution possible. I followed the path of least resistance.
yes
`8`. Since this …

Add territory link in post form info

---

lib/rehype-sn.js

We have hydration errors in our FAQ and I believe they are causing scroll issues since "as a result this tree will be regenerated on the client."
> Hydration failed because the server rendered [missing argument] didn't match the client. As a result this tree will be regenerated on the client. This can happen if a SSR-ed Client Component used:
>
> - A server/client branch `if (typeof window !== 'undefined')`.
> - Variable input such as `Date.now()` or `Math.random()` which changes each time it's called.
> - Date formatting in a user's locale which doesn't match the server.
> - External changing data without sending a snapshot of it along with the HTML.
> - Invalid HTML tag nesting.
> 
> It can also happen if the client has a browser extension installed which messes with the HTML before …

Fix FAQ hydration error

---

components/nav/common.js
components/nav/mobile/offcanvas.js
components/wallet-indicator.js
pages/wallets/index.js
wallets/index.js

~based on #2046~ _(merged)_
Show an indicator if no wallet has been setup yet like we do for bios.
TODO:
1. This will always show an indicator if no wallet is configured, not only the first time.
2. On back navigation, the button should maybe not show up again? It's at least annoying during development.
yes
`7`. Tested that wallet indicator disappers if recv or send wallet is attached. Indicator appears again when all wallets are detached.
yes …

Wallet indicators

---

api/resolvers/wallet.js

`testCreateInvoice` only checks currently if it throws but not if it actually returned a payment request.
This PR fixes that.
Considered to use this as the error message: `expected payment request, got: ${pr}` but I don't want to think if they might expose something to the user or store in logs we don't want
yes
`6`. Tested with NWC recv on 06d05c7f when it returned `undefined` and when it returned a pr (b617ac0a).
n/a
no

Verify testCreateInvoice returns a payment request

---

lib/cln.js
lib/url.js
wallets/blink/common.js
wallets/lightning-address/server.js
wallets/lnbits/client.js
wallets/lnbits/server.js
wallets/phoenixd/client.js
wallets/phoenixd/server.js

Our error messages on fetch errors are misleading: they always use `POST` as the method.
Unfortunately, afaict, it is not possible to go from [`Response`](https://developer.mozilla.org/en-US/docs/Web/API/Response) to request method so we have to manually pass it.
yes
`6`. Only tested with a lightning address that times out but changes are simple so ... lgtm :eyes: 
n/a
no

Fix wrong method in error message

---

worker/socialPoster.js

`NOSTR_PRIVATE_KEY` is defined in .env.development so the social poster will try to publish these events during development.
This PR makes sure the social poster only runs in production.
yes
0
n/a
no

Run social poster only in prod

---

README.md
docker-compose.yml
docker/opensearch/init-opensearch.sh
docs/dev/semantic-search.md
nlp-setup
scripts/nlp-setup

Closes https://github.com/stackernews/stacker.news/issues/2061 by fixing malformed curl request
Closes https://github.com/stackernews/stacker.news/issues/2058 by increasing memory available for JVM in opensearch container
Closes https://github.com/stackernews/stacker.news/issues/2047 by adding a setup script for semantic search
`nlp-setup` needs to be called after the initial index is already up and running. Thus, the containers and volumes must already be running by calling `sndev start` at least once. After `nlp-setup` is run, the containers need to be restarted with `sndev stop` and `sndev start` to enable semantic search in the dev environment.
It shouldn't affect anyone's running dev environment unless you run …

NLP startup script + opensearch fixes

---

components/item-act.js
wallets/index.js

Potential fix for #1656
Could not reproduce bug but using `wallets` instead of `wallets.length` should be fine sine `useSendWallets` returns a memoized value.
yes
`5`. Tested zapping with NWC. Still works.
n/a
no

Use wallets instead of wallets.length as useZap dependency

---

lib/lnurl.js
lib/url.js

A common error for lightning addresses is that `await req.json()` rejects, for example because the server didn't even respond with 2xx. This PR handles that case to show a more useful error message that includes the HTTP status code.
yes
`8`. Tested with calle@cashu.me (fails) and calle@npub.cash (succeeds).
n/a
no

Handle lightning address JSON errors

---

lib/rehype-sn.js

Fixes #2076
This regex matches user mentions (also with paths) starting with `@`, like @sox or @sox/all.
It ensures that the `@` symbol is not preceded by a word character, that it has the `@` symbol and that we have a username that contains word characters or underscores. Optionally, it could have a single forward slash to indicate paths.
As a bonus, it fixes popovers for mentions with slashes by serving only the username part to the `Mention` component.
https://github.com/user-attachments/assets/da283057-dada-4103-942d-a36aeeb828a2
I exponentially tested the possibility of abuse and the ms it took for the regex to conclude didn't grow.
Initially this regex contained * for more than one slash, it happens that user paths never have more than a single slash so it was removed.
**Are your …

Non-word boundary Regex on user Mentions

---

capture/package-lock.json
capture/package.json

We're not affected by [this](https://github.com/stackernews/stacker.news/security/dependabot/28) but I think it's still a good idea to update `express`.
yes, should be since it's just a minor version update
`0`
n/a
no

Update express to 4.21.2

---

components/login.js

Fix #2067
Adds a message that asks the user if they wanted to sign up instead.
https://github.com/user-attachments/assets/ae6593e9-41b1-455f-a381-e1e1feb21b61
This implementation is a workaround to next auth's missing custom error support.
Yes, it falls back to the original errors if signin prop is not present
6, the error shows only on sign in and only on errors that gets thrown by next auth in case of failure in returning the user object.
Yes …

enhance: helpful error message on login

---

components/wallet-indicator.js
pages/wallets/index.js
wallets/index.js

The wallet indicator currently shows up for everyone on first render because the wallets aren't loaded yet. Fixed that by exposing a loading state via `useWallets`.
However, this means that instead of going from `true` to `false` if there actually is a wallet attached, it now goes from `false` to `true` if there actually isn't a wallet attached, see video.
I think the way it is now (`false`to `true`) is better UX in most cases since most stackers will probably attach a wallet. 
Still something to think about.
<sub>I'm having a déjà vu :eyes:</sub>
https://github.com/user-attachments/assets/767a7263-1f25-4057-b584-f61911048334
- https://stacker.news/items/939641?commentId=939788
- this new loading state for the wallets might have been very useful a long time ago already for other things …

Fix wallet indicator blink via wallet loading state

---

prisma/migrations/20250411220921_fix_item_delete/migration.sql

Fix #2095 
This excludes the text `*deleted by author*` from hitting the constraint that I added in https://github.com/stackernews/stacker.news/pull/1747.
yes, it should be because this is excluding more from the constraint so anything that exists should already be valid according to it
`7`. Made sure this fixes the issue.
n/a
no

Fix item deletion hits constraint

---

api/resolvers/wallet.js
api/typeDefs/wallet.js
fragments/wallet.js

We don't use these wallet resolver and arguments anymore.
Removing them also means less stuff for me to migrate in #2092.
yes since the resolvers weren't used
`8`. I noticed that the resolvers are unused because I found nothing referencing the fragments. Also tried to search manually for some references but none showed up.
n/a
no

Remove unused wallet resolvers

---

.github/workflows/extend-awards.yml
docs/dev/extend-awards.md

Currently as described in #1991, when a PR is merged while a PR previously opened by the `extend-awards` workflow is still opened & unmerged into master, the workflow runs again and overwrites the prior changes. 
This PR addresses this issue by adding steps in the workflow to first check if the branch that the workflow creates is available, signalling that there is still a PR open trying to extend the awards.csv file. If there is a branch, the workflow instead pushes a commit to that branch rather than creating a new PR and overwriting changes. 
I checked on alternative approaches. Based on the docs for the [create-pull-request](https://github.com/peter-evans/create-pull-request) there is no obvious application/example that addresses this issue. Also, creating differently named branches …

fix(extend-awards): add check for existing branch with pending awards

---

api/resolvers/vault.js
api/typeDefs/vault.js
fragments/vault.js

Just like #2104, this removes vault resolvers and the `keysFilter` argument for `getVaultEntries` since they weren't used anywhere.
yes
`8`. Tested by rebasing #2092 on this branch and enabling, disconnecting, resetting and re-enabling device sync. Also saved LNbits with and without admin key etc. 
It's really not used; I didn't miss a reference.
n/a
no

Remove unused vault resolvers

---

lib/webPush.js

Found this while looking into #2116.
Not sure why this used `$queryRawUnsafe`. We edited  this query multiple times but always kept `$queryRawUnsafe`, lol
Works fine with `$queryRaw`.
yes
`9`. Tested with a reply from anon that the query runs as expected w/o syntax errors. Then I muted anon and query still runs as expected.
n/a
no

Fix unnecessary $queryRawUnsafe and missing await

---

lib/webPush.js

Based on #2117 
Fix 50% of #2116 because this only fixes the "ghost push notification" mentioned in #2116 (push notification received but none in /notifications).
The other issue is that when we unsubscribe from the root, we are still subscribed to replies to our own replies in that post.
I think if we unsubscribe from an item, we should also unsubscribe from all children.
I will do this in another PR.
tbd (ETA tomorrow)
yes
~lgtm rn, but will test again tomorrow and make sure this (simple?) fix still makes sense~
`9`. Tested with two levels of subscription: subscription to root item and subscription to own …

Fix push notifications sent without thread subscription

---

api/resolvers/item.js
components/subscribe.js

Fix #2116 
Now, when you unsubscribe, we will also delete any subscriptions from nested items such that you are really fully unsubscribed from an item.
TODO:
Since `unsubscribe` only shows up if you already have a subscription, stackers other than the author of the post would first need to subscribe so they can unsubscribe and delete all subscriptions they have in that item ...
This isn't great UX but should be enough to fix the notification spam caused be deeply nested replies in [item 948515](https://stacker.news/items/948515).
yes
`8`. Tested at various levels of nesting.
**For frontend changes: Tested …

Also unsubscribe from any children

---

lib/webPush.js

I should have tested #2118 with a reply from someone else in between.
The current filter only checks if any parent of a reply has a thread subscription. If that's the case, it will still continue to send out push notifications for all of them.
This PR fixes this by also checking that the thread subscription belongs to the parent.
yes
Now for real a `8`:
I ran this current query with the bug:
```sql
SELECT DISTINCT p."userId", i."userId" = p."userId" as "isDirect"
FROM "Item" i
JOIN "Item" p ON p.path @> i.path
WHERE i.id = 949729 and p."userId" <> 25629
AND NOT EXISTS (
SELECT 1 FROM "Mute" m
WHERE …
```

Fix push notification sent without own thread subscription

---

worker/imgproxy.js

#2074 broke profile picture uploads by adding an unwanted slash after the NEXT_PUBLIC_MEDIA_URL env var.
This PR uses a URL constructor to avoid this kind of inconsistencies.
n/a
In dev it works without problems because we set the URL manually via env vars, while in prod we use S3 buckets to then compose a URL for m.stacker.news, without infos on that a URL constructor should delete any doubts.
Yes
9, it works with or without slashes in dev
n/a …

hotfix: use URL constructor for imgproxy crop

---

worker/imgproxy.js

It uses the correct environment variable for production, which is `NEXT_PUBLIC_MEDIA_DOMAIN`
n/a
Production handles uploads url differently than dev, it doesn't use `NEXT_PUBLIC_MEDIA_URL`
Also reverted the usage of URL constructor as we don't need to normalize slashes for how we already compose the environment variables we use.
Yes
6, it works in dev and it **_should!_** in prod.
n/a
n/a

hotfix: return correct uploads url for imgproxy crop

---

api/paidAction/README.md

I think linking to the Postgres documentation that explains the same issue for the `read committed` transaction level is good.

Mention "phantom reads" in README

---

api/resolvers/user.js
api/typeDefs/user.js

The privacy setting to hide cowboy essentials was causing the wallet prompt to show up even with a wallet to receive attached.
This was reported [here](https://stacker.news/items/959013?commentId=959068).
yes
`7`.
Tested by attaching a lightning address via the wallet prompt. Wallet prompt no longer shows up. When I enable the privacy setting to hide the horse, the wallet prompt starts showing up again. This change fixes that.
n/a
no

Fix privacy setting interfering with wallet prompt

---

wallets/lightning-address/server.js

Test invoices for a lightning address can fail if we're requesting an invoice for an amount it does not support.
Example: https://breez.fun/.well-known/lnurlp/needcreations
This was reported [here](https://stacker.news/items/958590?commentId=960241).
The other issue that one can see in the [report](https://stacker.news/items/958590?commentId=960241) is that [`assertContentTypeJson`](https://github.com/stackernews/stacker.news/blob/4ad64d658fcf33d34ff3b3224d32d1ef9c7e513a/lib/url.js#L236-L241) would also throw `ResponseAssertError` which will log a confusing error message with 200 OK instead of "expected json, got html."
I will fix this in another PR.
yes
**On a scale of 1-10 how well and how have you QA'd this change and any …

Fix lnaddr attach fails if minSendable > 1000

---

lib/lnurl.js

On lnurlp errors, the message didn't include the used fetch method which was inconsistent with other error messages.

Fix missing method in lnurlp error

---

lib/url.js

The error message if our assertion for the `Content-Type` header failed didn't mention that it failed because of the header, not because of the status code, see [here](https://stacker.news/items/958590?commentId=960241).
This PR fixes this.
yes
`8`. Tested with this patch and calle@npub.cash:
```diff
diff --git a/lib/url.js b/lib/url.js
index c6871fc8..3b57920a 100644
--- a/lib/url.js
+++ b/lib/url.js
@@ -242,7 +242,7 @@ export function assertResponseOk (res, { method } = {}) {
export function assertContentTypeJson (res, { method } = {}) {
const expected = 'application/json'
const contentType = …
```

Fix error message on content-type mismatch

---

wallets/lightning-address/server.js

Fix #2147 
The only explanation I have for #2147 is that `minSendable` is 0 and thus we multiply by 0 even though the report mentions that `minSendable` is 1:
> With lnurlp my minSendable is 1 not 0.
Anyway, it's good to make sure it's at least 1 sat.
yes
`8`. Tested with calle@npub.cash.
n/a
no

Fix 0 sat lnaddr invoices

---

components/use-crossposter.js

So far nobody complained, but I think the crossposted notes on nostr look way cleaner without "originally posted at."
Example: [naddr1qvzqqqr4gupzq5064fm3wsdd252sacufuksxa0t29fp249q545lsvmqhdukzvc2mqqrrjde3xgmnw6lyklj](https://njump.me/naddr1qvzqqqr4gupzq5064fm3wsdd252sacufuksxa0t29fp249q545lsvmqhdukzvc2mqqrrjde3xgmnw6lyklj)
yes
0
n/a
no

Remove 'originally posted at'

---

.github/workflows/extend-awards.yml
extend-awards.py

Modify extend-awards.py so that when a pull request references and fixes multiple issues, each issue is attributed and awarded accordingly. Also fixed typo in Github bot message.
Test PR from my fork of this repo demonstrating functionality: https://github.com/brymut/stacker.news/pull/57
Resultant PR extending awards with all attributed issues: https://github.com/brymut/stacker.news/pull/58
closes #2087 
https://github.com/user-attachments/assets/db8a183b-7d49-44d0-ad6c-43a0dea5f566
Yes
10
N/A …

feat: attribute multiple issues addressed in a single PR in awards.csv

---

components/link-to-context.module.css

Fixes issue where if markdown for a heading is used in a comment, the notification would contain the the markdown rendered into Html containing a heading anchor link overriding the notification link to the actual comment. 
Edit: changed solution to using css that targets the anchor tags in the notification body
Closes #2142 
https://github.com/user-attachments/assets/8aa9a4fd-dd6c-4743-977d-93e07686ad61
Yes
10
*For frontend changes: Tested on mobile, light and dark mode? Please answer below:**
N/A
**Did …

Add check to prevent Markdown Heading links from rendering in notifcations

---

prisma/migrations/20250513212337_delete_duplicate_wallets/migration.sql
prisma/schema.prisma

Temporary fix for any user affected by #2160.
This does not fix the root cause so it might still be possible to create duplicate wallets. I know that #2059 made it possible to save a lightning address multiple times because if the user was hiding their wallet badges, the prompt would still show up. This was fixed in #2134.
However, I believe creating multiple/duplicate wallets per type was possible even before #2059.
This also doesn't check that the wallets are indeed duplicates (same values), but in that case, we would need to decide ourselves which wallet we're going to keep per user anyway. I decided to keep the wallet that was most recently updated.
The root cause will be fixed via #2092, #2146 and related changes.
We can also run this query manually, we don't need to deploy this as a …

Delete duplicate wallets

---

api/resolvers/item.js

Auto populate the title field if youtube link is used in the Link Form. 
Closes https://github.com/stackernews/stacker.news/issues/2164
https://github.com/user-attachments/assets/a452dd57-d88c-4ed0-b0d7-804599c3c9fb
yes
10
yes
no

Auto-populate YouTube video titles server-side and enforce title length.

---

api/resolvers/item.js

Dupes resolver to only show items with invoiceActionState as PAID or NULL. Based on [feedback provided ](https://github.com/stackernews/stacker.news/issues/2173#issuecomment-2898194663)
Closes https://github.com/stackernews/stacker.news/issues/2173
no

Refactor(dupes): filter dupes by PAID or NULL invoiceActionState

---

sndev

When you run `sndev cert lnd`, the output contains new lines. I had to always remove them manually with `tr -d '\n'` before I could pipe the output into my clipboard via `xclip`.
I noticed that `base64` has the option to not wrap lines via `-w0`. Now I can pipe the output of `sndev cert lnd` into `xclip` and save the LND wallet.
I used https://www.shellcheck.net/ to make sure `base64 -w0` is POSIX compliant and I think it is because I did not see this error:
> ^-- SC2039: In POSIX sh, [[ ]] is undefined.
yes
`9`.
n/a
**Did …

Don't wrap base64 cert output

---

awards.csv

Added the payout for [GHSA-x2xp-x867-4jfc](https://github.com/stackernews/stacker.news/security/advisories/GHSA-x2xp-x867-4jfc) to awards.csv as requested. 
Afaict, using advisory as the type and the GHSA id should not break our awards script but not sure.

Add security advisory payout to awards.csv

---

api/resolvers/search.js

_A clear and concise description of what you changed and why._
fixes #2181 
Avoid including both exact matches and item text in search results.
Before
After
Yes
10
Tested on laptop only
No

fix duplicate search highlights

---

components/footer.js

@janakelsay told me that @Soxasora had the idea to add a link to the zines in the footer.
While I discussed this idea with @janakelsay, we considered if we should link to a page on SN with all the PDFs and zaprite links, similar to how it's done [here](https://plebpoet.com/zines.html), but since:
- we don't deploy weekly
- the PDFs would bloat the repository
- it would be more work
I decided that it's easier for now to just link to her website.
yes, it's just a link
`10`. Link works!
nothing changed wrt light or dark mode …

Add zines to socials in footer

---

api/paidAction/README.md

`OPTIMISTIC` as a payment method for `RECEIVE` was removed in 5a8804de.
yes
10
n/a
no

Fix documentation for RECEIVE paid action

---

api/resolvers/wallet.js
api/typeDefs/wallet.js

While looking into #2029, I noticed that the `createInvoice` mutation is not used anywhere afaict.
I searched for `mutation create`, but could not find a mutation that calls `createInvoice`.
I then used `git log -S "mutation createInvoice"` and found that the mutation that would call this function was removed in 146b6027 (see pages/withdraw.js).
This makes sense, because that commit also introduced the `buyCredits` mutation; essentially replacing the `createInvoice` mutation.
So I am pretty confident this mutation is indeed no longer used anywhere.
yes
`5`. Code builds and tested buying credits. Not sure …

Remove unused createInvoice mutation

---

api/paidAction/receive.js

This function can be removed because it will never do anything when called.
It does not do anything for wrapped invoices, and it will never get called for direct payments (since we don't know when the invoice was paid).
These are the only two payment methods for the `RECEIVE` paid action since 5a8804d.
yes
`6`. Paid a wrapped invoice and a direct invoice returned via LNURLp and saw no errors in the worker.
n/a
no

Remove unused onPaid for RECEIVE paid action

---

components/embed.js
components/text.js
components/text.module.css

Fix to make listed embeds in markdown render the bullets at the top of embeds rather that the bottom
closes #2204
Tested using:
```
- https://www.youtube.com/watch?v=TA5nwAKav6A&t=544s
- https://x.com/unusual_whales/status/1933171682505814096
- https://primal.net/e/nevent1qqsphjsyk2l8uw5y3jun0nyjp26efe8lc2glj9584gg8mmlg7d7nmugzrlygy
- https://wavlake.com/track/4f596f59-4dc3-4eb0-8ea7-a4bdf9d13585
- https://open.spotify.com/track/4LhRPmfYakIKSWWwGAFOPj?si=0s7pjVyJRCCaMKk9yZNWxA
- https://rumble.com/embed/v6nspz0/?pub=3dskgx
- https://peertube.tv/w/cU3WYY81yg3Hpz53aujv3k
- https://bitcointv.com/w/fZkPWnEgRTfrUGCCDDbRTv
- https://github.com/stackernews/stacker.news/issues/2204
```
https://github.com/user-attachments/assets/152ed6eb-af84-4f52-8cfc-0f7ef6bfbd71
_Was anything unclear during …

fix embed list bullet to render at top of embed

---

components/form.js

I noticed—a while ago actually—that every form submission included an `amount` parameter.
For example, when you search for something, the URL contains an useless `amount` parameter: https://stacker.news/search?amount=&q=asdf
I now looked into this because of #2169 and noticed it's a relict of #1194 where I introduced the `usePayment` hook.
This hook no longer exists. We now handle payments with `usePaidMutation`.
yes
`9`. I searched for `name='amount'` to find all places where the `amount` param is used in a form.
That's the case for zaps, boost, buying credits, withdrawals and donations. I tested all of …

Remove unused injected amount param

---

api/paidAction/receive.js
api/typeDefs/user.js
fragments/users.js
pages/settings/index.js
prisma/migrations/20250614190749_remove_direct_receive_setting/migration.sql
prisma/schema.prisma

Close #2029 
This removes the `directReceive` setting because it currently unintentionally disabled the lightning address if  `directReceive` was not enabled and `proxyReceive` was not enabled or wrapping failed.
Since the original purpose of this setting was to disable buying credits, which is no longer possible since 5a8804de79ff8e004a74e52afc5ff4bf3e9ab3b3, this setting is no longer needed.
Now, if proxy was not enabled or wrapping failed, we always fallback to direct payments.
For the sake of keeping the product simple / simplifying it, I think we don't need to give stackers a dedicated setting to control if they want these fallbacks or not.
I actually think we should never fallback to direct payments if the proxy was enabled.
If the proxy is enabled and we allow fallbacks, it's …

Remove directReceive setting

---

.github/pull_request_template.md

I dropped a database column in #2230, but didn't notice that old Prisma clients would still try to query this column.
For the future, we can just add a comment to the columns in the Prisma schema columns that we want to remove in a follow-up PR.

Add another example to question about backward compatibility

---

components/fireworks.js

Fireworks didn't check if animations were disabled.
- https://stacker.news/items/1022281?commentId=1022632
- you can merge just this to fix the bug or merge #2261 to fix the bug and refactor so it doesn't happen again
`10`. 
n/a
no

Fix fireworks not checking localStorage flag

---

styles/globals.scss

Fix style for the poll expiraton clear button, now better aligns with ui style. Inspiration from clear button from main search UI.
closes #2106 
Dark Mode:
Dark Mode, mobile:
Light Mode:
Light Mode, mobile:
Y
10
Y
N

Fix poll expiration clear button style

---

components/item-info.js
components/item.js
lib/new-comments.js

When we reply to a post, we update the count of comments we’ve viewed in that post to avoid seeing the new comment indicator on our own replies.
But instead of counting, we're actually concatenating strings with what we retrieve in the local storage.
This PR parses `commentsViewNum` as Number, allowing real counts.
3 replies gets saved as `111` (as 3 times +1)
This actually **still worked anyway**, because to search for new comments we do (other than checking the time) `commentsViewedNum < item.ncomments`. So `6 + 1` would do `61` instead of `7`, and the comparison would  still give the expected behavior.
Yes
**On a …

Fix count of viewed comments of a post

---

api/resolvers/wallet.js
wallets/server/logger.js
wallets/server/resolvers/protocol.js

1. Logs by the client include `createdAt` in the context object, but they weren't meant to literally be included in the logger context, but simply as a timestamp for the message itself.
2. Removed `WalletLogEntry` field resolver duplicate that wasn't used. The one that is used is in wallets/server/resolvers/protocol.js.
3. Invoice was not included in the context for `sending payment` or `payment sent` log messages. If the invoice belongs to the user, it's safe to show. It will also show up in satistics.
4. Make sure we only show withdrawals that belong to the user, even though there's no case where we would create a log message for someone and link to the withdrawal of someone else.
yes
**On a scale of 1-10 how well and how …

wallet logger fixes

---

wallets/server/logger.js

@cursor mentioned this in https://github.com/stackernews/stacker.news/pull/2307#pullrequestreview-3040260608.
We should only run the status update of a protocol while logging when we actually have a protocol id.
It can currently never happen that `updateStatus` is true without a protocol id also set, but it's good to make sure.
yes
`10`. Protocol status still gets updated. 
n/a
no

Only update status if protocolId is set

---

components/form.js
pages/wallets/index.js
wallets/client/hooks/crypto.js

Related to #2288 
I noticed that everything works as expected if I don't return a function in `useMemo`.
That means I can't use JSX syntax, but I think this fixes it because else I would return a completely new component which React does not recognize as the same (??)
yes
`10`. Tested scanning with and without remounting while scanner is open.
n/a
no

Fix useMemo returns new component on change

---

components/comment.js

Fixes bottomed out comments retaining their `newComments` field by clearing it on route change.
https://github.com/user-attachments/assets/abb64564-1bcf-4142-b089-2a599531fae1
Yes
7, on route changes, only items that have the newComments array populated are being cleared
n/a
n/a

Fix clear new comments on route change

---

components/carousel.js

I noticed that @brymut fixed something in #2262 that we haven't even noticed yet.
The `... > view original` is never updated while we move around in the carousel, so clicking on `view original` always opens the image with which we entered the carousel. This PR fixes this.
Seems like this has always been a problem. In #1425, I did pass `setOptions` to `<Carousel>` but never used it, so I removed it in #2325 today.
I set @brymut as the author of the commit so rewards go to him.
yes
`8`. Dropdown is now properly updated while moving around in the carousel
**For frontend changes: Tested on mobile, light and dark …

Fix carousel dropdown

---

styles/logger.module.css

[`text-wrap`](https://developer.mozilla.org/en-US/docs/Web/CSS/text-wrap) is newly available, [`white-space`](https://developer.mozilla.org/en-US/docs/Web/CSS/white-space) is widely available
yes
`10`
n/a
no

Replace text-wrap with white-space because of better support

---

wallets/server/resolvers/wallet.js

I missed this when I replaced `id` as the primary key of the `WalletTemplate` table with `name`.
Afaict, this didn't cause any bugs because the id of `WalletTemplate` wasn't used anywhere where it had to be unique globally, only per wallet.
`10`. Tested creating a new LNbits wallet with send and receive.
n/a
no

Fix undefined in resolved WalletTemplate id

---

styles/nav.module.css

Fixes this warning in the browser console:
```
./node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[7].oneOf[9].use[1]!./node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[7].oneOf[9].use[2]!./styles/nav.module.css
Warning
(9:5) autoprefixer: start value has mixed support, consider using flex-start instead
Import trace for requested module:
./node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[7].oneOf[9].use[1]!./node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[7].oneOf[9].use[2]!./styles/nav.module.css
./styles/nav.module.css
./wallets/client/components/forms.js
./wallets/client/components/index.js
./wallets/client/hooks/crypto.js …
```

Fix autoprefixer warning

---

styles/dnd.module.css
wallets/client/context/dnd.js

fix #2322 based on #2347
Setting [`touch-action`](https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action) to `none` prevented panning (scrolling). Using `touch-action: pan-y` allows vertical scrolling.
It's not perfect, because when you start with scrolling vertically, you can still scroll horizontally and unexpectedly trigger DnD, see video. 
However, by observing my own scrolling behavior on mobile, I assume that in the general case, people don't follow-up vertical movements to scroll with horizontal movements, so they won't run into this.
So I think this is a pretty simple fix for #2322 that covers 99% of the cases.
DnD is more annoying to use now if you don't know that scrolling horizontally first prevents the annoying scrolling while dragging :sweat_smile: 
before: …

Use touch-action: pan-y to fix DnD vs scroll

---

wallets/server/protocols/nwc.js

In #2169, I forgot to copy the existing validation for NWC receive to the new code.
**This means we didn't check that `pay_invoice` is not supported.**
I downloaded a CSV file for all currently saved NWC receive protocols to check if any of them do support `pay_invoice`. Then we should delete them.
I also went through the diff of #2169 to check if I forgot that for other protocols, too, but I didn't. But most of them didn't even include a way to test if payments are not supported (see LNbits, Phoenixd).
This could be fixed via #1341. Instead of only testing if a payment is possible, we can do the same when attaching a receive wallet to make sure it's not possible (we always cancel the HODL invoice).
yes, but we have to …

Fix missing check for pay_invoice for NWC recv

---

wallets/client/components/logger.js
wallets/client/hooks/logger.js

Some changes regarding wallet logs:
**Avoid visual clutter in wallet logs**
- wallets logs are now hidden when creating a new wallet and there are no logs yet
- delete and more button, `loading...`, `empty` and `--- start of logs ---` are always hidden when creating a new wallet
- tag like `[lnbits]` is now only shown when looking at all logs
**Refactor**
- put code for specific parts of a log message into separate components
- other minor stuff, see commits
yes
`9`. Tested all kinds of wallet logs stuff: `[system]` tag in global logs via lnurlp, template wallet logs, normal wallet logs + deletion of all …

wallet logs: less visual clutter, refactor

---

extend-awards.py

Closes #2276 
Refactors issue extraction in `findIssuesInPR` for extend-awards.py, where currently may lead to double attribution in awards.csv. Solution involves using keywords to find the actual closing attribution instead of merely mentioning the issue. PRs now should use the Github closing keywords: 
- close
- closes
- closed
- fix
- fixes
- fixed
- resolve
- resolves
- resolved
From Github docs: https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword
Original issue was spotted here: https://github.com/stackernews/stacker.news/pull/2266#discussion_r2190955990
To test that functionality was fixed, I created a few test issues, https://github.com/brymut/stacker.news/issues, on my …

Refactor issue extraction logic for proper award attribution

---

wallets/lib/protocols/nwc.js

Even though receive credentials are not encrypted, we still use the password type for them, but we weren't for NWC receive.
yes
`10`. Just changing the type of the input
n/a
no

Fix input type of url for NWC receive

---

wallets/client/fragments/protocol.js
wallets/client/hooks/query.js

Simple rename of a mutation to be consistent with the `WalletName` enum value

Rename mutation to UPSERT_WALLET_RECEIVE_LND_GRPC

---

components/info/cc.js

Dust limit settings have been moved to /wallets/settings

Fix link to dust limit settings in CCInfo

---

lib/validate.js

No bug encountered but `autoWithdrawSchemaMembers` wasn't used anywhere anymore but had more validation which I assume was added for a reason
yes
`8`. saved settings
n/a
no

Fix autoWithdraw settings schema

---

components/info/cc.js

fixes #2370 using standard navigation with `<a>` tag 
`api/daily` redirect breaks NextJS rewrite rules in client side navigation.
everything good
yes
7

fix link to /daily in CCinfo loads forever

---

wallets/client/context/hooks.js
wallets/client/context/provider.js

This hook wasn't used because what it was supposed to do was moved to `useIsWrongKey` and `useKeyInit`

Remove unused keyCheck hook

---

wallets/client/hooks/logger.js

This didn't cause any visible bugs because the wallet logs always remounted.
I am not sure why though, since `key={router.asPath}` is only passed to `<Form>`, not to `<WalletLogs>`:
https://github.com/stackernews/stacker.news/blob/cbc41c0d992c862bd9b0c292bbbee325e0fa9b15/wallets/client/components/forms.js#L188-L199
yes
no visible bug, but it should never poll logs with a stale protocol
n/a
no

Fix protocolId missing as dependency

---

wallets/client/components/debug.js

If the local key was updated more than one day ago, the `timeSince` function will call `getDate` on a number.
I also removed the 'ago' suffix because in that case, `timeSince` will not return a relative time but a date like '27 Jul'.
yes
`10`. Input to `timeSince` is now always a date
n/a
no

/wallets/debug: fix getDate is not a function

---

components/comment.js

Fixes #2409 
After merging together the bottomed out and pagination link buttons, I wrongly deleted the `commentId` param that scrolls the user to the correct comment.
This PR re-instates the correct URL.
n/a
n/a
Yes
9, scrolls to the correct comment
n/a
n/a

fix wrong URL on Reply on another page

---

components/preserve-scroll.js

Related to #2355 
If in the viewport we have a textarea, `preserveScroll` will use it as the anchor element to determine if something has moved.
If multiple textareas are present in the viewport, the focused one is preferred, otherwise the first in the tree will be picked as anchor.
Textarea is the preferred anchor element, with fallback
https://github.com/user-attachments/assets/4eec08c5-d2ee-4292-81b8-e790078e8888
<sup>incredibly fumbled on the compression settings</sup>
This required an additional layer of `requestAnimationFrame`: some browsers may have their own anonymous content, like text extensions and such, deferring textarea/input renders.
It still fallbacks to picking a ref at the middle of the viewport in absence of textareas
**Are your changes backward compatible? Please …

auto show: Use textarea as the anchor element if available

---

api/resolvers/upload.js

reported by @Soxasora 
GraphQL does not support bigint so we have to cast upload fees to a number first
https://github.com/user-attachments/assets/01e42d9c-74e3-48f0-b27d-8449658d442f
yes
`10`, see video
n/a
no

Fix GraphQL cannot represent bigint as integer

---

pages/wallets/[...slug].js
wallets/client/components/card.js
wallets/client/components/forms.js
wallets/client/hooks/query.js
wallets/client/hooks/wallet.js
wallets/lib/util.js
wallets/server/resolvers/wallet.js

This enables SSR for wallet configuration pages.
Before, we showed an empty page while the client fetched a wallet, see videos.
If a wallet didn't exist, the page would stay empty.
Now, the page is rendered on the server with input fields that require decryption being empty until decryption finishes and we correctly show a 404 page if a wallet wasn't found.
1. /wallets doesn't use SSR because we fetch the wallets in the background for zaps, not specifically for that page. The loading indicator is also good because it avoids showing the wallets before we checked if they need to unlock their wallets first.
1. There's a warning from `graphql-tag` now for the `WALLET` query:
> Warning: fragment with name WalletTemplateFields already exists.
graphql-tag enforces all fragment names across your …

Use SSR for wallets

---

next.config.js
package.json

fix #2361
Changes Made:
in `package.json` (dev script):
Added `NODE_OPTIONS='--trace-warnings --enable-source-maps'` to the dev script.
Why: Enables Node to use source maps generated by Next, so that server-side stack traces in development report correct file and line numbers.
in `next.config.js`:
Activated `experimental.serverSourceMaps: true`.
Why: serverSourceMaps causes server-side space for Node to read;
Before/After Behavior:
Before: Error traces in dev showed "wrong" lines or bundle/transpiled references.
After: Traces show the original source with correct line/column (verified with the test in zap.js).
Operational Notes
The app's logical paths have been left unchanged, only the debug/build configuration.
https://github.com/user-attachments/assets/bd9b7cee-1d88-4884-96db-6904cb0e856 …

fixing line numbers on error traces in development

---

components/pull-to-refresh.js

Navigator #2377 exacerbated unexpected triggers to pull-to-refresh by emitting `touchStart` on `scrollY === 0`, but navigator scrolls between `touchStart` and `touchMove`, causing `touchMove` to think we're still at the top
Other autoscrolls can cause this as the scroll position can change between touch events, so we need to continuously validate our assumptions during the touch events, not just at the start.
n/a
n/a
Yes
8, everything works at it should
**For frontend changes: Tested on mobile, …

Fix pull-to-refresh can trigger on unexpected scroll positions

---

pages/items/[id]/index.js

Fixes stale navigator on item navigation by giving a key (`item.id`) to the navigator provider, triggering an effective unmount also when the item ID has changed.
https://github.com/user-attachments/assets/293a2eb3-d884-4db6-9dd3-1e6db02881aa
I fixed this during iterative QA with route change events, but overall I think it's better to continue with simple unmounting logic and just give a key to the provider to cause an unmount.
n/a
7, tried on threads that links to a subtree
n/a
**Did you introduce any new environment …

Fix navigator not clearing on Item navigation

---

.devcontainer/devcontainer.json
.devcontainer/minimal/devcontainer.json
README.md
scripts/setup-codespaces.sh
sndev

Added .devcontainer a default & minimal configuration to support running the sndev environment in codespaces, added instructions in the README and modified login link so the hyperlink in the terminal can redirect to the correct container host link. Services are accessible via links in the VSCode tabs
closes #2209 
Log in link
Logged in user
Codespaces config
Ports Tab with links
Lnbits
The machines available for Github codespaces have limited compute & storage. Storage left after build & config is less than 10 GB. I customised the devcontainers to run using the highest available free tier machines.
**On a scale of …

add devcontainer config for codespaces

---

api/resolvers/item.js
api/resolvers/search.js

When a graphql API call is made like
{"operationName":"SubItems","variables":{"sort":"top","type":"all","limit":999}}
and there are more than 999 items, the call correctly returns 999 items, but the returned cursor is
{"offset":21,"time":"...}
because the default for the limit parameter is used:
lib/cursor.js:
export const LIMIT = 21
export function nextCursorEncoded (cursor, limit = LIMIT) {
This change passes the actual limit used to nextCursorEncoded().
Yes
1, no tests done.
**Did you introduce any new environment …

pass limit in nextCursorEncoded()

---

wallets/client/hooks/prompt.js

I think the checkbox is currently too easy to miss. It's also a modifier of skipping, so it should also be closer to the skip button because of that and come after the skip button.
before:
after:
yes
`10`. No functionality changed
n/a
no

Change layout in wallet prompt

---

lib/url.js

fixes https://github.com/stackernews/stacker.news/issues/2443
The start time is actually already passed to the embedded player verbatim.
But it seems Google have changed the accepted values. Now only an integer denoting seconds is accepted:
https://developers.google.com/youtube/player_parameters#start
https://stackoverflow.com/questions/17379268/youtube-dropped-t-start-time-support-in-direct-url-and-embed-videos
So, add a function parseYoutubeStart() which converts "2h30m10s" to "9010" etc.
https://github.com/user-attachments/assets/148f39bb-789e-452b-b4ac-a42eb4e1c684
Yes
8, I tested with multiple …

fix #2443: add parseYoutubeStart() to convert start times

---

wallets/client/hooks/prompt.js
wallets/client/hooks/query.js

This resolves a TODO for attaching lightning addresses via the prompt. We're now mapping the address to the appropriate wallet if there is one and only use the generic lightning address wallet as a fallback.
https://github.com/user-attachments/assets/0be0afa1-2f83-4612-bb8b-a1979bb82723
I assume this is the source of why we have a lot of LN_ADDR wallets even though most addresses in them are from a wallet we directly support.
I will create a follow-up PR to migrate these wallets to the correct wallet. This also helps with wallet statistics.
yes
`9`. Tested with npub.cash, blitz-wallet.com and patching the …

Map lnAddr to correct wallet on save via prompt

---

worker/imgproxy.js

Any image link should be HTTPS and xcancel.com links are not images.
The clients checks them all the time (and might even be triggering 429 Too Many Requests for the client IP if there are too many on a page). This PR doesn't fix that; these are just easy improvements to our list of definitely-not-image hosts.
yes
I did not test, only made sure that `new URL("https://xcancel.com).protocol` returns `https:`, so looks good to me
n/a
no

Improve image detection

---

api/resolvers/item.js

Fixes `meCommentsViewedAt` fallbacks following this coalesce order:
`"CommentsViewAt"."last_viewed_at" -> "Item"."lastCommentAt" -> "Item"."created_at"`
Didn't think of it since dev seed has `lastCommentAt` null
Yes
6, shouldn't kill anything
n/a
n/a

Fix CommentsViewAt coalesce fallbacks

---

components/use-comments-navigator.js

Removes the viewport check when tracking new comments with navigator.
I agree that the experience feels inconsistent, especially when the navigator becomes the main way someone navigates a comment thread.
n/a
8, it was a plug-n-play check!
n/a
n/a

navigator: also track new comments visible in viewport

---

docker/cln/Dockerfile

I noticed we don't need to install the CLNRest plugin dependencies. [It's built-in since v23.08](https://docs.corelightning.org/docs/rest):
> CLNRest is a lightweight Rust-based built-in Core Lightning plugin (from v23.08) that transforms RPC calls into a REST service.
So we also shouldn't have needed this before #2475.
This should fix #2484 because it removes the failing command.
yes
`10`. Can still attach send and receive and pay
n/a
**Did you introduce any new environment variables? If so, call them out explicitly …

Fix CLN container build on ARM

---

api/resolvers/item.js
components/comment.js
components/item-full.js
components/reply.js
components/use-comments-view.js
components/use-live-comments.js

Fixes items not being tracked server-side because `meCommentsViewedAt` would always be up-to-date.
Fixes outlining conditions for logged-in and anon users.
Backports the `useCommentsView` hook from #2462
This video showcases an item that was never visited (no outlines), and what happens when we start tracking it.
Also showcases a correctly working outlining.
https://github.com/user-attachments/assets/c10ff4b5-b6a7-4a03-bb10-bb4f0a310eba
Coalescing wasn't the greatest of ideas considering that the purpose of `CommentsViewAt` should be personal tracking.
Yes
7, iterative QA
**For frontend changes: Tested on …

Fix comments view tracking

---

Dockerfile

`npm ci` is meant for deployments. It's more secure because it will never touch package.json or package-lock.json:
-- https://docs.npmjs.com/cli/v11/commands/npm-ci
I think most companies that got hit today weren't using `npm ci` because they automatically updated to the next (minor) version via `npm install`.
[Here](https://news.ycombinator.com/item?id=45172015)'s a HN commenter with the same thought process:
> I'm a little confused on one of the excerpts from your article.
>
>> Our package-lock.json specified the stable version 1.3.2 or newer, so it installed the latest version 1.3.3
>
> As far as I've always understood, the lockfile always specifies one single, locked version for each dependency, and even provides the URL to the tarball of that version. You can define "x version or …

Only run npm ci during image build

---

styles/logger.module.css
wallets/client/components/logger.js

I think this looks better
before:
after:
yes
`10` (if this breaks I'll ... idk)
n/a
no

Change order of tag and level in log message

---

wallets/server/protocols/phoenixd.js

Phoenixd supports custom expiry but we weren't passing it.
Using `Math.ceil()` so when we divide 1 by 1000, it's 1, not 0, and not sure what 0 means. I decoded such a lightning invoice with https://lightningdecoder.com/ and for Expire Time, it only showed two dashes.
yes
`8`
n/a
no
**Did you use AI for this? If so, how much did it assist you?**
no

Fix missing custom expiry for phoenixd invoices

---

api/lnd/index.js

We currently log the following:
> failed to wrap invoice: Unable to estimate route, excessive values: {"routing_fee_msat":"0","time_lock_delay":"0","failure_reason":"FAILURE_REASON_NO_ROUTE"}
The code tried to use `res.failure_reason` if it exists, but it didn't reach that line because `err` is apparently not set.
This PR fixes this.
Will lookup the source code of `lnd.router.estimateRouteFee` to make sure errors are handled properly.
yes
`8`. Tested wrapping via p2p zaps
n/a
**Did you introduce any new environment …

Fix error message if no route found

---

pages/_app.js
sw/index.js

**Update 9/11**
Okay, finally tested this to a satisfactory degree and I'm quite confident this native solution to navigate to links works at least as well as the existing solution with `postMessage`.
This doesn't mean it works well, but I saw no difference between both implementations and I would prefer this one because it uses native APIs. 
That it doesn't use client-side routing is negligible imo. The possibly slight increase in navigation speed shouldn't be worth a theoretically less reliable implementation.
Contrary to what @cursor mentioned [below](https://github.com/stackernews/stacker.news/pull/2294#pullrequestreview-3031430061), [`WindowClient.navigate()` actually has pretty good support across browsers](https://developer.mozilla.org/en-US/docs/Web/API/WindowClient/navigate#browse …

Use WindowClient.navigate() instead of service worker message

---

prisma/migrations/20250910153121_delete_nwc_recv_with_payments/migration.sql

**Final comment**
This will delete wallets that are now empty but **it will not update badges by ending streaks**. I think that's okay. Instead of accidentally inserting something wrong into the `Streak` table, a simple wallet save by the stacker will bring their badges to the correct state (if it ended up being wrong)
---
As mentioned in #2365, we should delete the NWC credentials that have been saved in plaintext with any method that supports paying.
To automate this, I added basic nip47 support to `nak` in https://github.com/fiatjaf/nak/pull/78 today.
<details>
<summary>Steps</summary>
Steps to find the IDs we should delete:
1. Download CSV of this query from metabase:
```sql
SELECT id, url FROM "WalletRecvNWC";
```
2. Build my fork of `nak` with nip47 support
```
$ git clone …
```

Delete NWC plaintext credentials that allow payments

---

prisma/migrations/20250920162959_remove_coinos_nwc_receive/migration.sql

Coinos does not support creating receive-only NWC connections.
I also checked the database, there aren't any rows in the `WalletProtocol` table for NWC receive with Coinos.
yes
tbd
n/a
no
**Did you use AI for this? If so, how much did it assist you?**
no

Remove NWC receive for Coinos

---

wallets/client/components/form/index.js

fix #2558 
This removes the lightning address domain if it matches with the one we would append automatically on paste, and only on paste.
https://github.com/user-attachments/assets/53556758-e5d8-4033-8cd8-d24529f66b38
yes
`9` see video
n/a
no
**Did you use AI for this? If so, how much did it assist you?**
no

Remove lightning address domain on paste

---

wallets/client/components/form/hooks.js
wallets/lib/validate.js

close #2560 based on #2563, #2562
If we're looking at a lightning address form and we previously entered a NWC send string, we now check if that string contains a `lud16` parameter and use it as the initial value.
The user still needs to explicitly save that lightning address.
**TODO**
- :white_check_mark: use lud16 parameter as default for lightning address
- :white_check_mark: automatically switch to ~first configured protocol~ lightning address if it has an initial value when moving to receive
ideally this default selection when switching to receive would be agnostic of lightning address and simply check all protocols if they have some initial value and then pick the first one, but that requires more changes. `useProtocolForm` would need to support returning the forms for multiple …

Use NWC lud16 parameter as initial value for lightning addresses

---

wallets/client/errors.js
wallets/client/protocols/nwc.js
wallets/server/protocols/nwc.js
wallets/server/resolvers/protocol.js

I don't think we need to show them the specific method that is failing validation. Just saying 'credentials allow spending' etc. should be enough context for a user to understand what's wrong.
yes
`10`. Tested attaching send + receive with and without error
n/a
no
**Did you use AI for this? If so, how much did it assist you?**
no

Improve error messages on wrong permissions

---

api/typeDefs/wallet.js
docker-compose.yml
package-lock.json
package.json
prisma/migrations/20250905014333_clink_recv/migration.sql
prisma/schema.prisma
wallets/client/fragments/protocol.js
wallets/client/fragments/wallet.js
wallets/client/hooks/query.js
wallets/lib/protocols/clink.js
wallets/lib/protocols/docs/dev/clink.md
wallets/lib/protocols/index.js
wallets/lib/validate.js
wallets/server/protocols/clink.js
wallets/server/protocols/index.js
wallets/server/resolvers/util.js

supersedes #2487
I changed my mind regarding adding CLINK debits + offers in #2487. This now only closes #1376.
[CLINK spec](https://clinkme.dev/specs.html)
**TODO**
- :white_check_mark: attach CLINK with `noffer`
- :white_check_mark: q&a
- :white_check_mark: use our custom timeout for wallets
- :white_check_mark: use custom invoice description and expiry
- :white_check_mark: replace `Invalid Amount` error if amount is below minimum with more user-friendly error
- :white_check_mark: add dev documentation how to attach
- :question: add user guide
- :question: ~use abort signal~ _SDK does not support abort signals, but that's okay, not that important_
- :white_check_mark: close websocket after invoice was received
see #2531 
- Lightning.Pub's default minimum amount for invoices seems to be …

CLINK offers
