stackernews/stacker.news

components/search.js
Currently, the new search feature redirects to 404 when searching for an empty string. 
> Disclaimer: I have not run/tested this code but I do believe it will work.
=> Don't submit empty search queries

components/login.js
Talked about in issue #120 I have added a message explaining how registration works on the login screen.
=> Add register message to login screen

docker-compose.yml, worker/Dockerfile
- Added worker image in docker-compose.yml
- Running install command and running worker/index.js on startup
- Added Docker file in /worker to run new image on port 8080
=> Created new image for worker, running work script on startup

worker/wallet.js
Not necessary but just looking through the code and dipping my toes in
=> Fixing a Few Comment Typos

pages/settings.js
=> Fix broken link to top users in settings

pages/api/auth/[...nextauth].js
Fixes:
https://github.com/stackernews/stacker.news/issues/231
=> limit github oauth scope to public user info

components/item-act.js
https://github.com/stackernews/stacker.news/assets/27162016/332f812f-092f-41c8-a38c-cbd6af551acd
As discussed here: https://github.com/stackernews/stacker.news/commit/e2aceee234b5e65808d8e7ec50b6d17fc1bb832b#r112267744
=> Tips update

prisma/seed.js
Not sure if this was overlooked?
Users can no longer create posts with no sub set. So I think it makes sense to reflect this in the seed script?
=> Add subName to seed

lib/url.js
https://github.com/stackernews/stacker.news/assets/27162016/be7b2179-e042-45f1-a6cb-6d7422911af8
=> Fix ensureProtocol not trimming whitespace

components/link-form.js
Closes #244
https://github.com/stackernews/stacker.news/assets/27162016/66c39691-ce7a-4380-881a-c7174833e45b
=> Fix no dupes check after link unshortening

api/resolvers/item.js, api/resolvers/notifications.js, api/resolvers/user.js, api/typeDefs/item.js, components/item-info.js, components/subscribe.js, fragments/comments.js, fragments/items.js, prisma/migrations/20230531043651_thread_subscription/migration.sql, prisma/migrations/20230601003219_comments_with_me_subscription/migration.sql, prisma/schema.prisma
Closes #283 
https://github.com/stackernews/stacker.news/assets/27162016/20ae2fbe-41a2-47a9-823b-a1621e4e6977
=> Add thread subscriptions

api/ssrApollo.js
Close #289 
https://github.com/stackernews/stacker.news/assets/27162016/5cd39cb1-cf5a-4709-8948-0dca68797f3b
=> Redirect to /login on /settings 401

pages/login.js, pages/signup.js
https://github.com/stackernews/stacker.news/assets/27162016/25a230f0-7bdb-448b-922d-2ab267d57b05
=> Use fallback instead of 500 if callback malformed

api/resolvers/item.js
https://github.com/stackernews/stacker.news/assets/27162016/95c9ddbe-dccd-48fe-b344-c3a2d44a86c3
Close #291
=> Match any port in dupe check

components/notifications.js
I've seen your TODO and I agreed:
> // TODO: oh man, this is a mess ... each notification type should just be a component ...
I've tested this by using mock data and comparing /notifications before and after the refactor.
<details>
<summary>mock data</summary>
```js
// components/samples.js
export const SAMPLES = [
{
__typename: 'InvoicePaid',
earnedSats: 100,
invoice: { 
id: 'id'
}
},
{
__typename: 'Invitification',
invite: {
invitees: [1, 5, 2],
id: 'clh91njlp00007un4rfcfc3ve'
}
},
{
__typename: 'Earn',
earnedSats: 69420,
sortTime: new Date().toISOString(),
sources: {
posts: 100,
comments: 141,
tips: 124
},
},
{
__typename: 'Referral'
},
{
__typename: 'Votification',
earnedSats: 1314,
item: {
sats: 134,
ncomments: 10,
title: '<random title>',
user: {
name: 'foo'
}
}
},
{
__typename: …
```
=> refactor: create component per notification type

docker-compose.yml
I realized that I lose all my data when I stop the container manually without this.
=> Use docker volume for db data

next.config.js
Maybe this fixes all these errors:
=> Fix CORS in service worker

components/upvote.js, styles/globals.scss
https://github.com/stackernews/stacker.news/assets/27162016/2ca6d796-6a90-4530-8e23-6c48cbdb99d5
=> Fix darkmode in walkthrough popover

api/resolvers/item.js
=> Add nym in reply notification

.env.sample, api/imgproxy/index.js, api/resolvers/item.js, components/form.js, components/item-full.js, components/text.js, docker-compose.yml, lib/md.js, lib/url.js
Here's a video demo of the feature:
https://www.loom.com/share/7e6ed97981a64840b25d9e62507eb279
> (please note, the `IS_NEW` state has been removed since I recorded the loom)
This code is quite rough and ready, if we're happy with the basic direction I'm happy to refine it further.
=> Render images without markdown and use image proxy

api/resolvers/user.js
=> Fix maxStreak for users with running best streak

next.config.js
=> add cors headers to /api/lnwith route

.platform/nginx/conf.d/elasticbeanstalk/00_application.conf, .platform/nginx/nginx.conf
=> Remove Content-Length header for requests to /api/lnauth

api/resolvers/notifications.js, api/webPush/index.js
=> Enhance logging related to web push

components/comment.js, prisma/seed.js
Don't show the OP badge next to comments from `anon` on posts from `anon`
Also added a post to the seed file from anon, with a comment by anon for easier testing
Addresses #406
=> Remove OP badge for comments by anon on posts by anon

components/item-full.js
Closes #408 
https://files.ekzyis.com/public/sn/youtube-player-x-overflow.mp4
=> Fix youtube player x-overflow

api/resolvers/item.js, api/typeDefs/user.js, fragments/users.js, lib/validate.js, pages/settings.js, prisma/migrations/20230818184016_hide_bookmarks/migration.sql, prisma/schema.prisma
A new feature - give stackers the ability to hide their bookmarks from other stackers (and non-logged-in users).
Includes:
1. A new boolean flag on the Users table
2. A new checkbox in the user settings page
3. Some special logic in the item API resolver to ensure that a stackers' bookmarks are meant to be shared, and returns empty results if not.
Let me know if I overlooked anything, this ended up requiring fewer changes than expected...
EDIT: I originally posted about this here: https://stacker.news/items/206443
=> Add new user setting to hide bookmarks from other users (and anon)

components/form.js, components/text.js
=> Fix click to load in preview

pages/api/lnwith.js
=> Fix negative maxWithdrawable

api/resolvers/wallet.js
Could not reopen #436 because I force-pushed the branch - and apparently this prevents reopening PRs
=> Fix expireSecs ignored for anons

api/resolvers/item.js, api/resolvers/notifications.js, api/resolvers/user.js, api/typeDefs/notifications.js, api/typeDefs/user.js, components/action-dropdown.js, components/item-info.js, components/notifications.js, components/subscribeUser.js, components/user-header.js, fragments/notifications.js, fragments/users.js, prisma/migrations/20230826005627_user_subscription/migration.sql, prisma/schema.prisma
Closes #442 
See #442 for the details of how this is implemented. It encapsulates the technical proposal.
TODOs:
=> Subscribe to a user

components/toast.js, components/toast.module.css
Closes #456 
Shamelessly borrowed from https://muffinman.io/blog/ios-safari-scroll-position-fixed/
=> Fix toast weirdness on iOS scrolling

api/resolvers/item.js
Closes #475 
Dynamic push notification body based on whether the item is a post or a reply
=> Vary push notification body for subscriptions based on whether item is post

components/reply.js
=> Fix replying to wrong comment

api/resolvers/item.js, api/resolvers/notifications.js, api/resolvers/user.js, api/typeDefs/notifications.js, api/typeDefs/user.js, api/webPush/index.js, components/notifications.js, fragments/notifications.js, fragments/users.js, pages/settings.js, prisma/migrations/20230901185713_notify_fwd_zap/migration.sql, prisma/schema.prisma
Closes #458 
Support configurable notifications when a post for which you are forwarded gets zapped
This is controlled by a new boolean flag in user settings
=> Notifications for when you are forwarded sats from a post

api/typeDefs/user.js, components/header.js, components/hidden-wallet-summary.js, fragments/users.js, lib/validate.js, pages/settings.js, pages/wallet.js, prisma/migrations/20230912122629_hide_wallet_balance/migration.sql, prisma/schema.prisma
Closes #480 
I tried to keep `<Link>` by using `event.preventDefault()` in `onLongPress` (and additionally in `onShortPress`) but it kept navigating.
So I used `router.push('/wallet')` in `onShortPress` instead.
Does this introduce undesired behavior?
Also wondering if we should mention this feature in the FAQ somewhere. But afaict, there is no "privacy" section yet.
Maybe just show a help icon next to the privacy section header and mention this?
=> Hide wallet balance

components/lightning.js, pages/rewards/index.js
=> Lightning strike on donation, if enabled. Else success toast

lib/rss.js
=> Add category tag to RSS feed

docs/useful-dev-commands.md
I figured I'd share this file I'd been carrying around locally. I could also add some of these to `package.json` as scripts, if that would be better. Let me know if you think this is valuable to share!
=> Add useful dev commands doc for others to reference

prisma/seed.js
Updated the seed file to generate a post with 200 comments in total, randomly placed at various depths. I made this to help debug the rendering perf issue on posts with a lot of comments.
=> Add a discussion post with a lot of comments to the seed file to help debug in dev

api/resolvers/item.js
Closes #537 
Don't create mentions when mentioning yourself. By extension, also don't send yourself a push notification when mentioning yourself
=> Self mentions

sw/index.js
Fixes #568
https://github.com/stackernews/stacker.news/assets/27162016/153d4b96-d8c1-4425-9f9a-95513c6e472a
=> Fix empty push notifications

components/share.js
Basically the title... I wanted to use shared URLs in localhost and they were pointing to prod.
=> Dynamic protocol, host for share URLs so they work on localhost and in prod

api/typeDefs/user.js, fragments/users.js, lib/validate.js, pages/settings.js, pages/wallet.js, prisma/migrations/20231010110432_withdraw_max_fee_default/migration.sql, prisma/schema.prisma
=> Add a setting for Default Withdrawal max fee

api/resolvers/notifications.js, components/item-info.js, prisma/migrations/20231710162230_self_subscription/migration.sql
For issue #512. This is intended to be the MVP.
=> Allow unsubscribing from our own threads

components/text.js, components/text.module.css
For issue #437 
Will change both editing box preview and posted content:
=> Embed Youtube videos in posts for valid Youtube URLs

lib/item.js
Not tested but pretty sure that's it.
Context: https://stacker.news/items/291566
=> Fix TypeError regarding matchAll

sw/eventListener.js
=> Fix FORWARDEDTIP change lost in serviceworker

api/resolvers/item.js
=> Additionally compare user ids during bookmark privacy check

components/user-header.js
=> Fix QR code overflow on mobile

lib/push-notifications.js, sw/eventListener.js
=> Fix missing merge of FOLLOW push notifications

components/user-header.js
Fix #613 
https://github.com/stackernews/stacker.news/assets/27162016/73b597be-5290-44a2-93da-24ae685c422e
=> Fix stale images

sw/eventListener.js
This change makes resubscriptions from #597 backwards compatible by only running the new resubscribe code if the old push subscription was saved under service worker version 2.
See https://github.com/stackernews/stacker.news/pull/597#issuecomment-1797099903
=> Only resubscribe on compatible old subscriptions

api/resolvers/item.js
To close #209
Turned out postgres/regex meta characters weren't escaped. (The %20 mentioned in the original issue was working only by accident because % in a postgres regex matches any string.)
=> Fix dup detection for links with "+" (for a space)

worker/deleteUnusedImages.js
Close #611 
https://github.com/stackernews/stacker.news/assets/27162016/c464c746-066a-4ae2-889a-d5114e378ea7
=> Delete unpaid anon uploads every hour

components/image.js
Fix #607 
https://github.com/stackernews/stacker.news/assets/27162016/7954f702-56f3-4a07-877c-de28ccf02f80
Forgot to include in video, but image still renders fine so I think this is it. No need for canvas drawing.
Credits go to https://stackoverflow.com/a/77472484
=> Strip EXIF data before upload on client

next.config.js
https://stacker.news/items/317414/r/WeAreAllSatoshi
=> enable prod sourcemaps in browser

components/header.js
Fix #625 
https://github.com/stackernews/stacker.news/assets/27162016/b10721c7-aaae-498c-bf84-115f5f006adb
=> Unsubscribe on signout

pages/wallet.js
=> Use textarea for unintended DMs

components/reply.js
https://github.com/stackernews/stacker.news/assets/27162016/01a562b4-9fd3-4527-8ac4-feb89bfed137
=> Fix bio replies

db/Dockerfile, docker-compose.yml
=> Use docker container with ip4r installed

pages/wallet.js
Related to #720 
https://github.com/stackernews/stacker.news/assets/27162016/42313fd4-06d0-4c58-8f8d-20618090dd25
=> Disable autocomplete for withdrawal invoices

components/serviceworker.js, sw/eventListener.js
Was working on this code currently anyway and I also added some documentation regarding the message types.
=> Fix usage of hardcoded strings for sw message types

components/bounty-form.js, components/comment-edit.js, components/discussion-form.js, components/job-form.js, components/link-form.js, components/poll-form.js, components/reply.js, lib/form.js
This might fix #728 
Tested by creating a post with no mention, with bad mention and with correct mention.
Got no notification, warning notification and success notification.
=> Refactor delete notification code

scripts/newsletter.js
https://stacker.news/items/379497/r/WeAreAllSatoshi
=> add link to email signup page for newsletter in newsletter signature

sw/eventListener.js
=> Fix push notification counting on iOS devices

api/resolvers/wallet.js, lib/lnurl.js, lib/validate.js, pages/settings/wallets/lightning-address.js, worker/wallet.js
- Fixes `IsNaN` checks. See https://github.com/stackernews/stacker.news/pull/746#discussion_r1451035611
- Support HTTPS during development. See https://github.com/stackernews/stacker.news/pull/746#discussion_r1451105983
- Disallow circular automated withdrawals
---
_I can also do separate PRs or you cherry pick the commits you want_
=> Small changes regarding automated withdrawals

api/resolvers/user.js
This fixes this page: https://stacker.news/top/stackers/day?by=posts
=> Fix 'column Item.day does not exist'

components/invoice.js, worker/wallet.js
https://github.com/stackernews/stacker.news/assets/27162016/67a92425-1abd-477f-9ce9-e037d71a6f3e
=> Finalize hodl invoices after payment within 60 seconds

api/resolvers/item.js, components/items.js
Related to https://github.com/stackernews/stacker.news/pull/783#issuecomment-1925919942
TODO:
=> Fix pinned items don't show up in home

api/resolvers/search.js, contributors.txt, docs/testing-search.md
Fixes: https://github.com/stackernews/stacker.news/issues/776
Updates `/api/resolvers/search.js` to wildcard match title and text on url passed in `url:` filter when searching.
=> Improved ux for domain only searches

api/resolvers/item.js, api/resolvers/sub.js, api/typeDefs/sub.js, api/typeDefs/user.js, components/item-info.js, components/sub-select.js, components/territory-form.js, components/territory-header.js, fragments/items.js, fragments/subs.js, fragments/users.js, lib/validate.js, pages/settings/index.js, prisma/migrations/20240205161535_add_nsfw_to_sub/migration.sql, prisma/migrations/20240207173333_add_nsfw_mode_to_user/migration.sql, prisma/schema.prisma
Closes https://github.com/stackernews/stacker.news/issues/713
Updated territory form with nsfw checkbox:
Info modal for nsfw option:
Territory header with nsfw badge:
=> Add nsfw setting to territories

middleware.js
=> Allow blob: scheme in CSP

pages/email.js, pages/invites/index.js, pages/invoices/[id].js, pages/live.js, pages/withdrawals/[id].js
Pages missing:
- offline (SSR doesn't make sense)
- 400 (SSR not possible)
- 500 (SSR not posible
=> Force SSR to include CSP nonces on page reload

middleware.js
=> Fix comment (unsafe-eval isn't used in prod)

components/qr.js, components/webln/index.js, components/webln/nwc.js
fix #819 fix #820
_Wow, it's suddenly 5am here. Will take another look at this when I slept lol_
=> Fix QR code interaction with WebLN provider

components/toast.js
=> Fix toast autohide

components/footer.js, contributors.txt
We should probably use user ids in contributors.txt but contributors usually don't know their user id so we would have to look it up for them.
=> Changed my nym to ek

components/image.js
* Adding tabindex to ImageUpload div wrapper in order to make it selectable
* Adding keyboard event handler to listen to Enter key stroke and trigger file upload selection
=> Trigger image upload from keyboard (#891)

components/item.js
=> Change poll icon color when active (#680)

README.md
I found this while reading the new readme and felt compelled to fix it :D
=> Super minor typo in the readme

api/resolvers/item.js, api/resolvers/rewards.js, api/resolvers/serial.js, api/resolvers/sub.js, api/resolvers/wallet.js, pages/api/lnurlp/[username]/pay.js, pages/invites/[id].js, worker/auction.js, worker/earn.js, worker/territory.js, worker/wallet.js
* merged `serializeInvoiceable` with `serialize`
* renamed `checkInvoice` to `verifyPayment` since it can be confused with `checkInvoice` from the worker.
* added support for conditional queries to `serialize` by filtering the input array with `.filter(q => !!q)`
=> Merge serializeInvoiceable with serialize

components/form.js
This is another nice feature I wanted for a long time :)
=> Allow pasting image from clipboard

worker/autowithdraw.js
=> Fix LND autowithdrawal error message

components/form.js
=> remove leaky text in uploadMarker

lib/validate.js, middleware.js
This is useful for connecting to LNbits running inside a VPN without HTTPS
Yes
Yes
=> Allow http: and ws: in dev CSP

.gitignore, scripts/nwc
I figured I should open-source the script I use to test NWC as a sending wallet.
=> Add script to use NWC with stacker lnd

components/upvote.js
Simple change that I wanted to get out of the way while working on zap UX
=> Don't repeat upvote fill color

components/item-full.js
=> fix: show related items on pinned items

api/resolvers/item.js
=> fix: deny zaps for deleted items

api/resolvers/user.js
=> Fix no red square for territory posts

components/fee-button.js
The cursor didn't switch to a pointer for the anon info. This PR fixes that.
=> Fix missing pointer for anon info

api/resolvers/item.js
This might already be it but need to check
=> Use global score for top

components/form.js
Fixes #1230 
This PR ensures that any image fee errors are just logged to the console (as per the comment in the issue).
=> Avoid Showing Image Fee Error

api/resolvers/item.js, api/resolvers/rewards.js, api/resolvers/serial.js, api/resolvers/sub.js
tACK 63280987
* Tested zaps and custom zaps from custodial balance, from attached wallet and as anon
* Tested replying as stacker and anon, editing as stacker
* Tested posting as stacker and anon
=> Fix anon payment verification

components/comment.js, components/dont-link-this.js, components/item-info.js, components/item.js, components/upvote.js
=> Fix downzaps

components/use-crossposter.js
* add link back to SN item in `content` of event
* fix inconsistent `content` generation
[context](https://coracle.social/notes/nevent1qy88wumn8ghj7mn0wvhxcmmv9uq35amnwvaz7tmwdaehgu3wwpkx2cnrdpskjm3wdaexwtcpzdmhxue69uhk7enxvd5xz6tw9ec82c30qyv8wumn8ghj7un9d3shjtnrw4e8yetwwshxv7tf9uq32amnwvaz7tmjv4kxz7fwv3sk6atn9e5k7tcprdmhxue69uhhyetvv9ujumn0wd68yurvv438xtnrdakj7qgewaehxw309aex2mrp0yh8xmn0wf6zuum0vd5kzmp0qywhwumn8ghj7mn0wd68ytndw46xjmnewaskcmr9wshxxmmd9uq3wamnwvaz7tmjv4kxz7fwwpexjmtpdshxuet59uqzqfq705tsz0cnnyp7x52judrkekqhgje4qpw539z8tj0zq9qwvq5dex5ncp)
=> Nostr crossposting backlink + content fix

.env.development, README.md, api/resolvers/blockHeight.js, docker-compose.yml, lib/sndev.js, sndev, worker/index.js
This makes it easier to set and unset specific `sndev` services. It also prevent unrun services from trying to run and logging a bunch. Bonus: I updated the readme for some out of date stuff.
=> better service enable/disable in dev environment

prisma/migrations/20240812234244_update_bio_marker/migration.sql
=> Add migration to fix missing item bio marker

api/resolvers/item.js
=> Fix freebie comment edits like a post

fragments/wallet.js
Forgot to include this change in #1318
=> Fix missing fragment name update

prisma/migrations/20240821072645_rename_lnbits_pk/migration.sql, prisma/schema.prisma
This didn't cause any bugs because we use the id of the `Wallet` table.
Yes, this shouldn't cause any downtime
Yes
No
=> Rename LNbits primary key column from 'int' to 'id'

.github/pull_request_template.md
do https://github.com/stackernews/stacker.news/pull/1321#issuecomment-2302416933
=> Update QA question in PR template

prisma/migrations/20240823045403_rename_nwc_pk/migration.sql, prisma/schema.prisma
same issue as #1321 but for NWC
=> Rename NWC primary key column from 'int' to 'id'

lib/nostr.js, worker/nostr.js
cherry-pick of bugfixes in 76fb6a44de166755ee96b6d8fbd99848826f2128 from #1311
=> Fix websocket leaks

docker-compose.yml, wallets/nwc/ATTACH.md
Primal relay seems to be more reliable and not have rate limits.
=> Switch NWC from Damus to Primal relay

components/modal.js
Alternative fix instead of #1347. This works also and is cleaner imo.
=> Use undefined instead of empty function for onHide

api/resolvers/item.js, components/accordian-item.js, components/link-form.js, prisma/migrations/20240903180612_url_index/migration.sql, prisma/schema.prisma
closes #1344
This makes dupe check use regex and adds an index on `url`.
Additionally:
- improves dupe check loading ui/ux
- debounces dupe check calls
8. I tested an article url and both youtube and hn urls and variations.
=> improve dupes

wallets/nwc/index.js
The spec mentions the following:
> for kind n such that 20000 <= n < 30000, events are ephemeral, which means they are not expected to be stored by relays.
This applies to NWC events. This means that we need to subscribe _before_ we publish the request.
See https://github.com/nostr-protocol/nips/blob/master/01.md
This fixes the NWC connection to Alby Hub.
Thanks to @riccardobl for mentioning this issue! I didn't connect the dots and forgot about it.
yes
`10`, tested locally with Alby Hub running in docker and worked immediately
=> Fix ephemeral events missed

components/text.js, components/text.module.css
I don't know if this should ship. It needs more testing but I was frustrated by only one image/video being on each line.
The goal to allow for responsive grid-like behavior with just css.
`3`
no
=> css to put adjacent images/video into vertical alignment

lib/validate.js, pages/settings/index.js
Close #1407 
yes
`8`. I tested saving with and without wss://.
n/a
no
=> Add wss:// to user relays by default

api/paidAction/itemUpdate.js, api/resolvers/item.js, components/item-info.js
Fixes #1350 
I debated removing the `pending` state for #1352, but I suspect posts/comments will primarily be paid for with fee credits when we transition.
QA: `7`
=> allow edit of pending items

docker/db/Dockerfile
Hello everyone. I was setting up a dev enviroment and getting this error on `./sndev start`:
```
> [db 2/2] RUN apt-get update     && apt-get install --no-install-recommends -y postgresql-13-ip4r     && rm -rf /var/lib/apt/lists/*:
16.77 Get:1 http://security.debian.org/debian-security buster/updates InRelease [34.8 kB]
17.34 Ign:2 http://apt.postgresql.org/pub/repos/apt buster-pgdg InRelease
17.47 Get:3 http://deb.debian.org/debian buster InRelease [122 kB]
17.64 Err:4 http://apt.postgresql.org/pub/repos/apt buster-pgdg Release
17.64   404  Not Found [IP: 87.238.57.227 80]
53.74 Get:5 http://security.debian.org/debian-security buster/updates/main amd64 Packages [610 kB]
81.88 Get:6 http://deb.debian.org/debian buster-updates InRelease [56.6 kB]
126.6 Get:7 http://deb.debian.org/debian …
```
=> chore: update postgres docker container version

pages/[name]/index.js
=> feat: cache bio draft

api/lnd/index.js
Fix https://stacker.news/items/729075
=> Fix lnaddr withdrawals

wallets/index.js
fix wallet save, see https://github.com/stackernews/stacker.news/pull/1487#issuecomment-2423933397
=> Fix wallet client validation

components/form.js
=> Use -webkit-text-security to hide passphrase

components/payment.js
This more directly addresses the underlying problem that #1555 solves. See the discussion there for more explaination.
Basically this creates a new invoice controller for every payment that's made rather than reusing the same one.
This can use a more serious refactor, but it's not worth it right now - it needs a real "meditation" to figure out how to improve it.
QA: `6`. I tested zaps and greped around for any use of `waitUntilPaid` which was very minimal.
@ekzyis can you confirm it fixes the issue you originally identified. I don't have a reproduction.
=> fix invoice waiting

api/paidAction/README.md, api/paidAction/index.js, api/paidAction/zap.js, lib/constants.js, lib/validate.js, wallets/server.js, wallets/wrap.js, worker/paidAction.js
Actions can define their sybil fee for wrapped invoices
=> configurable sybil fee

components/wallet-logger.js
Very likely fix #1579 without reproducing it.
I also verified that the latest known timestamp is used during polling so that should also work as intended.
yes
`5`. Did some small sanity checks as mentioned in the description.
n/a
no
=> Fix missing sorting of wallet logs

api/resolvers/user.js
Fix this:
https://github.com/user-attachments/assets/2c6ecc00-5b8e-4401-841c-fab7b57be939
Tested with anon and logged in. Also tested with items that were paid with fee credits (`invoiceActionState IS NULL`).
=> Fix unpaid items are counted

wallets/lightning-address/server.js
Caused by #1621 
I didn't test, but this looks good
=> Fix lnaddr not returning payment request

components/payment.js
This function wasn't used anywhere anymore.
=> Remove unused function usePayment

lib/webPush.js
Fix #1661
yes
`7`. Tested with a deposit.
n/a
no
=> Fix deposit push notifications

api/resolvers/invite.js, components/invite.js
Fix this:
https://github.com/user-attachments/assets/ddb722b7-285f-4dce-b081-3591f84420f7
yes
`8`. See video.
n/a
no
=> Fix missing authentication check for invite revocation

docker-compose.yml
cherry-picked commits from #1679
=> CLN: Use port 9735 and log to stdout

wallets/config.js
If validation for a sender wallet failed, the error message wasn't logged.
I made sure this only logs errors during sender wallet validation since logging of receiver wallet validation errors is already handled on the server.
Maybe at some point we can enable device sync by default (by simply generating a password for them which they can change if they want) and make it mandatory, then we never have to story anything related to wallets on the client. We can then probably also move sender logs to the server and we need to deal less with all this sender/client vs receiver/server stuff.
yes
`7`. Tested with a …
=> Fix missing logging of sender wallet validation error

lib/time.js
=> Fix missing usage of new TimeoutError

lib/cln.js, wallets/cln/server.js
Similar to #1725 
yes
`8`. Tested by attaching CLN which creates a test invoice.
n/a
no
=> Refactor CLN function signatures

api/resolvers/item.js
fix #1735 
regression happened in #1716 
yes
tbd
n/a
no
=> Fix admin edits

components/vault/use-vault-configurator.js
fixes #1743 
Following repro steps, this does not delete the local nwc key.
=> update cache on vault key update

prisma/migrations/20241223203751_renerf/migration.sql
Title says it all.
QA: `8`. Backtest was good. We can still rank high but have to work hard for it and are frequently beat.
=> renerf sn associated accounts by decreasing zap score by half

pages/rewards/index.js
=> tyle -> style

components/nav/common.js
_Updated on `Fri Dec 20 23:09:21 2024 UTC`_
A simple change to address issue #1648 by removing a conflicting tailwind class and only passing it when it's necessary.
Yes
10
Yes
No
=> fix: adjusts the navbar and signup button for mobile

components/item-act.js
Fixes: https://github.com/stackernews/stacker.news/issues/1803
=> pass hasSendWallet to ItemAct actor

scripts/welcome.js
Refactor script I created in #1827
=> Welcome series script update

api/lnd/index.js
fix #1853 
If we are a hop hint, use alternate form of `estimateRouteFee`.
QA: `8` - setup cln with private only channels to node and recreated error, verified fix, then verified payment request is still used to estimate fees when we aren't a hop hint
=> If we are a hop hint, use alternate form of `estimateRouteFee`

docs/user/faq.md
=> Add territory stats answer to FAQ

docs/user/faq.md
https://stacker.news/items/879080?commentId=879130
_It might look like unnecessary additional work to keep the version in the repo updated, but it's actually great to see the changes_
=> FAQ feedback

components/dark-mode.js
I noticed that the `useEffect` in `useDarkMode` does not return the cleanup function for all the listeners we attach in `listenForThemeChange`.
How I tested:
https://github.com/user-attachments/assets/df7382d2-8a26-45b2-a097-271557598ffa
I don't think this had any significant impact on memory on the client but I haven't found a way to analyze this. Maybe there's a way to do this with the performance tab in the browser dev tools but as mentioned, I don't think this is going to be significant so I'll try to get familiar with the performance tab when it's more important.
yes
`8`. See video.
**For frontend …
=> Fix missing cleanup of dark mode listeners

worker/autowithdraw.js
Follow-up of #1907, see https://github.com/stackernews/stacker.news/pull/1907/commits/40814c13f7623edb73f946e1021ca943318bffdd#r1956985603
=> Fix autowithdrawal error handling

contributors.txt
Added myself to contributors.txt as per [README](https://github.com/stackernews/stacker.news?tab=readme-ov-file#contributor-badges-on-sn-profiles).
=> Claim contributor's badge

contributors.txt
Adding self to contributors.txt per README
=> Add SimpleStacker to contributors.txt

wallets/payment.js
fix #1943
yes
`7`. It fixes the issue mentioned in #1943 in an obvious way.
n/a
no
=> Fix undefined db for wallet logs

.github/workflows/extend-awards.yml
Implements #1849 
Change trigger to push_request_target.
=> Change trigger to push_request_target

docs/user/faq.md
Adding the missing answers to the questions in https://stacker.news/items/911174
=> Update FAQ with wallet questions

wallets/phoenixd/server.js
Fix #1964
Support .onion urls like lnbits does.
=> Support .onion for phoenixd

components/user-header.js
Closes https://github.com/stackernews/stacker.news/issues/1982
yes
8
n/a
no
=> Fix nym editting state not changing on back button

components/account.js, lib/auth.js
`maybeSecureCookie` was the old, worse way to do what `cookieOptions` does.
yes
`8`. Tested by switching to anon and back. This is all this code does.
n/a
no
=> Use cookieOptions for pointer cookie

lib/auth.js
`MULTI_AUTH_REGEXP` was meant for this.
=> Use MULTI_AUTH_REGEXP to test for multi auth keys

.env.development, package-lock.json, package.json, prisma/migrations/20250325224718_auto_social_poster/migration.sql, prisma/schema.prisma, worker/index.js, worker/socialPoster.js
We are going to post hot posts periodically. This adds both X and nostr posting.
It posts the hottest story that hasn't already been posted on the hour, every hour. 
Message format is like the following:
```
Turning Tires into Bitcoin
by offordscott to ~bitcoin_Mining
2,563 sats so far
https://stacker.news/items/793375/r/sn
```
On X and nost clients that support it, the link will show as a preview.
=> automated social posting

components/notifications.js, lib/webPush.js, worker/reminder.js
This is the current text for reminder push notifications:
> **this is your requested reminder**
> you asked to be reminded of this post/comment
It only tells me with a lot of words that it's a reminder and if it's for a post or comment.
However, we can let the title start with "you" like a lot of other push notifications and include the most important information in the body: what did I want to be reminded of?
yes
`8`. Tested with a post and a comment.
n/a
**Did you introduce any new environment variables? If so, call them …
=> Refactor reminder push notifications

components/nav/common.js, components/nav/mobile/offcanvas.js
Just some code reuse to pave the way for wallet indicators with less changes
=> Refactor indicators

pages/wallets/index.js
This only remove a blank line and some annoying-to-look-at braces.
I wish our linter would be so opinionated that we could literally not push code that could be formatted in a different way without failing it. Or maybe I should be careful what I wish for? :eyes:
=> Formatting

wallets/lightning-address/index.js
=> Remove mention of autowithdrawal for lnaddr

lib/validate.js, wallets/lightning-address/index.js
I will reuse this validator in a future PR so let's get this tiny refactor out of the way
yes
`8`. Tested that validator still works:
n/a
no
=> external lightning address validator

wallets/nwc/server.js
=> Fix NWC recv

lib/nostr.js
fix #2129
https://github.com/user-attachments/assets/728e09f2-4e0e-4e24-b2fb-e1b703a9499b
=> Close every relay in every pool

wallets/server.js
=> Remove self-referential import

api/resolvers/sub.js, api/typeDefs/sub.js, components/adv-post-form.js, components/form.js, fragments/subs.js
Closes #992.
Added territory autocomplete functionality to enhance the user experience when entering territory names. This feature provides suggestions as users type territory names using the tilde (~) prefix, similar to how the existing user mention system works with @ mentions.
Key changes:
- Added a new GraphQL query `subSuggestions` to fetch territory name suggestions based on similarity to input
- Created a `TerritorySuggest` component that mirrors the existing `UserSuggest` component
- Integrated territory suggestions in the markdown input field
- Added appropriate fragment for territory suggestions
The implementation follows the same pattern as the existing user mention system. Territory suggestions appear when typing "~" followed by any text, and users can navigate/select …
=> feat: Territory autocomplete

contributors.txt
=> add contributor

api/resolvers/search.js, docker/opensearch/init-opensearch.sh, scripts/nlp-setup
Added exact search functionality for quoted phrases and words. Modified the search resolver to use wildcard queries on keyword fields instead of multi_match phrase queries, which improves the accuracy of quoted searches by making them truly case-sensitive and exact.
This change ensures that when users search for content in quotes, the search will find exact matches rather than partial or fuzzy matches, providing more precise search results.
Closes #1391.
The existing implementation has issues with syntax highlighting for exact matches, matching the individual words instead of the exact input.
This implementation has two commits: one with no highlighting for exact words and a second one that enables something similar to the existing highlighting. I see no clean/simple way of implementing …
=> Exact search

docs/user/faq.md
I already updated the FAQ, this PR only updates the documentation in the repository.
=> Explain guns and horses in FAQ

wallets/client/context/reducer.js
Fix https://github.com/stackernews/stacker.news/pull/2286#pullrequestreview-3026558216
=> Fix KEY_STORAGE_UNAVAILABLE undefined

wallets/client/components/debug.js
Forgot to push the last commit that adds the 'ago' suffix as seen in the screenshot in #2301
=> Add 'ago' suffix to timestamps in wallet debug page

wallets/client/components/debug.js
=> Use proper grid for wallet debug info

components/carousel.js
Simple changes that I noticed while reviewing #2239. See commits for description.
Changes are so simple that I will merge immediately to continue the review
=> Carousel cleanup

components/show-new-comments.js
Fixes #2321 
Traversing existing comments only if it's a thread comment, caused inconsistencies for new comments arriving with their own existing children.
A better approach is to traverse existing comments only if it's a thread comment, **or** we got past the parent comment and are analyzing its new comments subtree.
https://github.com/user-attachments/assets/3042e377-df38-4e2a-a8fe-cbf27f177238
Let's examine the following comment structure with the actual recursion logic:
```
Root Item: 3 new comments
├── New Top-level Comment A
│   ├── New Comment B
│   └── (new) Existing Comment C
│       └── New Comment D
```
The count shows 3 new comments, but clearly these are 4 comments.
New Comment D, which is a new comment to an existing comment, got ignored
What happens is that we check new …
=> Fix non-thread live comments recursion logic

awards.csv
Manually added a row to awards.csv because of #2326
=> Extending awards.csv

.cursor/BUGBOT.md
This should prevent repetitive wrong reviews from @cursor like https://github.com/stackernews/stacker.news/pull/2335#discussion_r2232911383
We can add more stuff to it over time to make it smarter
see https://docs.cursor.com/bugbot#rules
=> Add review guideline for cursor bot

components/text.js
Closes https://github.com/stackernews/stacker.news/issues/2371
Yes... I think so, I can't imagine anyone using a hashtag link previously for any other purpose.
9
n/a
no
=> fix hashtag links opening in new tabs

api/paidAction/itemUpdate.js, api/paidAction/territoryUpdate.js, api/resolvers/upload.js
- replace `$queryRawUnsafe` with `$queryRaw`
- replace comment about object shape with simply destructuring the object
- return all fees as BigInt
yes
`10`. tested territory edits and item edits and fee button
n/a
no
=> improvements to upload fees code

api/resolvers/sub.js, contributors.txt
_A clear and concise description of what you changed and why._
fixes #2399 
=> fix: include subs in grace status in suggestions

wallets/client/components/form/index.js, wallets/lib/protocols/clnRest.js
- list up-to-date command to create rune first
- add info regarding which certificate we need since there are many (ca, client, server)
=> Update CLN createrune & certificate help

wallets/lib/protocols/lnbits.js
Accidentally removed it from receive instead of send in #2489
=> Fix 'LNbits send does not support tor'

lib/constants.js, wallets/lib/protocols/docs/user/albyhub.md, wallets/lib/wallets.json
Based on #2490 
Like #2494 
Link to guide: TBD
yes
`10`
n/a
n/a
=> Alby Hub guide

wallets/lib/wallets.json
Rizful has created a new guide with our new UI.
=> Add Rizful guide

lib/constants.js, wallets/lib/protocols/docs/user/coinos.md, wallets/lib/wallets.json
https://stacker.news/items/1230105
=> Coinos guide
